In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, StandardScaler
import taxonomia
import utils

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('./data/species_features.csv')
print(df.shape)
df.head()

(101200, 466)

,track_index,chroma_cens_kurtosis_01,chroma_cens_kurtosis_02,chroma_cens_kurtosis_03,chroma_cens_kurtosis_04,chroma_cens_kurtosis_05,chroma_cens_kurtosis_06,chroma_cens_kurtosis_07,chroma_cens_kurtosis_08,chroma_cens_kurtosis_09,chroma_cens_kurtosis_10,chroma_cens_kurtosis_11,chroma_cens_kurtosis_12,chroma_cens_max_01,chroma_cens_max_02,chroma_cens_max_03,chroma_cens_max_04,chroma_cens_max_05,chroma_cens_max_06,chroma_cens_max_07,chroma_cens_max_08,chroma_cens_max_09,chroma_cens_max_10,chroma_cens_max_11,chroma_cens_max_12,chroma_cens_mean_01,chroma_cens_mean_02,chroma_cens_mean_03,chroma_cens_mean_04,chroma_cens_mean_05,chroma_cens_mean_06,chroma_cens_mean_07,chroma_cens_mean_08,chroma_cens_mean_09,chroma_cens_mean_10,chroma_cens_mean_11,chroma_cens_mean_12,chroma_cens_median_01,chroma_cens_median_02,chroma_cens_median_03,chroma_cens_median_04,chroma_cens_median_05,chroma_cens_median_06,chroma_cens_median_07,chroma_cens_median_08,chroma_cens_median_09,chroma_cens_median_10,chroma_cens_median_11,chroma_cens_median_12,chroma_cens_min_01,chroma_cens_min_02,chroma_cens_min_03,chroma_cens_min_04,chroma_cens_min_05,chroma_cens_min_06,chroma_cens_min_07,chroma_cens_min_08,chroma_cens_min_09,chroma_cens_min_10,chroma_cens_min_11,chroma_cens_min_12,chroma_cens_skew_01,chroma_cens_skew_02,chroma_cens_skew_03,chroma_cens_skew_04,chroma_cens_skew_05,chroma_cens_skew_06,chroma_cens_skew_07,chroma_cens_skew_08,chroma_cens_skew_09,chroma_cens_skew_10,chroma_cens_skew_11,chroma_cens_skew_12,chroma_cens_std_01,chroma_cens_std_02,chroma_cens_std_03,chroma_cens_std_04,chroma_cens_std_05,chroma_cens_std_06,chroma_cens_std_07,chroma_cens_std_08,chroma_cens_std_09,chroma_cens_std_10,chroma_cens_std_11,chroma_cens_std_12,chroma_cqt_kurtosis_01,chroma_cqt_kurtosis_02,chroma_cqt_kurtosis_03,chroma_cqt_kurtosis_04,chroma_cqt_kurtosis_05,chroma_cqt_kurtosis_06,chroma_cqt_kurtosis_07,chroma_cqt_kurtosis_08,chroma_cqt_kurtosis_09,chroma_cqt_kurtosis_10,chroma_cqt_kurtosis_11,chroma_cqt_kurtosis_12,chroma_cqt_max_01,chroma_cqt_max_02,chroma_cqt_max_03,chroma_cqt_max_04,chroma_cqt_max_05,chroma_cqt_max_06,chroma_cqt_max_07,chroma_cqt_max_08,chroma_cqt_max_09,chroma_cqt_max_10,chroma_cqt_max_11,chroma_cqt_max_12,chroma_cqt_mean_01,chroma_cqt_mean_02,chroma_cqt_mean_03,chroma_cqt_mean_04,chroma_cqt_mean_05,chroma_cqt_mean_06,chroma_cqt_mean_07,chroma_cqt_mean_08,chroma_cqt_mean_09,chroma_cqt_mean_10,chroma_cqt_mean_11,chroma_cqt_mean_12,chroma_cqt_median_01,chroma_cqt_median_02,chroma_cqt_median_03,chroma_cqt_median_04,chroma_cqt_median_05,chroma_cqt_median_06,chroma_cqt_median_07,chroma_cqt_median_08,chroma_cqt_median_09,chroma_cqt_median_10,chroma_cqt_median_11,chroma_cqt_median_12,chroma_cqt_min_01,chroma_cqt_min_02,chroma_cqt_min_03,chroma_cqt_min_04,chroma_cqt_min_05,chroma_cqt_min_06,chroma_cqt_min_07,chroma_cqt_min_08,chroma_cqt_min_09,chroma_cqt_min_10,chroma_cqt_min_11,chroma_cqt_min_12,chroma_cqt_skew_01,chroma_cqt_skew_02,chroma_cqt_skew_03,chroma_cqt_skew_04,chroma_cqt_skew_05,chroma_cqt_skew_06,chroma_cqt_skew_07,chroma_cqt_skew_08,chroma_cqt_skew_09,chroma_cqt_skew_10,chroma_cqt_skew_11,chroma_cqt_skew_12,chroma_cqt_std_01,chroma_cqt_std_02,chroma_cqt_std_03,chroma_cqt_std_04,chroma_cqt_std_05,chroma_cqt_std_06,chroma_cqt_std_07,chroma_cqt_std_08,chroma_cqt_std_09,chroma_cqt_std_10,chroma_cqt_std_11,chroma_cqt_std_12,chroma_stft_kurtosis_01,chroma_stft_kurtosis_02,chroma_stft_kurtosis_03,chroma_stft_kurtosis_04,chroma_stft_kurtosis_05,chroma_stft_kurtosis_06,chroma_stft_kurtosis_07,chroma_stft_kurtosis_08,chroma_stft_kurtosis_09,chroma_stft_kurtosis_10,chroma_stft_kurtosis_11,chroma_stft_kurtosis_12,chroma_stft_max_01,chroma_stft_max_02,chroma_stft_max_03,chroma_stft_max_04,chroma_stft_max_05,chroma_stft_max_06,chroma_stft_max_07,chroma_stft_max_08,chroma_stft_max_09,chroma_stft_max_10,chroma_stft_max_11,chroma_stft_max_12,chroma_stft_mean_01,chroma_stft_mean_02,chroma_stft_mean_03,chroma_stft_mean_04,chroma_stft_mean_05,chroma_stft_mean_06,chroma_stft_mean_07,chroma_stft_mean_08,chroma_stft_mean_09,chroma_stft_mean_10,chroma_stft_mean_11,chroma_stft_mean_12,chroma_stft_median_01,chroma_stft_median_02,chroma_stft_median_03,chroma_stft_median_04,chroma_stft_median_05,chroma_stft_median_06,chroma_stft_median_07,chroma_stft_median_08,chroma_stft_median_09,chroma_stft_median_10,chroma_stft_median_11,chroma_stft_median_12,chroma_stft_min_01,chroma_stft_min_02,chroma_stft_min_03,chroma_stft_min_04,chroma_stft_min_05,chroma_stft_min_06,chroma_stft_min_07,chroma_stft_min_08,chroma_stft_min_09,chroma_stft_min_10,chroma_stft_min_11,chroma_stft_min_12,chroma_stft_skew_01,chroma_stft_skew_02,chroma_stft_skew_03,chroma_stft_skew_04,chroma_stft_skew_05,chroma_stft_skew_06,chroma_stft_skew_07,chroma_stft_skew_08,chroma_stft_skew_09,chroma_stft_skew_10,chroma_stft_skew_11,chroma_stft_skew_12,chroma_stft_std_01,chroma_stft_std_02,chroma_stft_std_03,chroma_stft_std_04,chroma_stft_std_05,chroma_stft_std_06,chroma_stft_std_07,chroma_stft_std_08,chroma_stft_std_09,chroma_stft_std_10,chroma_stft_std_11,chroma_stft_std_12,mfcc_kurtosis_01,mfcc_kurtosis_02,mfcc_kurtosis_03,mfcc_kurtosis_04,mfcc_kurtosis_05,mfcc_kurtosis_06,mfcc_kurtosis_07,mfcc_kurtosis_08,mfcc_kurtosis_09,mfcc_kurtosis_10,mfcc_kurtosis_11,mfcc_kurtosis_12,mfcc_max_01,mfcc_max_02,mfcc_max_03,mfcc_max_04,mfcc_max_05,mfcc_max_06,mfcc_max_07,mfcc_max_08,mfcc_max_09,mfcc_max_10,mfcc_max_11,mfcc_max_12,mfcc_mean_01,mfcc_mean_02,mfcc_mean_03,mfcc_mean_04,mfcc_mean_05,mfcc_mean_06,mfcc_mean_07,mfcc_mean_08,mfcc_mean_09,mfcc_mean_10,mfcc_mean_11,mfcc_mean_12,mfcc_median_01,mfcc_median_02,mfcc_median_03,mfcc_median_04,mfcc_median_05,mfcc_median_06,mfcc_median_07,mfcc_median_08,mfcc_median_09,mfcc_median_10,mfcc_median_11,mfcc_median_12,mfcc_min_01,mfcc_min_02,mfcc_min_03,mfcc_min_04,mfcc_min_05,mfcc_min_06,mfcc_min_07,mfcc_min_08,mfcc_min_09,mfcc_min_10,mfcc_min_11,mfcc_min_12,mfcc_skew_01,mfcc_skew_02,mfcc_skew_03,mfcc_skew_04,mfcc_skew_05,mfcc_skew_06,mfcc_skew_07,mfcc_skew_08,mfcc_skew_09,mfcc_skew_10,mfcc_skew_11,mfcc_skew_12,mfcc_std_01,mfcc_std_02,mfcc_std_03,mfcc_std_04,mfcc_std_05,mfcc_std_06,mfcc_std_07,mfcc_std_08,mfcc_std_09,mfcc_std_10,mfcc_std_11,mfcc_std_12,rmse_kurtosis_01,rmse_max_01,rmse_mean_01,rmse_median_01,rmse_min_01,rmse_skew_01,rmse_std_01,spectral_bandwidth_kurtosis_01,spectral_bandwidth_max_01,spectral_bandwidth_mean_01,spectral_bandwidth_median_01,spectral_bandwidth_min_01,spectral_bandwidth_skew_01,spectral_bandwidth_std_01,spectral_centroid_kurtosis_01,spectral_centroid_max_01,spectral_centroid_mean_01,spectral_centroid_median_01,spectral_centroid_min_01,spectral_centroid_skew_01,spectral_centroid_std_01,spectral_contrast_kurtosis_01,spectral_contrast_kurtosis_02,spectral_contrast_kurtosis_03,spectral_contrast_kurtosis_04,spectral_contrast_kurtosis_05,spectral_contrast_kurtosis_06,spectral_contrast_kurtosis_07,spectral_contrast_max_01,spectral_contrast_max_02,spectral_contrast_max_03,spectral_contrast_max_04,spectral_contrast_max_05,spectral_contrast_max_06,spectral_contrast_max_07,spectral_contrast_mean_01,spectral_contrast_mean_02,spectral_contrast_mean_03,spectral_contrast_mean_04,spectral_contrast_mean_05,spectral_contrast_mean_06,spectral_contrast_mean_07,spectral_contrast_median_01,spectral_contrast_median_02,spectral_contrast_median_03,spectral_contrast_median_04,spectral_contrast_median_05,spectral_contrast_median_06,spectral_contrast_median_07,spectral_contrast_min_01,spectral_contrast_min_02,spectral_contrast_min_03,spectral_contrast_min_04,spectral_contrast_min_05,spectral_contrast_min_06,spectral_contrast_min_07,spectral_contrast_skew_01,spectral_contrast_skew_02,spectral_contrast_skew_03,spectral_contrast_skew_04,spectral_contrast_skew_05,spectral_contrast_skew_06,spectral_contrast_skew_07,spectral_contrast_std_01,spectral_contrast_std_02,spectral_contrast_std_03,spectral_contrast_std_04,spectral_contrast_std_05,spectral_contrast_std_06,spectral_contrast_std_07,spectral_rolloff_kurtosis_01,spectral_rolloff_max_01,spectral_rolloff_mean_01,spectral_rolloff_median_01,spectral_rolloff_min_01,spectral_rolloff_skew_01,spectral_rolloff_std_01,tonnetz_kurtosis_01,tonnetz_kurtosis_02,tonnetz_kurtosis_03,tonnetz_kurtosis_04,tonnetz_kurtosis_05,tonnetz_kurtosis_06,tonnetz_max_01,tonnetz_max_02,tonnetz_max_03,tonnetz_max_04,tonnetz_max_05,tonnetz_max_06,tonnetz_mean_01,tonnetz_mean_02,tonnetz_mean_03,tonnetz_mean_04,tonnetz_mean_05,tonnetz_mean_06,tonnetz_median_01,tonnetz_median_02,tonnetz_median_03,tonnetz_median_04,tonnetz_median_05,tonnetz_median_06,tonnetz_min_01,tonnetz_min_02,tonnetz_min_03,tonnetz_min_04,tonnetz_min_05,tonnetz_min_06,tonnetz_skew_01,tonnetz_skew_02,tonnetz_skew_03,tonnetz_skew_04,tonnetz_skew_05,tonnetz_skew_06,tonnetz_std_01,tonnetz_std_02,tonnetz_std_03,tonnetz_std_04,tonnetz_std_05,tonnetz_std_06,zcr_kurtosis_01,zcr_max_01,zcr_mean_01,zcr_median_01,zcr_min_01,zcr_skew_01,zcr_std_01,Familia,Genero,Especie
0,1201,-1.231321,1.176471,-0.934772,0.424999,-1.485922,-0.864360,-0.508379,0.049587,-0.953203,-0.993964,-0.575746,-1.033606,0.305312,0.316698,0.287402,0.314261,0.417602,0.397584,0.375472,0.458163,0.473803,0.361516,0.389344,0.284121,0.222915,0.193979,0.244048,0.219077,0.323959,0.253624,0.300486,0.396437,0.360632,0.297575,0.312899,0.220091,0.221706,0.185186,0.250002,0.212928,0.301104,0.234029,0.293754,0.399912,0.358910,0.299235,0.304977,0.217191,0.139554,0.131232,0.189835,0.162325,0.239839,0.143407,0.248700,0.307205,0.270301,0.216358,0.209988,0.162813,0.074305,1.091380,-0.415809,0.886281,0.293461,0.570579,0.437026,-0.482348,0.068436,-0.241754,-0.056226,0.115531,0.044275,0.042118,0.026701,0.036724,0.060080,0.069728,0.030211,0.034617,0.052445,0.037569,0.044411,0.030548,0.107738,0.695763,-0.113077,1.102263,-0.919800,-0.514442,-0.679674,0.026381,-0.718438,-0.631632,-0.797313,-0.147312,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,0.516372,0.465831,0.540953,0.483488,0.656742,0.557740,0.634490,0.797051,0.732696,0.617895,0.645149,0.510703,0.491417,0.451171,0.509169,0.457225,0.640767,0.515378,0.631520,0.841706,0.747318,0.602607,0.635895,0.477984,0.041343,0.042842,0.086158,0.202956,0.099544,5.971722e-02,6.688542e-02,9.070589e-02,0.065553,0.070947,0.054888,0.043762,0.534961,0.772280,0.579205,0.991615,0.046460,0.511044,-0.040553,-0.818764,-0.424600,0.112764,-0.022317,0.545099,0.194075,0.179296,0.192973,0.155095,0.207269,0.219709,0.201275,0.196088,0.224392,0.199239,0.220513,0.191168,-0.620973,-0.413599,-0.924831,0.347720,-0.069479,-1.171980,-0.980379,-0.765643,-0.515362,-0.486856,-0.900503,-0.500747,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.545415,0.585150,0.621738,0.451184,0.461428,0.561890,0.603490,0.525149,0.493652,0.498068,0.544007,0.563587,0.514215,0.578074,0.628624,0.441353,0.454401,0.552862,0.645150,0.519669,0.444761,0.481036,0.531468,0.545039,0.005725,0.001863,0.001571,0.000913,0.000647,0.001233,0.004297,0.002590,0.002438,0.002835,0.003911,0.007006,0.173750,-0.161147,-0.270623,0.329442,0.235494,-0.067240,-0.357408,0.026303,0.380349,0.247042,0.096862,0.130007,0.233598,0.252660,0.294633,0.221680,0.234956,0.308906,0.301430,0.266528,0.255150,0.241893,0.262895,0.238040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.080846,0.140741,0.013940,0.008756,0.006266,4.201499,0.018014,6.078933,3364.258658,3030.258866,3184.348084,1141.642843,-2.686334,450.205223,8.899993,4696.954665,3108.093245,3032.803488,2598.413955,2.773888,316.901437,2.511117,2.073426,2.222147,0.190175,0.785742,4.736465,28.356246,34.485527,25.015210,26.531432,22.734371,24.213381,33.674361,51.951964,22.646908,10.591495,12.885256,14.793545,14.845164,15.375642,44.648909,22.270081,10.067213,12.315571,14.569383,14.203215,13.976111,45.203049,9.168008,5.356176,7.094698,9.758755,10.567502,10.246504,16.379717,0.425970,1.118419,1.181009,0.585100,1.021216,2.328581,-4.429613,2.951701,3.145892,3.000625,2.250641,2.640098,4.545462,3.680845,4.472041,8096.484375,7116.655918,7396.655273,3671.411133,-2.345250,904.277230,-1.166026,0.019189,-1.001678,-0.482878,-0.004382,-1.032505,0.084352,0.080295,0.099115,0.089346,0.050564,0.013336,0.021345,0.018927,0.027030,0.014905,0.019280,-0.016964,0.016073,0.020051,0.026564,0.010367,0.018180,-0.017366,-0.022558,-0.026391,-0.040326,-0.059574,-0.008304,-0.049212,0.333802,0.224949,0.077190,0.318629,0.398030,0.166977,0.031429,0.022830,0.036613,0.035726,0.012488,0.016694,13.474359,0.452637,0.156672,0.144531,0.067383,3.319025,0.048615,Alaudidae,Eremophila,Eremophila alpestris
1,11505,-0.323925,0.169799,0.076766,-0.229971,-0.523899,0.527224,0.894531,-0.467025,-0.851283,-0.609040,-0.376143,-0.472319,0.546641,0.680258,0.578395,0.508211,0.406083,0.425999,0.385660,0.251195,0.233190,0.197594,0.222686,0.162656,0.382399,0.509077,0.439266,0.377772,0.280272,0.225441,0.197550,0.148693,0.124281,0.079906,0.067047,0.045210,0.394284,0.502111,0.452572,0.381129,0.270731,0.226458,0.202524,0.149252,0.127951,0.076231,0.055344,0.032596,0.167077,0.377133,0.245203,0.227282,0.143083,0.065533,0.013256,0.034040,0.013192,0.000000,0.000000,0.000000,-0.579854,0.602621,-0.524115,-0.166453,0.210612,0.350378,-0.189426,-0.175020,-0.028824,0.395569,0.666110,0.772347,0.078314,0.056904,0.064635,0.057016,0.056067,0.060192,0.062402,0.049734,0.054560,0.049342,0.053768,0.042752,-0.920408,0.911299,-1.091828,-0.519702,0.553296,1.104181,2.170378,0.464939,1.048652,0.897144,1.705479,1.113198,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,0.880741,0.769337,0.726604,0.722186,0.684796,0.647589,0.900913,0.753529,0.616716,0.478209,0.412729,0.367261,0.316422,0.292125,0.252696,0.243139,0.207915,0.629350,1.000000,0.757856,0.589312,0.448758,0.389325,0.342481,0.305410,0.273233,0.237797,0.220510,0.190832,0.107039,0.354692,0.257621,0.170948,0.150308,7.936554e-02,1.121457e-01,8.485591e-02,0.061966,0.073888,0.046179,0.042545,0.121119,-1.353837,-0.336812,0.404968,0.876691,0.932446,1.214419,0.676409,0.958418,0.897479,1.158237,0.958121,0.221854,0.142721,0.212869,0.189788,0.173033,0.158535,0.146185,0.118631,0.119281,0.097203,0.108419,0.095175,-0.431419,-0.684166,-0.697556,-0.783455,-0.790031,-1.023123,-0.820094,-0.706977,-0.739378,-0.815111,-0.407252,-0.387995,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.489350,0.541830,0.589379,0.659482,0.693889,0.710289,0.625094,0.571883,0.558035,0.558535,0.497297,0.484923,0.463333,0.525471,0.579682,0.671432,0.696931,0.724854,0.609321,0.559508,0.549687,0.529659,0.470344,0.452246,0.020660,0.029981,0.028232,0.033953,0.076219,0.159971,0.064715,0.036917,0.029140,0.011958,0.010994,0.015967,0.372888,0.192957,0.026439,-0.213761,-0.272696,-0.314009,0.087191,0.190603,0.168161,0.190035,0.378147,0.433832,0.223192,0.232805,0.230275,0.231800,0.224040,0.234814,0.226191,0.228451,0.233731,0.249132,0.227562,0.224138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.165177,0.342020,0.122735,0.115418,0.030119,1.773209,0.038637,30.894400,2616.925819,1357.956770,1346.172055,1083.048905,4.477890,144.718098,34.669392,3842.125339,838.703025,777.388870,432.615255,5.251455,306.366809,4.414644,1.502278,0.860777,1.682441,3.978214,13.969600,67.780988,35.028009,25.819223,26.458276,25.154140,28.912055,28.826265,58.020053,12.645188,10.997946,12.797352,15.674533,16.185814,14.663381,45.833768,12.156681,10.629024,12.475901,15.453191,15.895798,14.413671,45.781735,4.281257,4.582011,6.333832,4.731386,4.137753,3.712500,17.639009,1.376516,0.881275,0.708647,0.382904,1.048611,2.167475,-4.000431,3.664006,3.104035,2.860614,2.210817,2.515034,2.073692,1.934286,27.732618,7256.689453,1267.590622,1098.193359,613.696289,4.638934,669.276398,0.144674,-0.220710,-0.430400,-0.853777,-0.209085,-0.604340,0.056484,0.113768,0.015296,0.147354,0.093847,0.089306,-0.038133,0.027771,-0.085217,0.029506,0.026249,0.020723,-0.038884,0.029398,-0.079392,0.027930,0.022549,0.017871,-0.151261,-0.076516,-0.191378,-0.081109,-0.020404,-0.024264,-0.062010,-0.215987,-0.318831,0.043972,0.417984,0.447087,0.036673,0.040370,0.045239,0.049793,0.022824,0.026179,20.381352,0.258789,0.036708,0.031738,0.007324,4.274347,0.028874,Alaudidae,Eremophila,Eremophila alpestris

In [3]:
df = df.drop(columns=[
    'track_index'
])

In [4]:
df = utils.elimina_nulos(df)

In [5]:
species = df['Especie']
df_taxonomy = df[['Especie', 'Genero', 'Familia']]
df = df.drop(columns=['Especie', 'Genero', 'Familia'])
df_taxonomy = df_taxonomy.drop_duplicates()
df_taxonomy.head()

                      Especie       Genero         Familia
0        Eremophila alpestris   Eremophila       Alaudidae
370       Bombycilla cedrorum   Bombycilla   Bombycillidae
381     Cinclus leucocephalus      Cinclus       Cinclidae
387        Conopophaga aurita  Conopophaga  Conopophagidae
444  Conopophaga castaneiceps  Conopophaga  Conopophagidae

In [6]:
# scaler = MinMaxScaler()
# df_normalized = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

# scaler = StandardScaler()
# df_standardized = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

In [7]:
# df_standardized.hist(bins=50, figsize=(40, 15))
# plt.show()

In [8]:
# plt.figure(figsize=(15, 10))
# sns.boxplot(data=df)
# plt.xticks(rotation=90)
# plt.show()

In [9]:
df['Specie'] = species

In [10]:
df_summary = df.groupby('Specie').mean()
df_summary = df_summary.dropna(axis=1)
df_summary.reset_index(inplace=True)
df_merged = df_summary.merge(df_taxonomy, left_on='Specie', right_on='Especie', how='left')

familia = taxonomia.capitalize_family_genus(taxonomia.genus_family)
df_merged['Family'] = df_merged['Genero'].map(familia)
df_merged['Suborder'] = df_merged['Family'].map(taxonomia.suborder)
df_merged = df_merged.rename(columns={'Genero': 'Genus'})

df_merged.head()

,Specie,chroma_cens_kurtosis_01,chroma_cens_kurtosis_02,chroma_cens_kurtosis_03,chroma_cens_kurtosis_04,chroma_cens_kurtosis_05,chroma_cens_kurtosis_06,chroma_cens_kurtosis_07,chroma_cens_kurtosis_08,chroma_cens_kurtosis_09,chroma_cens_max_01,chroma_cens_max_02,chroma_cens_max_03,chroma_cens_max_04,chroma_cens_max_05,chroma_cens_max_06,chroma_cens_max_07,chroma_cens_max_08,chroma_cens_max_09,chroma_cens_max_10,chroma_cens_max_11,chroma_cens_max_12,chroma_cens_mean_01,chroma_cens_mean_02,chroma_cens_mean_03,chroma_cens_mean_04,chroma_cens_mean_05,chroma_cens_mean_06,chroma_cens_mean_07,chroma_cens_mean_08,chroma_cens_mean_09,chroma_cens_mean_10,chroma_cens_mean_11,chroma_cens_mean_12,chroma_cens_median_01,chroma_cens_median_02,chroma_cens_median_03,chroma_cens_median_04,chroma_cens_median_05,chroma_cens_median_06,chroma_cens_median_07,chroma_cens_median_08,chroma_cens_median_09,chroma_cens_median_10,chroma_cens_median_11,chroma_cens_median_12,chroma_cens_min_01,chroma_cens_min_02,chroma_cens_min_03,chroma_cens_min_04,chroma_cens_min_05,chroma_cens_min_06,chroma_cens_min_07,chroma_cens_min_08,chroma_cens_min_09,chroma_cens_min_10,chroma_cens_min_11,chroma_cens_min_12,chroma_cens_skew_01,chroma_cens_skew_02,chroma_cens_skew_03,chroma_cens_skew_04,chroma_cens_skew_05,chroma_cens_skew_06,chroma_cens_skew_07,chroma_cens_skew_08,chroma_cens_skew_09,chroma_cens_std_01,chroma_cens_std_02,chroma_cens_std_03,chroma_cens_std_04,chroma_cens_std_05,chroma_cens_std_06,chroma_cens_std_07,chroma_cens_std_08,chroma_cens_std_09,chroma_cens_std_10,chroma_cens_std_11,chroma_cens_std_12,chroma_cqt_kurtosis_01,chroma_cqt_kurtosis_02,chroma_cqt_kurtosis_03,chroma_cqt_kurtosis_04,chroma_cqt_kurtosis_05,chroma_cqt_kurtosis_06,chroma_cqt_kurtosis_07,chroma_cqt_kurtosis_08,chroma_cqt_kurtosis_09,chroma_cqt_kurtosis_10,chroma_cqt_kurtosis_11,chroma_cqt_kurtosis_12,chroma_cqt_max_01,chroma_cqt_max_02,chroma_cqt_max_03,chroma_cqt_max_04,chroma_cqt_max_05,chroma_cqt_max_06,chroma_cqt_max_07,chroma_cqt_max_08,chroma_cqt_max_09,chroma_cqt_max_10,chroma_cqt_max_11,chroma_cqt_max_12,chroma_cqt_mean_01,chroma_cqt_mean_02,chroma_cqt_mean_03,chroma_cqt_mean_04,chroma_cqt_mean_05,chroma_cqt_mean_06,chroma_cqt_mean_07,chroma_cqt_mean_08,chroma_cqt_mean_09,chroma_cqt_mean_10,chroma_cqt_mean_11,chroma_cqt_mean_12,chroma_cqt_median_01,chroma_cqt_median_02,chroma_cqt_median_03,chroma_cqt_median_04,chroma_cqt_median_05,chroma_cqt_median_06,chroma_cqt_median_07,chroma_cqt_median_08,chroma_cqt_median_09,chroma_cqt_median_10,chroma_cqt_median_11,chroma_cqt_median_12,chroma_cqt_min_01,chroma_cqt_min_02,chroma_cqt_min_03,chroma_cqt_min_04,chroma_cqt_min_05,chroma_cqt_min_06,chroma_cqt_min_07,chroma_cqt_min_08,chroma_cqt_min_09,chroma_cqt_min_10,chroma_cqt_min_11,chroma_cqt_min_12,chroma_cqt_skew_01,chroma_cqt_skew_02,chroma_cqt_skew_03,chroma_cqt_skew_04,chroma_cqt_skew_05,chroma_cqt_skew_06,chroma_cqt_skew_07,chroma_cqt_skew_08,chroma_cqt_skew_09,chroma_cqt_skew_10,chroma_cqt_skew_11,chroma_cqt_skew_12,chroma_cqt_std_01,chroma_cqt_std_02,chroma_cqt_std_03,chroma_cqt_std_04,chroma_cqt_std_05,chroma_cqt_std_06,chroma_cqt_std_07,chroma_cqt_std_08,chroma_cqt_std_09,chroma_cqt_std_10,chroma_cqt_std_11,chroma_cqt_std_12,chroma_stft_kurtosis_01,chroma_stft_kurtosis_02,chroma_stft_kurtosis_03,chroma_stft_kurtosis_04,chroma_stft_kurtosis_05,chroma_stft_kurtosis_06,chroma_stft_kurtosis_07,chroma_stft_kurtosis_08,chroma_stft_kurtosis_09,chroma_stft_kurtosis_10,chroma_stft_kurtosis_11,chroma_stft_kurtosis_12,chroma_stft_max_01,chroma_stft_max_02,chroma_stft_max_03,chroma_stft_max_04,chroma_stft_max_05,chroma_stft_max_06,chroma_stft_max_07,chroma_stft_max_08,chroma_stft_max_09,chroma_stft_max_10,chroma_stft_max_11,chroma_stft_max_12,chroma_stft_mean_01,chroma_stft_mean_02,chroma_stft_mean_03,chroma_stft_mean_04,chroma_stft_mean_05,chroma_stft_mean_06,chroma_stft_mean_07,chroma_stft_mean_08,chroma_stft_mean_09,chroma_stft_mean_10,chroma_stft_mean_11,chroma_stft_mean_12,chroma_stft_median_01,chroma_stft_median_02,chroma_stft_median_03,chroma_stft_median_04,chroma_stft_median_05,chroma_stft_median_06,chroma_stft_median_07,chroma_stft_median_08,chroma_stft_median_09,chroma_stft_median_10,chroma_stft_median_11,chroma_stft_median_12,chroma_stft_min_01,chroma_stft_min_02,chroma_stft_min_03,chroma_stft_min_04,chroma_stft_min_05,chroma_stft_min_06,chroma_stft_min_07,chroma_stft_min_08,chroma_stft_min_09,chroma_stft_min_10,chroma_stft_min_11,chroma_stft_min_12,chroma_stft_skew_01,chroma_stft_skew_02,chroma_stft_skew_03,chroma_stft_skew_04,chroma_stft_skew_05,chroma_stft_skew_06,chroma_stft_skew_07,chroma_stft_skew_08,chroma_stft_skew_09,chroma_stft_skew_10,chroma_stft_skew_11,chroma_stft_skew_12,chroma_stft_std_01,chroma_stft_std_02,chroma_stft_std_03,chroma_stft_std_04,chroma_stft_std_05,chroma_stft_std_06,chroma_stft_std_07,chroma_stft_std_08,chroma_stft_std_09,chroma_stft_std_10,chroma_stft_std_11,chroma_stft_std_12,rmse_kurtosis_01,rmse_max_01,rmse_mean_01,rmse_median_01,rmse_min_01,rmse_skew_01,rmse_std_01,spectral_bandwidth_kurtosis_01,spectral_bandwidth_max_01,spectral_bandwidth_mean_01,spectral_bandwidth_median_01,spectral_bandwidth_min_01,spectral_bandwidth_skew_01,spectral_bandwidth_std_01,spectral_centroid_kurtosis_01,spectral_centroid_max_01,spectral_centroid_mean_01,spectral_centroid_median_01,spectral_centroid_min_01,spectral_centroid_skew_01,spectral_centroid_std_01,spectral_contrast_kurtosis_01,spectral_contrast_kurtosis_02,spectral_contrast_kurtosis_03,spectral_contrast_kurtosis_04,spectral_contrast_kurtosis_05,spectral_contrast_kurtosis_06,spectral_contrast_kurtosis_07,spectral_contrast_max_01,spectral_contrast_max_02,spectral_contrast_max_03,spectral_contrast_max_04,spectral_contrast_max_05,spectral_contrast_max_06,spectral_contrast_max_07,spectral_contrast_mean_01,spectral_contrast_mean_02,spectral_contrast_mean_03,spectral_contrast_mean_04,spectral_contrast_mean_05,spectral_contrast_mean_06,spectral_contrast_mean_07,spectral_contrast_median_01,spectral_contrast_median_02,spectral_contrast_median_03,spectral_contrast_median_04,spectral_contrast_median_05,spectral_contrast_median_06,spectral_contrast_median_07,spectral_contrast_min_01,spectral_contrast_min_02,spectral_contrast_min_03,spectral_contrast_min_04,spectral_contrast_min_05,spectral_contrast_min_06,spectral_contrast_min_07,spectral_contrast_skew_01,spectral_contrast_skew_02,spectral_contrast_skew_03,spectral_contrast_skew_04,spectral_contrast_skew_05,spectral_contrast_skew_06,spectral_contrast_skew_07,spectral_contrast_std_01,spectral_contrast_std_02,spectral_contrast_std_03,spectral_contrast_std_04,spectral_contrast_std_05,spectral_contrast_std_06,spectral_contrast_std_07,spectral_rolloff_kurtosis_01,spectral_rolloff_max_01,spectral_rolloff_mean_01,spectral_rolloff_median_01,spectral_rolloff_min_01,spectral_rolloff_skew_01,spectral_rolloff_std_01,tonnetz_kurtosis_01,tonnetz_kurtosis_02,tonnetz_kurtosis_03,tonnetz_kurtosis_04,tonnetz_kurtosis_05,tonnetz_kurtosis_06,tonnetz_max_01,tonnetz_max_02,tonnetz_max_03,tonnetz_max_04,tonnetz_max_05,tonnetz_max_06,tonnetz_mean_01,tonnetz_mean_02,tonnetz_mean_03,tonnetz_mean_04,tonnetz_mean_05,tonnetz_mean_06,tonnetz_median_01,tonnetz_median_02,tonnetz_median_03,tonnetz_median_04,tonnetz_median_05,tonnetz_median_06,tonnetz_min_01,tonnetz_min_02,tonnetz_min_03,tonnetz_min_04,tonnetz_min_05,tonnetz_min_06,tonnetz_skew_01,tonnetz_skew_02,tonnetz_skew_03,tonnetz_skew_04,tonnetz_skew_05,tonnetz_skew_06,tonnetz_std_01,tonnetz_std_02,tonnetz_std_03,tonnetz_std_04,tonnetz_std_05,tonnetz_std_06,zcr_kurtosis_01,zcr_max_01,zcr_mean_01,zcr_median_01,zcr_min_01,zcr_skew_01,zcr_std_01,Especie,Genus,Familia,Family,Suborder
0,Acropternis orthonyx,1.603518,1.925427,2.011351,0.967991,1.769442,6.020500,1.944098,1.404928,3.698810,0.648805,0.780883,0.663126,0.551339,0.438560,0.390456,0.376038,0.373370,0.352749,0.339950,0.364228,0.418704,0.338702,0.404409,0.351636,0.315497,0.243388,0.198391,0.188936,0.188013,0.176551,0.169365,0.170697,0.168289,0.328153,0.380087,0.344916,0.327288,0.252506,0.206249,0.196451,0.196866,0.187467,0.178362,0.175373,0.164956,0.083835,0.173647,0.129345,0.075219,0.044780,0.024831,0.022325,0.019447,0.017361,0.015256,0.015582,0.019101,0.420326,0.955441,0.575455,-0.428226,-0.253594,0.238607,-0.032508,-0.194875,0.037015,0.102948,0.119388,0.092918,0.094395,0.079941,0.075387,0.073980,0.074196,0.071627,0.067958,0.068746,0.072609,-0.127986,-0.174581,-0.320366,0.134061,0.557038,9.561194,1.244445,1.216906,2.080721,3.010873,3.911508,7.589515,1.000000,1.000000,1.000000,1.000000,0.988177,0.974825,0.973479,0.969653,0.959721,0.958865,0.957339,0.967141,0.593462,0.685302,0.608670,0.571157,0.473234,0.411455,0.405398,0.402839,0.387733,0.377524,0.376582,0.366464,0.595980,0.710394,0.612206,0.582532,0.472161,0.403425,0.397698,0.395814,0.380588,0.371523,0.369764,0.352547,0.042418,0.082851,0.055358,0.043476,0.030027,0.021366,0.019394,0.019045,0.016319,0.012623,0.012159,0.010516,-0.074725,-0.352499,-0.104324,-0.160118,0.257731,0.818765,0.521135,0.514834,0.618255,0.703814,0.795311,1.105257,0.248421,0.229444,0.241303,0.248238,0.225594,0.212020,0.211844,0.212249,0.207786,0.203232,0.200084,0.194900,-0.327763,-0.266753,-0.208838,-0.254180,-0.279266,-0.142063,-0.220925,-0.240138,-0.305794,-0.292087,-0.296712,-0.322684,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.0,1.000000,1.000000,0.999564,1.000000,0.551573,0.568291,0.575864,0.575939,0.560440,0.544911,0.532438,0.526178,0.524313,0.523301,0.530077,0.535481,0.569082,0.586704,0.593233,0.592804,0.579222,0.565798,0.555886,0.552318,0.551168,0.550540,0.554477,0.555628,0.002370,0.002981,0.003635,0.004705,0.006005,0.007553,0.003303,0.002264,0.002244,0.002173,0.002458,0.002236,-0.306619,-0.366943,-0.359759,-0.326918,-0.240444,-0.200369,-0.229303,-0.247377,-0.253035,-0.246420,-0.259967,-0.266731,0.284176,0.279759,0.277090,0.278159,0.277943,0.281332,0.286176,0.288301,0.289189,0.287604,0.287746,0.285104,21.206514,0.169865,0.016259,0.007747,0.000703,3.421341,0.024139,4.498373,2739.125285,1912.606677,2011.830588,732.749601,-0.961022,339.220150,9.368897,3981.812602,2082.396365,2152.413059,781.347818,0.267983,393.649537,3.223497,1.837617,2.501897,2.467604,4.364802,9.224306,33.265949,44.185087,29.522869,33.588457,40.984320,36.880541,40.536237,58.859286,17.664915,11.573544,13.338335,16.926445,17.179973,19.499898,46.825973,17.161440,11.135938,12.765718,14.964332,16.283613,18.683444,46.836064,4.518139,3.234193,5.089973,7.123881,9.087660,11.103492,19.541612,0.960721,0.919170,1.152092,1.582018,1.429856,1.733963,-2.209788,4.187261,3.190469,3.474067,6.067085,3.864753,3.809943,4.088830,6.983445,7064.126137,4070.195215,4356.061091,1037.918041,-0.453965,1030.776910,1.814988,2.293358,3.244810,2.859091,2.581952,3.206044,0.131516,0.143572,0.190315,0.252963,0.130400,0.092098,-0.020107,0.013162,-0.045296,0.017643,0.018907,0.009841,-0.020003,0.017179,-0.029288,0.020438,0.015945,0.013578,-0.163621,-0.175096,-0.393273,-0.280307,-0.067367,-0.121605,0.017224,-0.760118,-0.962036,-0.408277,0.668462,-0.942232,0.044161,0.049789,0.098617,0.081598,0.030285,0.033438,7.725479,0.300913,0.129693,0.130889,0.028536,0.861032,0.038596,Acropternis orthonyx,Acropternis,Rhinocryptidae,Rhinocryptidae,tiranni
1,Agriornis albicauda,0.804493,0.168919,0.605155,0.190439,1.532476,13.875214,13.460870,13.506733,11.323860,0.382395,0.396291,0.492402,0.555568,0.473350,0.467718,0.462359,0.447381,0.417548,0.450097,0.410615,0.383529,0.199660,0.208801,0.249293,0.302314,0.271000,0.294196,0.289155,0.273026,0.239715,0.245271,0.214657,0.193684,0.195969,0.206247,0.243059,0.296277,0.269923,0.293999,0.291495,0.274026,0.240998,0.242872,0.211752,0.188582,0.075577,0.074686,0.062989,0.113964,0.114698,0.138142,0.133233,0.091208,0.062681,0.070685,0.083790,0.076116,0.426040,0.219176,0.347209,0.354333,0.473785,1.000555,0.857300,0.743654,0.661147,0.064115,0.066508,0.082780,0.088093,0.069349,0.064149,0.065068,0.070767,0.073078,0.077454,0.066041,0.059370,1.245927,0.916266,0.563662,-0.105659,2.233215,43.633775,42.665208,41.618519,14.801731,0.099968,0.594740,1.128011,0.982309,0.981213,1.000000,1.000000,0.991958,1.000000,0.999245,0.996047,0.996074,0.992193,0.986417,0.983695,0.397793,0.401380,0.442612,0.532599,0.516650,0.556760,0.530555,0.498660,0.454115,0.464061,0.420345,0.389092,0.376357,0.378410,0.409832,0.505913,0.506743,0.573703,0.526269,0.483558,0.436820,0.448435,0.398893,0.363851,0.023271,0.039006,0.062892,0.074882,0.077334,0.072474,0.071364,0.055089,0.041662,0.027969,0.020022,0.016175,0.741928,0.734820,0.769308,0.471882,0.509074,1.536670,1.698690,1.814011,1.152791,0.461577,0.615793,0.761009,0.194617,0.187400,0.200993,0.221854,0.196953,0.192550,0.212186,0.224503,0.223162,0.229734,0.211788,0.198862,-0.638194,-0.634534,-0.576652,-0.561900,-0.579565,-0.636531,-0.531246,-0.397775,-0.328865,-0.400317,-0.366133,-0.591210,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,0.631094,0.622189,0.623228,0.630693,0.616850,0.618087,0.605197,0.601600,0.607314,0.611494,0.607706,0.617461,0.633943,0.625263,0.622952,0.633452,0.619857,0.621012,0.603581,0.595570,0.602919,0.605973,0.608872,0.619527,0.067891,0.069882,0.053775,0.033598,0.024329,0.016821,0.015148,0.017232,0.017272,0.022006,0.026303,0.050354,-0.194672,-0.172195,-0.171821,-0.213275,-0.168555,-0.151790,-0.133398,-0.102458,-0.159904,-0.152710,-0.174694,-0.163685,0.235603,0.230301,0.230307,0.235606,0.236307,0.239702,0.232671,0.228146,0.230072,0.237305,0.228787,0.230536,73.513612,0.122222,0.008046,0.004098,0.000004,6.317742,0.012449,18.158411,3409.203690,2635.562379,2719.863265,1080.368163,-2.152231,348.409884,15.328794,5565.517978,2792.466823,2875.270426,950.305778,-0.043779,522.960841,2.309478,1.555568,1.780253,3.342500,3.306959,3.359097,38.581149,40.380387,27.655050,32.018289,29.710116,32.535736,29.908888,59.168933,16.970928,11.306005,15.330691,13.886947,16.345013,16.373689,48.670779,16.500629,10.918910,14.957480,13.324374,15.824119,15.830578,48.502896,4.943003,3.530076,6.166614,7.380912,9.654240,10.859163,24.254101,0.905612,0.838719,0.811621,1.299609,1.196855,1.017638,-2.807546,4.172350,3.080724,3.388524,2.972576,3.021143,2.873906,3.820430,30.637348,8986.882324,6068.470604,6376.788940,1029.825439,-1.852469,1190.521544,0.345676,0.010235,0.428136,0.057224,0.412507,0.123136,0.097298,0.111064,0.165017,0.120446,0.057211,0.073036,-0.005962,0.010038,0.007690,-0.015463,-0.001230,0.011142,-0.006443,0.009986,0.005496,-0.014450,-0.001017,0.010530,-0.121154,-0.085092,-0.148556,-0.155134,-0.058158,-0.046385,-0.062841,0.113916,0.146231,-0.132414,-0.021151,0.120885,0.038733,0.035674,0.053486,0.050545,0.020225,0.020879,6.001015,0.411328,0.170299,0.171143,0.047827,0.326213,0.047808,Agriornis albicauda,Agriornis,Tyrannidae,Tyrannidae,tiranni
2,Agriornis montanus,3.125996,5.936433,5.653313,4.073615,3.578971,51.884843,65.725211,49.828854,27.685244,0.521195,0.678582,0.727320,0.633158,0.460323,0.361240,0.347295,0.386154,0.377731,0.395316,0.398348,0.378965,0.315218,0.374738,0.379823,0.345285,0.231782,0.181806,0.169643,0.182120,0.190892,0.196761,0.182865,0.181867,0.321315,0.369866,0.374356,0.341989,0.231913,0.180728,0.165404,0.179456,0.187940,0.190886,0.173132,0.174899,0.063341,0.142723,0.190923,0.131973,0.047350,0.025442,0.030800,0.034759,0.030733,0.033673,0.027545,0.024873,-0.861777,0.692680,1.381762,0.624892,0.496255,2.657056,3.078573,2.214160,1.423739,0.072518,0.077491,0.081220,0.076726,0.069860,0.059320,0.060013,0.061578,0.063489,0.067283,0.070374,0.066194,-0.176446,0.060023,-0.450603,-0.143525,1.750472,86.618968,49.173444,28.057488,2.608688,4.038384,1.711707,1.383024,1.000000,1.000000,1.000000,1.000000,0.990637,0.868872,0.886734,0.925455,0.906074,0.918760,0.949376,0.952902,0.577211,0.673093,0.668647,0.616121,0.463695,0.391427,0.379704,0.401362,0.417470,0.432008,0.410179,0.395656,0.565878,0.690751,0.664095,0.605418,0.447608,0.376616,0.356146,0.382121,0.400715,0.417118,0.384899,0.371004,0.046680,0.065757,0.083888,0.066037,0.037391,0.027319,0.027977,0.030116,0.025072,0.022237,0.013697,0.010850,0.058870,-0.305270,-0.115656,-0.004681,0.567775,2.576055,2.020306,1.535162,0.634371,0.600979,0.687870,0.713484,0.228468,0.221255,0.219195,0.221042,0.190387,0.163230,0.171182,0.177382,0.183156,0.192085,0.196605,0.191105,0.063084,0.327666,0.389618,0.287270,0.217495,0.152889,0.095055,0.021449,0.039707,0.101014,0.572640,0.088612,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,0.584711,0.607950,0.622658,0.621513,0.615007,0.606343,0.577130,0.559657,0.546059,0.564442,0.579413,0.571598,0.600094,0.628592,0.646400,0.638524,0.630072,0.619790,0.585617,0.558357,0.547642,0.575303,0.594432,0.583937,0.006699,0.006806,0.006881,0.009152,0.007913,0.009382,0.018115,0.019581,0.012549,0.007715,0.006796,0.008904,-0.359198,-0.473622,-0.510677,-0.442109,-0.409964,-0.340962,-0.203122,-0.076293,-0.090294,-0.218512,-0.390154,-0.301036,0.244517,0.248052,0.248848,0.246923,0.247389,0.249387,0.238923,0.236785,0.233597,0.237642,0.235364,0.238010,29.962962,0.142151,0.013833,0.010715,0.000011,4.460449,0.014777,9.034526,3031.693013,2146.431116,2183.458642,1078.233728,-1.487127,260.124860,13.843939,4892.038378,2608.207774,2631.768003,1206.373115,-0.128593,386.391457,2.662026,1.641497,2.005033,6.638856,8.056241,16.961908,24.132623,46.445672,30.115108,33.162031,35.629514,36.299607,34.384606,56.433937,17.696551,11.751427,13.601328,15.008123,15.989871,17.677089,44.232773,17.217633,11.333386,13.122583,14.349180,15.371903,17.421770,43.923733,4.745221,3.672285,5.751418,7.366669,9.418324,10.863069,19.230405,0.956580,0.909960,1.015220,2.046896,1.978148,1.946549,-2.094662,4.400970,3.191494,3.198759,3.553807,3.130744,2.197396,4.528575,16.415726,8058.801270,4929.853222,5025.580444,1913.225098,-0.888490,834.169116,2.355971,3.346072,5.180594,6.723998,4.960326,4.042659,0.129194,0.153589,0.207554,0.157319,0.090240,0.085033,-0.014982,0.017672,-0.016252,0.001900,0.005664,0.013653,-0.015386,0.018132,-0.017308,0.009919,0.005830,0.014584,-0.142595,-0.131752,-0.249246,-0.313241,-0.097536,-0.083046,0.179733,-0.200677,-0.092075,-1.598274,-0.482867,-0.633069,0.037817,0.040723,0.058614,0.065015,0.023678,0.022690,12.757831,0.366260,0.177263,0.179968,0.040991,0.285132,0.039378,Agriornis montanus,Agriornis,Tyrannidae,Tyrannidae,tiranni

In [11]:
df_merged[['Suborder', 'Family', 'Genus']].isnull().sum().sort_values(ascending=False)

Suborder    0
Family      0
Genus       0
dtype: int64

In [12]:
df_merged['Specie'] = df_merged['Specie'].str.replace(" ", "_")

In [13]:
#guarda el csv
df_merged.to_csv('./data/data_summary.csv', index=False)

In [14]:
df_merged.Specie.value_counts().sort_values(ascending=False)

Specie
Acropternis_orthonyx          1
Anabacerthia_variegaticeps    1
Arremon_atricapillus          1
Agriornis_montanus            1
Alopochelidon_fucata          1
                             ..
Zimmerius_cinereicapilla      1
Zimmerius_gracilipes          1
Zimmerius_improbus            1
Zimmerius_vilissimus          1
Zonotrichia_leucophrys        1
Name: count, Length: 992, dtype: int64