In [1]:
# manejo de datos
import numpy as np
import pandas as pd
import os

import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
import os
import pandas as pd

def encontrar_especies_con_pocos_archivos(ruta_base):
    columnas = ['Family', 'Genus', 'Species', 'Comun Name', 'Number of Recordings']  # Incluir el nombre de la columna corregido
    datos = []  # Lista para acumular los datos
    
    try:
        familias = os.listdir(ruta_base)
    except Exception as e:
        print(f"Error al listar {ruta_base}: {e}")
        return pd.DataFrame(datos, columns=columnas)
    
    for familia in familias:
        ruta_familia = os.path.join(ruta_base, familia)
        if not os.path.isdir(ruta_familia):
            continue  # Si no es un directorio, omite
        
        try:
            generos = os.listdir(ruta_familia)
        except Exception as e:
            print(f"Error al listar {ruta_familia}: {e}")
            continue
        
        for genero in generos:
            ruta_genero = os.path.join(ruta_familia, genero)
            if not os.path.isdir(ruta_genero):
                continue  # Si no es un directorio, omite
            
            try:
                especies = os.listdir(ruta_genero)
            except Exception as e:
                print(f"Error al listar {ruta_genero}: {e}")
                continue
            
            for especie in especies:
                ruta_especie = os.path.join(ruta_genero, especie)
                if not os.path.isdir(ruta_especie):
                    continue  # Si no es un directorio, omite
                
                try:
                    nombres_comunes = os.listdir(ruta_especie)
                except Exception as e:
                    print(f"Error al listar {ruta_especie}: {e}")
                    continue
                
                for nombre_comun in nombres_comunes:
                    ruta_nombre_comun = os.path.join(ruta_especie, nombre_comun)
                    if not os.path.isdir(ruta_nombre_comun):
                        continue  # Si no es un directorio, omite
                    
                    try:
                        archivos = os.listdir(ruta_nombre_comun)
                        # Filtrar `.DS_Store` o cualquier otro archivo no deseado
                        archivos = [archivo for archivo in archivos if not archivo.startswith('.')]
                    except Exception as e:
                        print(f"Error al listar {ruta_nombre_comun}: {e}")
                        continue
                    
                    if len(archivos) > 0:
                        # Incluir el nombre común y el conteo de archivos en los datos
                        datos.append([familia, genero, especie, nombre_comun, len(archivos)])
    
    especies_pocas_grabaciones = pd.DataFrame(datos, columns=columnas)
    return especies_pocas_grabaciones

# Uso de la función
ruta_base = './songs'
df = encontrar_especies_con_pocos_archivos(ruta_base)

In [3]:
print(df.shape)
df = df.sort_values(by='Number of Recordings', ascending=False)
df.head(10)

(999, 5)

,Family,Genus,Species,Comun Name,Number of Recordings
569,Passeridae,Passer,Passer domesticus,HouseSparrow,824
697,Troglodytidae,Troglodytes,Troglodytes aedon,HouseWren,774
693,Troglodytidae,Henicorhina,Henicorhina leucophrys,Grey-breastedWoodWren,425
961,Passerellidae,Zonotrichia,Zonotrichia capensis,Rufous-collaredSparrow,418
377,Hirundinidae,Hirundo,Hirundo rustica,BarnSwallow,411
264,Tyrannidae,Myiarchus,Myiarchus tyrannulus,Brown-crestedFlycatcher,324
337,Tyrannidae,Pitangus,Pitangus sulphuratus,GreatKiskadee,316
694,Troglodytidae,Henicorhina,Henicorhina leucosticta,White-breastedWoodWren,290
562,Vireonidae,Cyclarhis,Cyclarhis gujanensis,Rufous-browedPeppershrike,270
315,Tyrannidae,Tolmomyias,Tolmomyias sulphurescens,Yellow-oliveFlatbill,258

In [4]:
df[df['Family'] == 'Psittacidae'].sort_values(by='Number of Recordings', ascending=False).head(10)

,Family,Genus,Species,Comun Name,Number of Recordings
400,Psittacidae,Pionus,Pionus menstruus,Blue-headedParrot,89
399,Psittacidae,Ara,Ara ararauna,Blue-and-yellowMacaw,83
401,Psittacidae,Brotogeris,Brotogeris jugularis,Orange-chinnedParakeet,69
402,Psittacidae,Forpus,Forpus conspicillatus,SpectacledParrotlet,21
397,Psittacidae,Bolborhynchus,Bolborhynchus lineola,BarredParakeet,14
398,Psittacidae,Touit,Touit dilectissimus,Blue-frontedParrotlet,8

In [5]:
df[df['Family'] == 'Troglodytidae'].sort_values(by='Number of Recordings', ascending=False)

,Family,Genus,Species,Comun Name,Number of Recordings
697,Troglodytidae,Troglodytes,Troglodytes aedon,HouseWren,774
693,Troglodytidae,Henicorhina,Henicorhina leucophrys,Grey-breastedWoodWren,425
694,Troglodytidae,Henicorhina,Henicorhina leucosticta,White-breastedWoodWren,290
683,Troglodytidae,Cantorchilus,Cantorchilus nigricapillus,BayWren,184
680,Troglodytidae,Cantorchilus,Cantorchilus leucotis,Buff-breastedWren,179
670,Troglodytidae,Pheugopedius,Pheugopedius euophrys,Plain-tailedWren,162
675,Troglodytidae,Pheugopedius,Pheugopedius coraya,CorayaWren,148
685,Troglodytidae,Microcerculus,Microcerculus marginatus,SouthernNightingale-Wren,143
664,Troglodytidae,Cistothorus,Cistothorus platensis,GrassWren,132
674,Troglodytidae,Pheugopedius,Pheugopedius genibarbis,MoustachedWren,129
677,Troglodytidae,Cyphorhinus,Cyphorhinus thoracicus,Chestnut-breastedWren,99
671,Troglodytidae,Pheugopedius,Pheugopedius mystacalis,WhiskeredWren,94
689,Troglodytidae,Campylorhynchus,Campylorhynchus turdinus,Thrush-likeWren,89
672,Troglodytidae,Pheugopedius,Pheugopedius sclateri,Speckle-breastedWren,84
667,Troglodytidae,Cinnycerthia,Cinnycerthia olivascens,Sepia-brownWren,81
679,Troglodytidae,Cyphorhinus,Cyphorhinus arada,MusicianWren,76
673,Troglodytidae,Pheugopedius,Pheugopedius fasciatoventris,Black-belliedWren,69
668,Troglodytidae,Pheugopedius,Pheugopedius rutilus,Rufous-breastedWren,68
665,Troglodytidae,Cistothorus,Cistothorus apolinari,Apolinar'sWren,67
698,Troglodytidae,Troglodytes,Troglodytes solstitialis,MountainWren,66
690,Troglodytidae,Campylorhynchus,Campylorhynchus zonatus,Band-backedWren,62
700,Troglodytidae,Thryophilus,Thryophilus rufalbus,Rufous-and-whiteWren,62
678,Troglodytidae,Cyphorhinus,Cyphorhinus phaeocephalus,SongWren,58
682,Troglodytidae,Cantorchilus,Cantorchilus leucopogon,Stripe-throatedWren,39
686,Troglodytidae,Campylorhynchus,Campylorhynchus griseus,BicoloredWren,37
684,Troglodytidae,Microcerculus,Microcerculus bambla,Wing-bandedWren,36
669,Troglodytidae,Pheugopedius,Pheugopedius spadix,Sooty-headedWren,34
666,Troglodytidae,Cinnycerthia,Cinnycerthia unirufa,RufousWren,31
691,Troglodytidae,Henicorhina,Henicorhina negreti,MunchiqueWoodWren,26
692,Troglodytidae,Henicorhina,Henicorhina anachoreta,HermitWoodWren,23
676,Troglodytidae,Odontorchilus,Odontorchilus branickii,Grey-mantledWren,18
701,Troglodytidae,Thryophilus,Thryophilus nicefori,Niceforo'sWren,16
688,Troglodytidae,Campylorhynchus,Campylorhynchus nuchalis,Stripe-backedWren,13
687,Troglodytidae,Campylorhynchus,Campylorhynchus albobrunneus,White-headedWren,11
696,Troglodytidae,Troglodytes,Troglodytes ochraceus,OchraceousWren,9
681,Troglodytidae,Cantorchilus,Cantorchilus griseus,GreyWren,8
695,Troglodytidae,Troglodytes,Troglodytes monticola,SantaMartaWren,7
699,Troglodytidae,Thryophilus,Thryophilus sernai,AntioquiaWren,4

In [6]:
df[df['Number of Recordings']<=4]['Species'].unique().tolist()

['Myiotheretes pernix',
 'Myiobius atricaudus',
 'Tachycineta cyaneoviridis',
 'Thryophilus sernai',
 'Myrmotherula sunensis',
 'Chrysothlypis chrysomelas',
 'Atlapetes semirufus',
 'Sicalis columbiana',
 'Cnemarchus erythropygius',
 'Arremon crassirostris',
 'Sirystes albogriseus',
 'Drymotoxeres pucheranii',
 'Sporophila murallae',
 'Myadestes coloratus',
 'Thraupis glaucocolpa',
 'Conirostrum rufum',
 'Cranioleuca vulpecula',
 'Eubucco richardsoni',
 'Spinus spinescens',
 'Vireo approximans',
 'Myrmotherula behni',
 'Contopus nigrescens',
 'Psarocolius cassini',
 'Pittasoma michleri',
 'Margarornis stellatus',
 'Muscisaxicola alpinus',
 'Elaenia pelzelni',
 'Ixothraupis guttata',
 'Arremonops tocuyensis',
 'Siptornis striaticollis',
 'Spinus yarrellii',
 'Chloropipo flavicapilla',
 'Lonchura atricapilla',
 'Cyanerpes nitidus',
 'Cryptopipo holochlora',
 'Muscisaxicola albilora',
 'Cotinga cayana',
 'Dacnis albiventris',
 'Zimmerius improbus',
 'Doliornis remseni',
 'Cyanerpes lucidus',
 'Icterus auricapillus',
 'Phylloscartes flavovirens',
 'Elaenia strepera',
 'Myrmotherula ambigua',
 'Tangara inornata',
 'Furnarius torridus',
 'Knipolegus poecilocercus',
 'Scytalopus panamensis',
 'Rhynchocyclus fulvipectus',
 'Frederickena unduliger',
 'Xiphorhynchus ocellatus',
 'Thlypopsis ornata',
 'Thlypopsis fulviceps',
 'Lonchura malacca',
 'Myiarchus panamensis',
 'Porphyrolaema porphyrolaema',
 'Paroaria nigrogenis',
 'Sporophila americana',
 'Haematoderus militaris',
 'Snowornis cryptolophus',
 'Saltator cinctus',
 'Pseudocolopteryx acutipennis',
 'Lipaugus fuscocinereus',
 'Psarocolius guatimozinus',
 'Cephalopterus ornatus']

In [7]:
df['Number of Recordings'].sum()

42067

In [8]:
#df.to_csv('/Users/camcortes/Documents/birds-sounds/data/Species_Passeriformes_Summary.csv', index=False)