In [10]:
# manejo de datos
import numpy as np
import pandas as pd
import os

import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [11]:
import os
import pandas as pd

def encontrar_especies_con_pocos_archivos(ruta_base):
    columnas = ['Family', 'Genus', 'Species', 'Comun Name', 'Number of Recordings']  # Incluir el nombre de la columna corregido
    datos = []  # Lista para acumular los datos
    
    try:
        familias = os.listdir(ruta_base)
    except Exception as e:
        print(f"Error al listar {ruta_base}: {e}")
        return pd.DataFrame(datos, columns=columnas)
    
    for familia in familias:
        ruta_familia = os.path.join(ruta_base, familia)
        if not os.path.isdir(ruta_familia):
            continue  # Si no es un directorio, omite
        
        try:
            generos = os.listdir(ruta_familia)
        except Exception as e:
            print(f"Error al listar {ruta_familia}: {e}")
            continue
        
        for genero in generos:
            ruta_genero = os.path.join(ruta_familia, genero)
            if not os.path.isdir(ruta_genero):
                continue  # Si no es un directorio, omite
            
            try:
                especies = os.listdir(ruta_genero)
            except Exception as e:
                print(f"Error al listar {ruta_genero}: {e}")
                continue
            
            for especie in especies:
                ruta_especie = os.path.join(ruta_genero, especie)
                if not os.path.isdir(ruta_especie):
                    continue  # Si no es un directorio, omite
                
                try:
                    nombres_comunes = os.listdir(ruta_especie)
                except Exception as e:
                    print(f"Error al listar {ruta_especie}: {e}")
                    continue
                
                for nombre_comun in nombres_comunes:
                    ruta_nombre_comun = os.path.join(ruta_especie, nombre_comun)
                    if not os.path.isdir(ruta_nombre_comun):
                        continue  # Si no es un directorio, omite
                    
                    try:
                        archivos = os.listdir(ruta_nombre_comun)
                        # Filtrar `.DS_Store` o cualquier otro archivo no deseado
                        archivos = [archivo for archivo in archivos if not archivo.startswith('.')]
                    except Exception as e:
                        print(f"Error al listar {ruta_nombre_comun}: {e}")
                        continue
                    
                    if len(archivos) > 0:
                        # Incluir el nombre común y el conteo de archivos en los datos
                        datos.append([familia, genero, especie, nombre_comun, len(archivos)])
    
    especies_pocas_grabaciones = pd.DataFrame(datos, columns=columnas)
    return especies_pocas_grabaciones

# Uso de la función
ruta_base = './songs'
df = encontrar_especies_con_pocos_archivos(ruta_base)

In [12]:
print(df.shape)
df = df.sort_values(by='Number of Recordings', ascending=False)
df.head(10)

(1017, 5)

,Family,Genus,Species,Comun Name,Number of Recordings
979,Passerellidae,Zonotrichia,Zonotrichia capensis,Rufous-collaredSparrow,416
381,Hirundinidae,Hirundo,Hirundo rustica,BarnSwallow,413
550,Vireonidae,Vireo,Vireo griseus,White-eyedVireo,400
328,Tyrannidae,Myiozetetes,Myiozetetes similis,SocialFlycatcher,399
219,Tyrannidae,Lathrotriccus,Lathrotriccus euleri,Euler'sFlycatcher,381
158,Turdidae,Hylocichla,Hylocichla mustelina,WoodThrush,371
593,Fringillidae,Spinus,Spinus psaltria,LesserGoldfinch,367
708,Troglodytidae,Troglodytes,Troglodytes aedon,HouseWren,361
556,Vireonidae,Vireo,Vireo olivaceus,Red-eyedVireo,360
343,Tyrannidae,Myiodynastes,Myiodynastes maculatus,StreakedFlycatcher,354

In [13]:
df[df['Family'] == 'Psittacidae'].sort_values(by='Number of Recordings', ascending=False).head(10)

,Family,Genus,Species,Comun Name,Number of Recordings
404,Psittacidae,Pionus,Pionus menstruus,Blue-headedParrot,89
403,Psittacidae,Ara,Ara ararauna,Blue-and-yellowMacaw,82
405,Psittacidae,Brotogeris,Brotogeris jugularis,Orange-chinnedParakeet,70
406,Psittacidae,Forpus,Forpus conspicillatus,SpectacledParrotlet,20
401,Psittacidae,Bolborhynchus,Bolborhynchus lineola,BarredParakeet,14
402,Psittacidae,Touit,Touit dilectissimus,Blue-frontedParrotlet,8

In [14]:
df[df['Species'] == 'Campylorhamphus trochilirostris']

,Family,Genus,Species,Comun Name,Number of Recordings
59,Furnariidae,Campylorhamphus,Campylorhamphus trochilirostris,Red-billedScythebill,231

In [29]:
df[df['Number of Recordings']<=4]['Species'].unique().tolist()

['Chloropipo flavicapilla',
 'Cotinga maynana',
 'Lonchura malacca',
 'Haematoderus militaris',
 'Psarocolius guatimozinus',
 'Siptornis striaticollis',
 'Polioptila guianensis',
 'Eubucco richardsoni',
 'Chlorospingus tacarcunae',
 'Snowornis cryptolophus',
 'Spinus yarrellii',
 'Polioptila facilis',
 'Chlorospingus inornatus',
 'Carpodectes hopkei',
 'Cotinga nattererii',
 'Tangara fucosa',
 'Bangsia arcaei',
 'Gymnoderus foetidus',
 'Margarornis bellulus',
 'Cotinga cotinga',
 'Dacnis viguieri']

In [16]:
df['Number of Recordings'].sum()

89923

In [ ]:
df.to_csv('/Users/camcortes/Documents/birds-sounds/data/Species_Passeriformes_Summary.csv', index=False)