In [1]:
# manejo de datos
import numpy as np
import pandas as pd
import os

from google.colab import drive
drive.mount('/content/drive')

import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
def summary(ruta_base):
    columnas = ['Family', 'Genus', 'Species', 'Comun Name', 'Number of Recordings']  # Incluir el nombre de la columna corregido
    datos = []  # Lista para acumular los datos

    try:
        familias = os.listdir(ruta_base)
    except Exception as e:
        print(f"Error al listar {ruta_base}: {e}")
        return pd.DataFrame(datos, columns=columnas)

    for familia in familias:
        ruta_familia = os.path.join(ruta_base, familia)
        if not os.path.isdir(ruta_familia):
            continue  # Si no es un directorio, omite

        try:
            generos = os.listdir(ruta_familia)
        except Exception as e:
            print(f"Error al listar {ruta_familia}: {e}")
            continue

        for genero in generos:
            ruta_genero = os.path.join(ruta_familia, genero)
            if not os.path.isdir(ruta_genero):
                continue  # Si no es un directorio, omite

            try:
                especies = os.listdir(ruta_genero)
            except Exception as e:
                print(f"Error al listar {ruta_genero}: {e}")
                continue

            for especie in especies:
                ruta_especie = os.path.join(ruta_genero, especie)
                if not os.path.isdir(ruta_especie):
                    continue  # Si no es un directorio, omite

                try:
                    nombres_comunes = os.listdir(ruta_especie)
                except Exception as e:
                    print(f"Error al listar {ruta_especie}: {e}")
                    continue

                for nombre_comun in nombres_comunes:
                    ruta_nombre_comun = os.path.join(ruta_especie, nombre_comun)
                    if not os.path.isdir(ruta_nombre_comun):
                        continue  # Si no es un directorio, omite

                    try:
                        archivos = os.listdir(ruta_nombre_comun)
                        # Filtrar `.DS_Store` o cualquier otro archivo no deseado
                        archivos = [archivo for archivo in archivos if not archivo.startswith('.')]
                    except Exception as e:
                        print(f"Error al listar {ruta_nombre_comun}: {e}")
                        continue

                    if len(archivos) > 0:
                        # Incluir el nombre común y el conteo de archivos en los datos
                        datos.append([familia, genero, especie, nombre_comun, len(archivos)])

    especies_pocas_grabaciones = pd.DataFrame(datos, columns=columnas)
    return especies_pocas_grabaciones

In [3]:
# Uso de la función
ruta_base = '/content/drive/My Drive/songs'
df = summary(ruta_base)

In [4]:
print(df.shape)
df = df.sort_values(by='Number of Recordings', ascending=False)
df.head(10)

(1002, 5)

,Family,Genus,Species,Comun Name,Number of Recordings
938,Passeridae,Passer,Passer domesticus,HouseSparrow,743
631,Troglodytidae,Troglodytes,Troglodytes aedon,HouseWren,720
660,Troglodytidae,Henicorhina,Henicorhina leucophrys,Grey-breastedWoodWren,413
625,Hirundinidae,Hirundo,Hirundo rustica,BarnSwallow,389
970,Passerellidae,Zonotrichia,Zonotrichia capensis,Rufous-collaredSparrow,381
491,Tyrannidae,Myiarchus,Myiarchus tyrannulus,Brown-crestedFlycatcher,314
460,Tyrannidae,Pitangus,Pitangus sulphuratus,GreatKiskadee,302
659,Troglodytidae,Henicorhina,Henicorhina leucosticta,White-breastedWoodWren,277
571,Vireonidae,Cyclarhis,Cyclarhis gujanensis,Rufous-browedPeppershrike,259
394,Tyrannidae,Tolmomyias,Tolmomyias sulphurescens,Yellow-oliveFlatbill,258

In [5]:
df[df['Family'] == 'Psittacidae'].sort_values(by='Number of Recordings', ascending=False).head(10)

,Family,Genus,Species,Comun Name,Number of Recordings
1000,Psittacidae,Pionus,Pionus menstruus,Blue-headedParrot,87
1001,Psittacidae,Ara,Ara ararauna,Blue-and-yellowMacaw,82
998,Psittacidae,Brotogeris,Brotogeris jugularis,Orange-chinnedParakeet,67
999,Psittacidae,Forpus,Forpus conspicillatus,SpectacledParrotlet,20
997,Psittacidae,Bolborhynchus,Bolborhynchus lineola,BarredParakeet,14
996,Psittacidae,Touit,Touit dilectissimus,Blue-frontedParrotlet,8

In [6]:
df[df['Family'] == 'Troglodytidae'].sort_values(by='Number of Recordings', ascending=False)

,Family,Genus,Species,Comun Name,Number of Recordings
631,Troglodytidae,Troglodytes,Troglodytes aedon,HouseWren,720
660,Troglodytidae,Henicorhina,Henicorhina leucophrys,Grey-breastedWoodWren,413
659,Troglodytidae,Henicorhina,Henicorhina leucosticta,White-breastedWoodWren,277
654,Troglodytidae,Cantorchilus,Cantorchilus nigricapillus,BayWren,175
655,Troglodytidae,Cantorchilus,Cantorchilus leucotis,Buff-breastedWren,171
644,Troglodytidae,Pheugopedius,Pheugopedius euophrys,Plain-tailedWren,155
646,Troglodytidae,Pheugopedius,Pheugopedius coraya,CorayaWren,143
628,Troglodytidae,Microcerculus,Microcerculus marginatus,SouthernNightingale-Wren,137
635,Troglodytidae,Cistothorus,Cistothorus platensis,GrassWren,130
649,Troglodytidae,Pheugopedius,Pheugopedius genibarbis,MoustachedWren,129
665,Troglodytidae,Cyphorhinus,Cyphorhinus thoracicus,Chestnut-breastedWren,93
641,Troglodytidae,Campylorhynchus,Campylorhynchus turdinus,Thrush-likeWren,88
645,Troglodytidae,Pheugopedius,Pheugopedius mystacalis,WhiskeredWren,88
648,Troglodytidae,Pheugopedius,Pheugopedius sclateri,Speckle-breastedWren,80
658,Troglodytidae,Cinnycerthia,Cinnycerthia olivascens,Sepia-brownWren,79
663,Troglodytidae,Cyphorhinus,Cyphorhinus arada,MusicianWren,70
636,Troglodytidae,Cistothorus,Cistothorus apolinari,Apolinar'sWren,67
632,Troglodytidae,Troglodytes,Troglodytes solstitialis,MountainWren,65
643,Troglodytidae,Pheugopedius,Pheugopedius fasciatoventris,Black-belliedWren,65
647,Troglodytidae,Pheugopedius,Pheugopedius rutilus,Rufous-breastedWren,64
650,Troglodytidae,Thryophilus,Thryophilus rufalbus,Rufous-and-whiteWren,58
664,Troglodytidae,Cyphorhinus,Cyphorhinus phaeocephalus,SongWren,56
638,Troglodytidae,Campylorhynchus,Campylorhynchus zonatus,Band-backedWren,46
653,Troglodytidae,Cantorchilus,Cantorchilus leucopogon,Stripe-throatedWren,37
640,Troglodytidae,Campylorhynchus,Campylorhynchus griseus,BicoloredWren,37
629,Troglodytidae,Microcerculus,Microcerculus bambla,Wing-bandedWren,34
642,Troglodytidae,Pheugopedius,Pheugopedius spadix,Sooty-headedWren,31
657,Troglodytidae,Cinnycerthia,Cinnycerthia unirufa,RufousWren,31
662,Troglodytidae,Henicorhina,Henicorhina negreti,MunchiqueWoodWren,24
661,Troglodytidae,Henicorhina,Henicorhina anachoreta,HermitWoodWren,22
630,Troglodytidae,Odontorchilus,Odontorchilus branickii,Grey-mantledWren,18
652,Troglodytidae,Thryophilus,Thryophilus nicefori,Niceforo'sWren,16
639,Troglodytidae,Campylorhynchus,Campylorhynchus nuchalis,Stripe-backedWren,13
637,Troglodytidae,Campylorhynchus,Campylorhynchus albobrunneus,White-headedWren,11
634,Troglodytidae,Troglodytes,Troglodytes ochraceus,OchraceousWren,8
656,Troglodytidae,Cantorchilus,Cantorchilus griseus,GreyWren,8
633,Troglodytidae,Troglodytes,Troglodytes monticola,SantaMartaWren,7
651,Troglodytidae,Thryophilus,Thryophilus sernai,AntioquiaWren,1

In [7]:
df[df['Number of Recordings']<=4]['Species'].unique().tolist()

['Cranioleuca vulpecula',
 'Chlorochrysa nitidissima',
 'Atlapetes semirufus',
 'Sublegatus obscurior',
 'Arremon crassirostris',
 'Myadestes coloratus',
 'Cinclus leucocephalus',
 'Myrmotherula sunensis',
 'Drymotoxeres pucheranii',
 'Conirostrum rufum',
 'Sporophila murallae',
 'Tachycineta cyaneoviridis',
 'Vireo caribaeus',
 'Fluvicola pica',
 'Sicalis columbiana',
 'Cnemarchus erythropygius',
 'Myiotheretes pernix',
 'Thraupis glaucocolpa',
 'Ixothraupis varia',
 'Myiobius atricaudus',
 'Laniocera rufescens',
 'Chrysothlypis chrysomelas',
 'Sirystes albogriseus',
 'Arremonops tocuyensis',
 'Eubucco richardsoni',
 'Pittasoma michleri',
 'Ixothraupis guttata',
 'Margarornis stellatus',
 'Siptornis striaticollis',
 'Psarocolius cassini',
 'Muscisaxicola alpinus',
 'Vireo approximans',
 'Spinus spinescens',
 'Myrmotherula behni',
 'Contopus nigrescens',
 'Cyanerpes nitidus',
 'Dacnis albiventris',
 'Rhynchocyclus fulvipectus',
 'Cryptopipo holochlora',
 'Cyanerpes lucidus',
 'Myrmotherula ambigua',
 'Furnarius torridus',
 'Knipolegus poecilocercus',
 'Thlypopsis ornata',
 'Muscisaxicola albilora',
 'Scytalopus panamensis',
 'Frederickena unduliger',
 'Polioptila facilis',
 'Chloropipo flavicapilla',
 'Tangara inornata',
 'Elaenia strepera',
 'Phylloscartes flavovirens',
 'Cotinga cayana',
 'Doliornis remseni',
 'Zimmerius improbus',
 'Gymnoderus foetidus',
 'Xiphorhynchus ocellatus',
 'Thlypopsis fulviceps',
 'Psarocolius guatimozinus',
 'Thryophilus sernai',
 'Paroaria nigrogenis',
 'Icterus auricapillus',
 'Spinus yarrellii',
 'Elaenia pelzelni',
 'Porphyrolaema porphyrolaema',
 'Saltator cinctus',
 'Snowornis cryptolophus',
 'Haematoderus militaris',
 'Sporophila americana',
 'Cephalopterus ornatus',
 'Lonchura atricapilla',
 'Lonchura malacca',
 'Lipaugus fuscocinereus',
 'Myiarchus panamensis',
 'Pseudocolopteryx acutipennis']

In [8]:
df['Number of Recordings'].sum()

40276

In [9]:
df.to_csv('/content/drive/My Drive/data_passerifromes/summary_songs.csv', index=False)