In [1]:
import os
import pandas as pd

pd.set_option('display.max_columns', None)

In [2]:
def obtener_paths_cantos(base_dir):
    data = []

    # Recorrer las familias
    for familia in os.listdir(base_dir):
        familia_path = os.path.join(base_dir, familia)
        if os.path.isdir(familia_path):
            # Recorrer los géneros
            for genero in os.listdir(familia_path):
                genero_path = os.path.join(familia_path, genero)
                if os.path.isdir(genero_path):
                    # Recorrer las especies
                    for especie in os.listdir(genero_path):
                        especie_path = os.path.join(genero_path, especie)
                        if os.path.isdir(especie_path):
                            # Recorrer los nombres comunes
                            for nombre_comun in os.listdir(especie_path):
                                nombre_comun_path = os.path.join(especie_path, nombre_comun)
                                if os.path.isdir(nombre_comun_path):
                                    # Recorrer los cantos
                                    for canto in os.listdir(nombre_comun_path):
                                        canto_path = os.path.join(nombre_comun_path, canto)
                                        if os.path.isfile(canto_path):
                                            data.append({
                                                'Specie': especie,
                                                'Genus': genero,
                                                'Family': familia,
                                                'Path': canto_path
                                            })

    # Crear el DataFrame
    df = pd.DataFrame(data)
    return df

# Definir la ruta base
base_dir = 'C:/Users/Camilo/Documents/Mis Documentos/Trabajo de grado/songs'

# Obtener el DataFrame
df = obtener_paths_cantos(base_dir)

# Mostrar el DataFrame
df.sample(4)

,Specie,Genus,Family,Path
1944,Lipaugus vociferans,Lipaugus,Cotingidae,C:/Users/Camilo/Documents/Mis Documentos/Traba...
79953,Empidonax virescens,Empidonax,Tyrannidae,C:/Users/Camilo/Documents/Mis Documentos/Traba...
62859,Schiffornis major,Schiffornis,Tityridae,C:/Users/Camilo/Documents/Mis Documentos/Traba...
94926,Tolmomyias sulphurescens,Tolmomyias,Tyrannidae,C:/Users/Camilo/Documents/Mis Documentos/Traba...

In [3]:
print(df['Path'][0])

C:/Users/Camilo/Documents/Mis Documentos/Trabajo de grado/songs\Alaudidae\Eremophila\Eremophila alpestris\HornedLark\105151.mp3

In [4]:
df.shape

(101200, 4)

In [5]:
avonet = pd.read_csv('C:/Users/Camilo/Documents/Mis Documentos/Trabajo de grado/notebooks/evolution/data_total/data_songs_avonet.csv')
avonet.head()

,Specie,chroma_cens_kurtosis_01,chroma_cens_kurtosis_02,chroma_cens_kurtosis_03,chroma_cens_kurtosis_04,chroma_cens_kurtosis_05,chroma_cens_kurtosis_06,chroma_cens_kurtosis_07,chroma_cens_kurtosis_08,chroma_cens_kurtosis_09,chroma_cens_max_01,chroma_cens_max_02,chroma_cens_max_03,chroma_cens_max_04,chroma_cens_max_05,chroma_cens_max_06,chroma_cens_max_07,chroma_cens_max_08,chroma_cens_max_09,chroma_cens_max_10,chroma_cens_max_11,chroma_cens_max_12,chroma_cens_mean_01,chroma_cens_mean_02,chroma_cens_mean_03,chroma_cens_mean_04,chroma_cens_mean_05,chroma_cens_mean_06,chroma_cens_mean_07,chroma_cens_mean_08,chroma_cens_mean_09,chroma_cens_mean_10,chroma_cens_mean_11,chroma_cens_mean_12,chroma_cens_median_01,chroma_cens_median_02,chroma_cens_median_03,chroma_cens_median_04,chroma_cens_median_05,chroma_cens_median_06,chroma_cens_median_07,chroma_cens_median_08,chroma_cens_median_09,chroma_cens_median_10,chroma_cens_median_11,chroma_cens_median_12,chroma_cens_min_01,chroma_cens_min_02,chroma_cens_min_03,chroma_cens_min_04,chroma_cens_min_05,chroma_cens_min_06,chroma_cens_min_07,chroma_cens_min_08,chroma_cens_min_09,chroma_cens_min_10,chroma_cens_min_11,chroma_cens_min_12,chroma_cens_skew_01,chroma_cens_skew_02,chroma_cens_skew_03,chroma_cens_skew_04,chroma_cens_skew_05,chroma_cens_skew_06,chroma_cens_skew_07,chroma_cens_skew_08,chroma_cens_skew_09,chroma_cens_std_01,chroma_cens_std_02,chroma_cens_std_03,chroma_cens_std_04,chroma_cens_std_05,chroma_cens_std_06,chroma_cens_std_07,chroma_cens_std_08,chroma_cens_std_09,chroma_cens_std_10,chroma_cens_std_11,chroma_cens_std_12,chroma_cqt_kurtosis_01,chroma_cqt_kurtosis_02,chroma_cqt_kurtosis_03,chroma_cqt_kurtosis_04,chroma_cqt_kurtosis_05,chroma_cqt_kurtosis_06,chroma_cqt_kurtosis_07,chroma_cqt_kurtosis_08,chroma_cqt_kurtosis_09,chroma_cqt_kurtosis_10,chroma_cqt_kurtosis_11,chroma_cqt_kurtosis_12,chroma_cqt_max_01,chroma_cqt_max_02,chroma_cqt_max_03,chroma_cqt_max_04,chroma_cqt_max_05,chroma_cqt_max_06,chroma_cqt_max_07,chroma_cqt_max_08,chroma_cqt_max_09,chroma_cqt_max_10,chroma_cqt_max_11,chroma_cqt_max_12,chroma_cqt_mean_01,chroma_cqt_mean_02,chroma_cqt_mean_03,chroma_cqt_mean_04,chroma_cqt_mean_05,chroma_cqt_mean_06,chroma_cqt_mean_07,chroma_cqt_mean_08,chroma_cqt_mean_09,chroma_cqt_mean_10,chroma_cqt_mean_11,chroma_cqt_mean_12,chroma_cqt_median_01,chroma_cqt_median_02,chroma_cqt_median_03,chroma_cqt_median_04,chroma_cqt_median_05,chroma_cqt_median_06,chroma_cqt_median_07,chroma_cqt_median_08,chroma_cqt_median_09,chroma_cqt_median_10,chroma_cqt_median_11,chroma_cqt_median_12,chroma_cqt_min_01,chroma_cqt_min_02,chroma_cqt_min_03,chroma_cqt_min_04,chroma_cqt_min_05,chroma_cqt_min_06,chroma_cqt_min_07,chroma_cqt_min_08,chroma_cqt_min_09,chroma_cqt_min_10,chroma_cqt_min_11,chroma_cqt_min_12,chroma_cqt_skew_01,chroma_cqt_skew_02,chroma_cqt_skew_03,chroma_cqt_skew_04,chroma_cqt_skew_05,chroma_cqt_skew_06,chroma_cqt_skew_07,chroma_cqt_skew_08,chroma_cqt_skew_09,chroma_cqt_skew_10,chroma_cqt_skew_11,chroma_cqt_skew_12,chroma_cqt_std_01,chroma_cqt_std_02,chroma_cqt_std_03,chroma_cqt_std_04,chroma_cqt_std_05,chroma_cqt_std_06,chroma_cqt_std_07,chroma_cqt_std_08,chroma_cqt_std_09,chroma_cqt_std_10,chroma_cqt_std_11,chroma_cqt_std_12,chroma_stft_kurtosis_01,chroma_stft_kurtosis_02,chroma_stft_kurtosis_03,chroma_stft_kurtosis_04,chroma_stft_kurtosis_05,chroma_stft_kurtosis_06,chroma_stft_kurtosis_07,chroma_stft_kurtosis_08,chroma_stft_kurtosis_09,chroma_stft_kurtosis_10,chroma_stft_kurtosis_11,chroma_stft_kurtosis_12,chroma_stft_max_01,chroma_stft_max_02,chroma_stft_max_03,chroma_stft_max_04,chroma_stft_max_05,chroma_stft_max_06,chroma_stft_max_07,chroma_stft_max_08,chroma_stft_max_09,chroma_stft_max_10,chroma_stft_max_11,chroma_stft_max_12,chroma_stft_mean_01,chroma_stft_mean_02,chroma_stft_mean_03,chroma_stft_mean_04,chroma_stft_mean_05,chroma_stft_mean_06,chroma_stft_mean_07,chroma_stft_mean_08,chroma_stft_mean_09,chroma_stft_mean_10,chroma_stft_mean_11,chroma_stft_mean_12,chroma_stft_median_01,chroma_stft_median_02,chroma_stft_median_03,chroma_stft_median_04,chroma_stft_median_05,chroma_stft_median_06,chroma_stft_median_07,chroma_stft_median_08,chroma_stft_median_09,chroma_stft_median_10,chroma_stft_median_11,chroma_stft_median_12,chroma_stft_min_01,chroma_stft_min_02,chroma_stft_min_03,chroma_stft_min_04,chroma_stft_min_05,chroma_stft_min_06,chroma_stft_min_07,chroma_stft_min_08,chroma_stft_min_09,chroma_stft_min_10,chroma_stft_min_11,chroma_stft_min_12,chroma_stft_skew_01,chroma_stft_skew_02,chroma_stft_skew_03,chroma_stft_skew_04,chroma_stft_skew_05,chroma_stft_skew_06,chroma_stft_skew_07,chroma_stft_skew_08,chroma_stft_skew_09,chroma_stft_skew_10,chroma_stft_skew_11,chroma_stft_skew_12,chroma_stft_std_01,chroma_stft_std_02,chroma_stft_std_03,chroma_stft_std_04,chroma_stft_std_05,chroma_stft_std_06,chroma_stft_std_07,chroma_stft_std_08,chroma_stft_std_09,chroma_stft_std_10,chroma_stft_std_11,chroma_stft_std_12,rmse_kurtosis_01,rmse_max_01,rmse_mean_01,rmse_median_01,rmse_min_01,rmse_skew_01,rmse_std_01,spectral_bandwidth_kurtosis_01,spectral_bandwidth_max_01,spectral_bandwidth_mean_01,spectral_bandwidth_median_01,spectral_bandwidth_min_01,spectral_bandwidth_skew_01,spectral_bandwidth_std_01,spectral_centroid_kurtosis_01,spectral_centroid_max_01,spectral_centroid_mean_01,spectral_centroid_median_01,spectral_centroid_min_01,spectral_centroid_skew_01,spectral_centroid_std_01,spectral_contrast_kurtosis_01,spectral_contrast_kurtosis_02,spectral_contrast_kurtosis_03,spectral_contrast_kurtosis_04,spectral_contrast_kurtosis_05,spectral_contrast_kurtosis_06,spectral_contrast_kurtosis_07,spectral_contrast_max_01,spectral_contrast_max_02,spectral_contrast_max_03,spectral_contrast_max_04,spectral_contrast_max_05,spectral_contrast_max_06,spectral_contrast_max_07,spectral_contrast_mean_01,spectral_contrast_mean_02,spectral_contrast_mean_03,spectral_contrast_mean_04,spectral_contrast_mean_05,spectral_contrast_mean_06,spectral_contrast_mean_07,spectral_contrast_median_01,spectral_contrast_median_02,spectral_contrast_median_03,spectral_contrast_median_04,spectral_contrast_median_05,spectral_contrast_median_06,spectral_contrast_median_07,spectral_contrast_min_01,spectral_contrast_min_02,spectral_contrast_min_03,spectral_contrast_min_04,spectral_contrast_min_05,spectral_contrast_min_06,spectral_contrast_min_07,spectral_contrast_skew_01,spectral_contrast_skew_02,spectral_contrast_skew_03,spectral_contrast_skew_04,spectral_contrast_skew_05,spectral_contrast_skew_06,spectral_contrast_skew_07,spectral_contrast_std_01,spectral_contrast_std_02,spectral_contrast_std_03,spectral_contrast_std_04,spectral_contrast_std_05,spectral_contrast_std_06,spectral_contrast_std_07,spectral_rolloff_kurtosis_01,spectral_rolloff_max_01,spectral_rolloff_mean_01,spectral_rolloff_median_01,spectral_rolloff_min_01,spectral_rolloff_skew_01,spectral_rolloff_std_01,tonnetz_kurtosis_01,tonnetz_kurtosis_02,tonnetz_kurtosis_03,tonnetz_kurtosis_04,tonnetz_kurtosis_05,tonnetz_kurtosis_06,tonnetz_max_01,tonnetz_max_02,tonnetz_max_03,tonnetz_max_04,tonnetz_max_05,tonnetz_max_06,tonnetz_mean_01,tonnetz_mean_02,tonnetz_mean_03,tonnetz_mean_04,tonnetz_mean_05,tonnetz_mean_06,tonnetz_median_01,tonnetz_median_02,tonnetz_median_03,tonnetz_median_04,tonnetz_median_05,tonnetz_median_06,tonnetz_min_01,tonnetz_min_02,tonnetz_min_03,tonnetz_min_04,tonnetz_min_05,tonnetz_min_06,tonnetz_skew_01,tonnetz_skew_02,tonnetz_skew_03,tonnetz_skew_04,tonnetz_skew_05,tonnetz_skew_06,tonnetz_std_01,tonnetz_std_02,tonnetz_std_03,tonnetz_std_04,tonnetz_std_05,tonnetz_std_06,zcr_kurtosis_01,zcr_max_01,zcr_mean_01,zcr_median_01,zcr_min_01,zcr_skew_01,zcr_std_01,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-Wing.Index,Tail.Length,Mass,Habitat,Habitat.Density,Migration,Trophic.Level,Trophic.Niche,Primary.Lifestyle,Min.Latitude,Max.Latitude,Centroid.Latitude,Centroid.Longitude,Range.Size,Species.Status,Genus,Family,Suborder
0,Acropternis_orthonyx,0.001471,0.007027,0.010283,0.004517,0.003856,0.001506,0.000723,0.000912,0.002066,0.648805,0.780883,0.663126,0.551339,0.438560,0.390459,0.376038,0.373493,0.352783,0.339950,0.364230,0.418704,0.380927,0.488973,0.385909,0.352912,0.253815,0.240446,0.206878,0.226549,0.211372,0.175691,0.194284,0.181324,0.350505,0.426024,0.377120,0.362586,0.254581,0.243424,0.214476,0.235386,0.215080,0.178882,0.198423,0.176428,0.119356,0.236279,0.164361,0.096330,0.057728,0.037007,0.028495,0.028722,0.023756,0.021995,0.021273,0.030672,0.102680,0.206678,0.234551,0.539433,0.458215,0.093098,0.058285,0.072497,0.073833,0.290299,0.318862,0.267050,0.243572,0.245347,0.219827,0.198302,0.213141,0.196763,0.195879,0.191179,0.190474,0.000629,0.001407,0.000343,0.000724,0.000734,0.000588,0.000257,0.000162,0.000223,0.000550,0.000906,0.001893,1.000000,1.000000,1.00000,1.000000,0.986494,0.974727,0.973353,0.969530,0.959500,0.958637,0.957238,0.967041,0.593296,0.684723,0.608010,0.570342,0.472685,0.411446,0.405389,0.402830,0.387714,0.377450,0.376614,0.367997,0.595944,0.710317,0.612082,0.582421,0.472024,0.403424,0.397697,0.395814,0.380578,0.371523,0.369764,0.352547,0.042418,0.082851,0.055358,0.043476,0.030027,0.021366,0.019394,0.019045,0.016319,0.012623,0.013908,0.018036,0.373350,0.427082,0.673697,0.625991,0.494511,0.164735,0.302230,0.283995,0.178357,0.154616,0.232630,0.153087,0.569113,0.519638,0.563765,0.556395,0.525013,0.511016,0.480995,0.465266,0.446832,0.464897,0.463545,0.447854,0.000408,0.000647,0.000751,0.000354,0.000250,0.000184,0.000197,0.000152,0.000152,0.000663,0.000724,0.000373,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.0,1.000000,1.000000,0.999556,1.000000,0.551524,0.568445,0.576008,0.576199,0.561331,0.544679,0.533019,0.526169,0.524307,0.523264,0.530222,0.535651,0.569082,0.586704,0.593233,0.592804,0.579222,0.565798,0.555886,0.552318,0.551168,0.550540,0.554477,0.555628,0.002370,0.003181,0.005444,0.006740,0.008764,0.007553,0.004466,0.002264,0.002244,0.002173,0.003070,0.002843,0.431620,0.510384,0.519611,0.260727,0.217509,0.254743,0.207015,0.183811,0.261895,0.315445,0.300053,0.424517,0.605074,0.603867,0.575013,0.581415,0.589401,0.607541,0.598286,0.625531,0.621803,0.616264,0.578923,0.594830,0.007701,0.023056,0.030794,0.014795,0.001956,0.472892,0.037006,0.005799,0.487877,0.396409,0.429273,0.190194,0.447451,0.158081,0.006699,0.320833,0.222023,0.221001,0.108590,0.369187,0.100297,0.068470,0.112198,0.152880,0.038724,0.044872,0.043382,0.017986,0.378847,0.293476,0.329044,0.372922,0.289274,0.356522,0.659636,0.302163,0.223749,0.194647,0.110251,0.074428,0.118504,0.641271,0.298910,0.228707,0.189666,0.072010,0.058529,0.108055,0.640627,0.146734,0.166500,0.195842,0.197154,0.226881,0.179661,0.333640,0.493284,0.602316,0.623753,0.540403,0.587163,0.550012,0.641003,0.200771,0.085195,0.186235,0.237578,0.148769,0.129009,0.179045,0.003728,0.613160,0.368064,0.395108,0.096498,0.487640,0.207041,0.009099,0.006394,0.013637,0.014560,0.009013,0.010176,0.295009,0.304878,0.358638,0.459676,0.443844,0.320703,0.281380,0.532709,0.527748,0.465552,0.420959,0.321345,0.251095,0.486436,0.574344,0.440093,0.403861,0.325176,0.680794,0.686476,0.412624,0.513599,0.609311,0.320151,0.684396,0.183372,0.650663,0.728006,0.821681,0.702080,0.114772,0.128417,0.169831,0.190223,0.156245,0.163025,0.004543,0.301060,0.131440,0.130953,0.060814,0.335196,0.100959,22.9,10.4,4.5,6.5,36.4,94.8,5.2,89.9,5.5,88.9,89.86,Forest,1.0,1.0,Carnivore,Invertivore,Insessorial,-5.46,9.74,1.60,-76.74,112912.00,Extant,Acropternis,Rhinocryptidae,tiranni
1,Agriornis_albicauda,0.001132,0.003793,0.006593,0.003264,0.003602,0.003011,0.002900,0.004278,0.004896,0.382395,0.396291,0.492402,0.555568,0.473350,0.467723,0.462359,0.447528,0.417588,0.450097,0.410618,0.383529,0.224551,0.252463,0.273591,0.338166,0.282609,0.356559,0.316613,0.328987,0.286994,0.254432,0.244319,0.208685,0.209318,0.231174,0.265753,0.328230,0.272141,0.346990,0.318240,0.327644,0.276495,0.243580,0.239582,0.201697,0.107600,0.101624,0.080041,0.145951,0.147864,0.205883,0.170060,0.134710,0.085770,0.101908,0.114392,0.122225,0.102793,0.178931,0.224752,0.557495,0.471830,0.103103,0.070292,0.087586,0.085654,0.180796,0.177629,0.237913,0.227310,0.212837,0.187058,0.174414,0.203290,0.200749,0.223251,0.183656,0.155745,0.001155,0.002343,0.000543,0.000636,0.001255,0.002347,0.003710,0.002295,0.000946,0.000220,0.000386,0.000589,0.980475,0.977494,1.00000,1.000000,0.990813,1.000000,0.999241,0.996031,0.996052,0.992150,0.986384,0.983646,0.397548,0.400280,0.441671,0.531710,0.516146,0.556753,0.530548,0.498653,0.454098,0.463997,0.420394,0.390728,0.376301,0.378246,0.409643,0.505782,0.506615,0.573703,0.526269,0.483557,0.436811,0.448435,0.398893,0.363851,0.023271,0.039006,0.062892,0.074882,0.077334,0.072474,0.071364,0.055089,0.041662,0.027969,0.022902,0.027743,0.383558,0.445862,0.682551,0.633632,0.496842,0.169213,0.310127,0.291121,0.181923,0.152220,0.230840,0.148649,0.445851,0.424419,0.469586,0.497259,0.458357,0.464090,0.481772,0.492128,0.479898,0.525522,0.490677,0.456969,0.000329,0.000500,0.000587,0.000288,0.000204,0.000132,0.000161,0.000138,0.000150,0.000618,0.000694,0.000312,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,0.631054,0.622373,0.623398,0.631095,0.617851,0.617893,0.605864,0.601593,0.607308,0.611463,0.607937,0.617715,0.633943,0.625263,0.622952,0.633452,0.619857,0.621012,0.603581,0.595570,0.602919,0.605973,0.608872,0.619527,0.067891,0.074550,0.080535,0.048128,0.035505,0.016821,0.020482,0.017232,0.017272,0.022006,0.032851,0.064005,0.432654,0.512439,0.521835,0.262263,0.218328,0.255142,0.207899,0.184973,0.262595,0.316820,0.301391,0.425432,0.501650,0.496783,0.477877,0.491994,0.500462,0.517640,0.485934,0.495012,0.494692,0.508487,0.458862,0.479947,0.025185,0.016589,0.015231,0.007826,0.000012,0.505531,0.019085,0.018140,0.619991,0.554647,0.580349,0.280423,0.424148,0.162689,0.010224,0.475052,0.299735,0.295222,0.132072,0.363400,0.135510,0.055808,0.103419,0.125691,0.046891,0.037113,0.020545,0.020700,0.335153,0.256306,0.299808,0.199789,0.226284,0.202285,0.663857,0.287869,0.216740,0.239603,0.046064,0.058862,0.068738,0.671787,0.286415,0.223061,0.239179,0.037753,0.050001,0.062849,0.668154,0.160532,0.181733,0.237266,0.204267,0.241026,0.175708,0.414098,0.488348,0.590894,0.575126,0.518731,0.572908,0.521901,0.631659,0.199809,0.076188,0.179314,0.072783,0.100793,0.086374,0.166720,0.013600,0.800946,0.549654,0.578394,0.095746,0.471333,0.239392,0.005457,0.002771,0.006077,0.005868,0.004546,0.003932,0.267232,0.278493,0.338600,0.363829,0.309333,0.288960,0.293596,0.528885,0.568007,0.443048,0.382565,0.323573,0.261704,0.478201,0.598579,0.418383,0.373263,0.320487,0.715361,0.761377,0.579052,0.602927,0.624658,0.507711,0.681386,0.212595,0.691447,0.740137,0.794826,0.739502,0.100166,0.089130,0.085814,0.115431,0.097360,0.097958,0.003733,0.411529,0.172593,0.171226,0.101925,0.327314,0.125055,32.4,18.6,7.0,8.6,39.7,141.3,35.2,106.0,24.9,113.1,53.00,Shrubland,3.0,1.0,Carnivore,Vertivore,Insessorial,-27.47,0.00,-15.22,-71.16,579914.07,Extant,Agriornis,Tyrannidae,tiranni
2,Agriornis_montanus,0.002116,0.014413,0.019840,0.009525,0.005802,0.010294,0.012779,0.014382,0.010970,0.521195,0.678582,0.727320,0.633158,0.460323,0.361243,0.347295,0.386281,0.377767,0.395316,0.398350,0.378965,0.354515,0.453098,0.416843,0.386232,0.241711,0.220344,0.185753,0.219448,0.228542,0.204111,0.208134,0.195953,0.343202,0.414568,0.409309,0.378872,0.233819,0.213303,0.180580,0.214570,0.215623,0.191443,0.195887,0.187063,0.090179,0.194201,0.242609,0.169014,0.061041,0.037918,0.039313,0.051337,0.042054,0.048548,0.037606,0.039940,0.077234,0.196775,0.269169,0.563740,0.472250,0.124856,0.100263,0.111227,0.100099,0.204490,0.206964,0.233429,0.197979,0.214407,0.172977,0.160865,0.176892,0.174408,0.193935,0.195706,0.173644,0.000611,0.001608,0.000314,0.000622,0.001105,0.004567,0.004253,0.001579,0.000253,0.000667,0.000561,0.000641,1.000000,1.000000,1.00000,1.000000,0.989304,0.868362,0.886197,0.925152,0.905559,0.918310,0.949255,0.952759,0.577039,0.672492,0.668088,0.615391,0.463136,0.391418,0.379694,0.401353,0.417452,0.431941,0.410223,0.397322,0.565839,0.690670,0.663987,0.605313,0.447465,0.376615,0.356146,0.382120,0.400706,0.417118,0.384899,0.371004,0.046680,0.065757,0.083888,0.066037,0.037391,0.027319,0.027977,0.030116,0.025072,0.022237,0.015668,0.018609,0.375020,0.427898,0.673582,0.627870,0.497387,0.175696,0.312284,0.289592,0.178465,0.153599,0.231559,0.148036,0.523402,0.501091,0.512113,0.495440,0.443078,0.393422,0.388671,0.388836,0.393867,0.439397,0.455481,0.439122,0.000507,0.000885,0.001017,0.000469,0.000327,0.000215,0.000233,0.000176,0.000185,0.000824,0.001099,0.000468,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,0.584666,0.608126,0.622827,0.621890,0.616005,0.606142,0.577764,0.559649,0.546052,0.564408,0.579613,0.571805,0.600094,0.628592,0.646400,0.638524,0.630072,0.619790,0.585617,0.558357,0.547642,0.575303,0.594432,0.583937,0.006699,0.007261,0.010305,0.013110,0.011548,0.009382,0.024494,0.019581,0.012549,0.007715,0.008488,0.011317,0.431134,0.509259,0.517826,0.259170,0.215577,0.253590,0.207256,0.185182,0.263119,0.315854,0.298011,0.424212,0.520630,0.535215,0.516374,0.515777,0.524135,0.538555,0.499063,0.513756,0.502272,0.509208,0.472256,0.495682,0.010628,0.019294,0.026198,0.020461,0.000032,0.484601,0.022654,0.009897,0.545560,0.447588,0.465894,0.279869,0.437159,0.118427,0.009346,0.409470,0.279569,0.270220,0.167659,0.361826,0.098320,0.060692,0.106094,0.134160,0.077662,0.071944,0.073510,0.013323,0.404808,0.305262,0.321104,0.290690,0.280852,0.267242,0.626574,0.302815,0.228409,0.200581,0.069740,0.052241,0.089487,0.598376,0.299972,0.233843,0.197728,0.059160,0.041609,0.088063,0.592531,0.154108,0.189054,0.221291,0.203873,0.235136,0.175771,0.328327,0.492913,0.601008,0.604204,0.576078,0.620707,0.558355,0.642803,0.214565,0.085279,0.163962,0.103736,0.107026,0.055560,0.199240,0.007664,0.710305,0.446184,0.455835,0.177878,0.482573,0.167226,0.010440,0.008064,0.018833,0.026549,0.013910,0.011871,0.293124,0.313009,0.372294,0.390498,0.370035,0.308938,0.285805,0.538227,0.549815,0.454850,0.395710,0.327874,0.254707,0.487527,0.582690,0.433548,0.385615,0.326723,0.697908,0.722547,0.510575,0.490096,0.559037,0.416298,0.690505,0.202076,0.682677,0.675680,0.776846,0.712963,0.097701,0.103183,0.095360,0.150283,0.117570,0.107339,0.006905,0.366439,0.179651,0.180056,0.087357,0.326708,0.103005,30.4,17.4,5.8,5.7,33.1,131.3,33.0,98.2,25.1,98.2,63.30,Shrubland,3.0,1.0,Carnivore,Omnivore,Insessorial,-50.11,2.51,-30.52,-68.63,2168659.57,Extant,Agriornis,Tyrannidae,tiranni

In [6]:
avonet_cols = ['Specie', 'Beak.Length_Culmen', 'Beak.Length_Nares', 'Beak.Width', 'Beak.Depth', 'Tarsus.Length', 'Wing.Length',
               'Kipps.Distance', 'Secondary1', 'Hand-Wing.Index', 'Tail.Length', 'Mass', 'Habitat', 'Habitat.Density', 'Migration',
               'Trophic.Level', 'Trophic.Niche', 'Primary.Lifestyle', 'Min.Latitude', 'Max.Latitude', 'Centroid.Latitude',
               'Centroid.Longitude', 'Range.Size', 'Species.Status', 'Suborder']

avonet = avonet[avonet_cols]

In [7]:
avonet['Specie'] = avonet['Specie'].str.replace('_', ' ')

In [8]:
df_merge = pd.merge(df, avonet, how="left", on=["Specie", "Specie"])

In [9]:
print(df_merge.shape)
df_merge.head()

(101205, 28)

,Specie,Genus,Family,Path,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-Wing.Index,Tail.Length,Mass,Habitat,Habitat.Density,Migration,Trophic.Level,Trophic.Niche,Primary.Lifestyle,Min.Latitude,Max.Latitude,Centroid.Latitude,Centroid.Longitude,Range.Size,Species.Status,Suborder
0,Eremophila alpestris,Eremophila,Alaudidae,C:/Users/Camilo/Documents/Mis Documentos/Traba...,13.9,9.2,4.2,5.0,23.5,108.1,41.7,66.2,38.6,71.4,33.33,Grassland,3.0,3.0,Omnivore,Omnivore,Terrestrial,4.06,77.73,53.86,4.61,35118904.89,Extant,passeri
1,Eremophila alpestris,Eremophila,Alaudidae,C:/Users/Camilo/Documents/Mis Documentos/Traba...,13.9,9.2,4.2,5.0,23.5,108.1,41.7,66.2,38.6,71.4,33.33,Grassland,3.0,3.0,Omnivore,Omnivore,Terrestrial,4.06,77.73,53.86,4.61,35118904.89,Extant,passeri
2,Eremophila alpestris,Eremophila,Alaudidae,C:/Users/Camilo/Documents/Mis Documentos/Traba...,13.9,9.2,4.2,5.0,23.5,108.1,41.7,66.2,38.6,71.4,33.33,Grassland,3.0,3.0,Omnivore,Omnivore,Terrestrial,4.06,77.73,53.86,4.61,35118904.89,Extant,passeri
3,Eremophila alpestris,Eremophila,Alaudidae,C:/Users/Camilo/Documents/Mis Documentos/Traba...,13.9,9.2,4.2,5.0,23.5,108.1,41.7,66.2,38.6,71.4,33.33,Grassland,3.0,3.0,Omnivore,Omnivore,Terrestrial,4.06,77.73,53.86,4.61,35118904.89,Extant,passeri
4,Eremophila alpestris,Eremophila,Alaudidae,C:/Users/Camilo/Documents/Mis Documentos/Traba...,13.9,9.2,4.2,5.0,23.5,108.1,41.7,66.2,38.6,71.4,33.33,Grassland,3.0,3.0,Omnivore,Omnivore,Terrestrial,4.06,77.73,53.86,4.61,35118904.89,Extant,passeri

In [10]:
df_merge.Suborder.nunique()

2

In [11]:
df_merge = df_merge[['Suborder', 'Path']]

In [21]:
df_sample = df_merge.groupby('Suborder').sample(n=250, random_state=42).reset_index(drop=True)
df_sample = df_sample.rename(columns={'Suborder': 'label', 'Path': 'audio_path'})
df_sample['label'] = df_sample['label'].apply(lambda x: 1 if x == 'passeri' else 0)

In [22]:
df_sample

     label                                         audio_path
0        1  C:/Users/Camilo/Documents/Mis Documentos/Traba...
1        1  C:/Users/Camilo/Documents/Mis Documentos/Traba...
2        1  C:/Users/Camilo/Documents/Mis Documentos/Traba...
3        1  C:/Users/Camilo/Documents/Mis Documentos/Traba...
4        1  C:/Users/Camilo/Documents/Mis Documentos/Traba...
..     ...                                                ...
495      0  C:/Users/Camilo/Documents/Mis Documentos/Traba...
496      0  C:/Users/Camilo/Documents/Mis Documentos/Traba...
497      0  C:/Users/Camilo/Documents/Mis Documentos/Traba...
498      0  C:/Users/Camilo/Documents/Mis Documentos/Traba...
499      0  C:/Users/Camilo/Documents/Mis Documentos/Traba...

[500 rows x 2 columns]

In [24]:
df_sample.to_csv('C:/Users/Camilo/Documents/Mis Documentos/Trabajo de grado/notebooks/data/data_suborder_ludwig.csv', index=False)

In [ ]:
#

* Realizar una base de datos estratificada a nivel de familia