In [ ]:
import sys
from pathlib import Path

project_root = Path().resolve().parent
sys.path.append(str(project_root))

from src.incertidumbres import (
    graficar_imagen,
    crear_dataframe_incertidumbre,
    plot_incertidumbres,
    plot_combinado
)

from src.image_preprocessor import (
    ImagePreprocessor
)

from src.model_trainer import ModelTrainer
from src.image_preprocessor import ImagePreprocessor
import pickle
import pandas as pd
import tensorflow as tf

/Users/camcortes/Documents/birds-sounds/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
model_name = "EfficientNetV2L" #"MobileNetV3Large" #"EfficientNetV2L" #"ResNet152V2" #"EfficientNetB7"

model_trainer = ModelTrainer(
    model_name=model_name,
    img_shape=(128, 256, 1),
    n_classes=667,
    dropout_rate=0.3,
    label_smoothing=0.1,
    fine_tune_layers=200
)

model = model_trainer.create_model()
model.summary()
model.load_weights(f"./models/weights_{model_name}.weights.h5")
tf.keras.backend.clear_session()

Model: "EfficientNetV2L_classifier"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 128, 256, 1)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda (Lambda)                 │ (None, 128, 256, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ preprocess_input (Lambda)       │ (None, 128, 256, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ efficientnetv2-l (Functional)   │ (None, 1280)           │   117,746,848 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ top_dropout (Dropout)           │ (None, 1280)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ logits (Dense)                  │ (None, 667)            │       854,427 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 118,601,275 (452.43 MB)

 Trainable params: 55,177,211 (210.48 MB)

 Non-trainable params: 63,424,064 (241.94 MB)

/Users/camcortes/Documents/birds-sounds/.venv/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 354 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [3]:
with open(f'./models/label_encoder_{model_name}.pkl', 'rb') as f:
    label_encoder = pickle.load(f)

In [6]:
preprocessor = ImagePreprocessor(label_encoder=label_encoder)
data = preprocessor.load_data_from_directory("/Users/camcortes/Documents/birds-sounds/src/data/images_test/images_spectograms")
data.head()

,label,image_path
0,Acropternis orthonyx,/Users/camcortes/Documents/birds-sounds/src/data/images_test/images_spectograms/Acropternis orthonyx/121142_13.jpeg
1,Acropternis orthonyx,/Users/camcortes/Documents/birds-sounds/src/data/images_test/images_spectograms/Acropternis orthonyx/511703_5.jpeg
2,Acropternis orthonyx,/Users/camcortes/Documents/birds-sounds/src/data/images_test/images_spectograms/Acropternis orthonyx/461011_0.jpeg
3,Acropternis orthonyx,/Users/camcortes/Documents/birds-sounds/src/data/images_test/images_spectograms/Acropternis orthonyx/621780_9.jpeg
4,Acropternis orthonyx,/Users/camcortes/Documents/birds-sounds/src/data/images_test/images_spectograms/Acropternis orthonyx/428484_0.jpeg

In [7]:
import random
from tqdm import tqdm

def especie_batch(data):
    species = list(set(data["label"]))
    num_species = len(species)
    for i, specie in enumerate(tqdm(species, desc=f"Especies procesadas")):
        print(f"\nEspecie {i+1} de {(num_species)}, ({specie})")
        yield specie

def specie_ds(data, gen):
    try:
        specie = next(gen)
        df = data[data["label"] == specie]
        if df.empty:
            print(f"No more species")
            return None, None
    except StopIteration:
        return None, None
    return specie, preprocessor.create_validation_dataset(df)

In [8]:
import matplotlib.pyplot as plt
import numpy as np

def calcular_incertidumbre(dataset_espectrogramas, modelo):
    predicciones_mc = []
    confianzas_mc = []

    etiqueta_real_lista =[]
    etiqueta_inferencia_lista = []

    if dataset_espectrogramas:
        for imagenes_batch, etiquetas_batch in dataset_espectrogramas.take(1):
            num_imagenes = len(imagenes_batch)

            # MONTE CARLO DROPOUT: Múltiples pasadas con training=True
            for idx in range(num_imagenes):
                imagen = imagenes_batch[idx]
                # Añadir una dimensión de batch (necesario para la inferencia)
                imagen_batch = tf.expand_dims(imagen, axis=0)
                etiqueta_real = tf.argmax(etiquetas_batch[idx])

                etiqueta_real_lista.append(etiqueta_real.numpy())

                #for iteracion in range(5):
                logits = modelo(imagen_batch)
                probabilidades = tf.nn.softmax(logits, axis=-1).numpy()
                clase_predicha = np.argmax(probabilidades, axis=-1)[0]
                confianza = probabilidades[0, clase_predicha]

                predicciones_mc.append(clase_predicha)
                confianzas_mc.append(confianza)

                # Predicción convencional (sin dropout activo)
                logits_inferencia = modelo(imagen_batch, training=False)
                probabilidades_inferencia = tf.nn.softmax(logits_inferencia, axis=-1).numpy()
                clase_predicha_inferencia = np.argmax(probabilidades_inferencia, axis=-1)[0]
                confianza_inferencia = probabilidades_inferencia[0, clase_predicha_inferencia]

                etiqueta_inferencia_lista.append(clase_predicha_inferencia)

                #print(f"\nClase real: {etiqueta_real}")
                #print(f"Clase predicha (modo inferencia): {clase_predicha_inferencia}")
                #print(f"Confianza (modo inferencia): {confianza_inferencia:.4f} ({confianza_inferencia*100:.2f}%)")

            # Si se desea mostrar la imagen:
            # plt.imshow(imagen.numpy().squeeze(), cmap='inferno')
            # plt.title(f"Predicha: {clase_predicha_inferencia} (Inferencia)")
            # plt.axis('off')
            # plt.show()

    return predicciones_mc, confianzas_mc, etiqueta_inferencia_lista, etiqueta_real_lista

In [11]:
dataset_generado = especie_batch(data)

resultados = {}
for i in range(data["label"].nunique()):
    especie, dataset_especie = specie_ds(data, dataset_generado)
    predicciones_mc, confianzas_mc, clase_predicha_inferencia, etiqueta_real = calcular_incertidumbre(dataset_especie, model)
    resultados[especie] = {
        "clase_real": etiqueta_real,
        "clase_predicha_inferencia": clase_predicha_inferencia,
        "predicciones_mc": predicciones_mc,
        "confianzas_mc": confianzas_mc,
    }

Especies procesadas:  97%|█████████▋| 644/667 [14:36:55<13:48, 36.03s/it]

Especie 645 de 667, (Psarocolius decumanus)

Especies procesadas:  97%|█████████▋| 645/667 [14:37:44<14:33, 39.73s/it]

Especie 646 de 667, (Ara ararauna)

Especies procesadas:  97%|█████████▋| 646/667 [14:38:29<14:33, 41.58s/it]

Especie 647 de 667, (Sclateria naevia)

Especies procesadas:  97%|█████████▋| 647/667 [14:39:17<14:28, 43.45s/it]

Especie 648 de 667, (Pheugopedius coraya)

Especies procesadas:  97%|█████████▋| 648/667 [14:40:01<13:45, 43.43s/it]

Especie 649 de 667, (Hemitriccus granadensis)

Especies procesadas:  97%|█████████▋| 649/667 [14:40:22<11:02, 36.79s/it]

Especie 650 de 667, (Dives warczewiczi)

Especies procesadas:  97%|█████████▋| 650/667 [14:40:54<10:01, 35.39s/it]

Especie 651 de 667, (Andigena nigrirostris)

Especies procesadas:  98%|█████████▊| 651/667 [14:41:30<09:28, 35.56s/it]

Especie 652 de 667, (Phlegopsis nigromaculata)

Especies procesadas:  98%|█████████▊| 652/667 [14:42:01<08:34, 34.32s/it]

Especie 653 de 667, (Saltator atripennis)

Especies procesadas:  98%|█████████▊| 653/667 [14:42:29<07:31, 32.28s/it]

Especie 654 de 667, (Cyphorhinus arada)

Especies procesadas:  98%|█████████▊| 654/667 [14:43:12<07:40, 35.44s/it]

Especie 655 de 667, (Pseudocolaptes boissonneautii)

Especies procesadas:  98%|█████████▊| 655/667 [14:43:23<05:37, 28.10s/it]

Especie 656 de 667, (Arremonops conirostris)

Especies procesadas:  98%|█████████▊| 656/667 [14:44:06<05:58, 32.61s/it]

Especie 657 de 667, (Grallaria flavotincta)

Especies procesadas:  99%|█████████▊| 657/667 [14:44:39<05:27, 32.73s/it]

Especie 658 de 667, (Rhytipterna simplex)

Especies procesadas:  99%|█████████▊| 658/667 [14:45:09<04:46, 31.80s/it]

Especie 659 de 667, (Sicalis citrina)

Especies procesadas:  99%|█████████▉| 659/667 [14:45:32<03:53, 29.21s/it]

Especie 660 de 667, (Automolus rufipileatus)

Especies procesadas:  99%|█████████▉| 660/667 [14:46:06<03:36, 30.86s/it]

Especie 661 de 667, (Pheugopedius spadix)

Especies procesadas:  99%|█████████▉| 661/667 [14:46:23<02:39, 26.66s/it]

Especie 662 de 667, (Sphenopsis melanotis)

Especies procesadas:  99%|█████████▉| 662/667 [14:46:38<01:55, 23.07s/it]

Especie 663 de 667, (Tachycineta bicolor)

Especies procesadas:  99%|█████████▉| 663/667 [14:47:22<01:57, 29.49s/it]

Especie 664 de 667, (Hemitriccus margaritaceiventer)

Especies procesadas: 100%|█████████▉| 664/667 [14:48:08<01:43, 34.40s/it]

Especie 665 de 667, (Hylophylax naevioides)

Especies procesadas: 100%|█████████▉| 665/667 [14:48:43<01:08, 34.41s/it]

Especie 666 de 667, (Tangara velia)

Especies procesadas: 100%|█████████▉| 666/667 [14:48:57<00:28, 28.22s/it]

Especie 667 de 667, (Grallaricula lineifrons)

In [12]:
labels = list(set(data["label"]))
labels.sort()

In [14]:
df = pd.DataFrame(resultados)
print(df.shape)
df.iloc[::1].head(2)

(4, 667)

,Conirostrum bicolor,Legatus leucophaius,Empidonax traillii,Pheugopedius sclateri,Synallaxis gujanensis,Lipaugus vociferans,Psarocolius bifasciatus,Stelgidopteryx ruficollis,Attila spadiceus,Xenops rutilans,Thamnophilus unicolor,Phylloscartes gualaquizae,Cnemotriccus fuscatus,Scytalopus chocoensis,Euphonia xanthogaster,Machetornis rixosa,Xiphocolaptes promeropirhynchus,Contopus cinereus,Quiscalus mexicanus,Drymophila striaticeps,Conopias parvus,Euphonia fulvicrissa,Gymnopithys leucaspis,Ramphastos tucanus,Sphenopsis frontalis,Pheugopedius genibarbis,Spinus magellanicus,Coryphospingus pileatus,Hellmayrea gularis,Cyanerpes caeruleus,Mimus gilvus,Scytalopus opacus,Dendroma rufa,Diglossa albilatera,Cissopis leverianus,Clytoctantes alixii,Dendrocolaptes picumnus,Formicarius colma,Schiffornis aenea,Henicorhina anachoreta,Myrmotherula brachyura,Empidonomus varius,Phyllomyias griseiceps,Scytalopus latrans,Pyriglena maura,Microcerculus bambla,Arremon brunneinucha,Cacicus haemorrhous,Myiophobus phoenicomitra,Cinnycerthia unirufa,Sublegatus modestus,Grallaria dignissima,Grallaria saturata,Sipia berlepschi,Cyphorhinus thoracicus,Myrmotherula multostriata,Thripadectes flammulatus,Sciaphylax castanea,Piprites chloris,Drymophila hellmayri,Microbates cinereiventris,Euphonia plumbea,Attila torridus,Saltator maximus,Myrmotherula ignota,Anairetes parulus,Diglossa caerulescens,Isleria guttata,Brotogeris jugularis,Ploceus cucullatus,Mionectes oleagineus,Pheugopedius rutilus,Myrmoborus leucophrys,Dichrozona cincta,Leistes militaris,Todirostrum cinereum,Tolmomyias flaviventris,Platyrinchus platyrhynchos,Euphonia chlorotica,Thamnophilus tenuepunctatus,Contopus sordidulus,Myrmotherula menetriesii,Pachyramphus polychopterus,Pseudotriccus ruficeps,Cercomacroides tyrannina,Chrysomus icterocephalus,Ceratopipra erythrocephala,Nephelomyias pulcher,Ramphocelus carbo,Pheugopedius mystacalis,Rhegmatorhina melanosticta,Schiffornis turdina,Sipia palliata,Diglossa gloriosissima,Empidonax minimus,Clibanornis rubiginosus,Scytalopus stilesi,Epinecrophylla fulviventris,Cranioleuca hellmayri,Myrmotherula longicauda,Querula purpurata,Thamnophilus schistaceus,Xenops minutus,Iridosornis porphyrocephalus,Stelgidopteryx serripennis,Atlapetes albofrenatus,Pygochelidon cyanoleuca,Hemithraupis guira,Ramphotrigon ruficauda,Phyllomyias burmeisteri,Asemospiza fuliginosa,Molothrus oryzivorus,Thamnophilus aethiops,Zonotrichia capensis,Leptopogon amaurocephalus,Ramphotrigon megacephalum,Atlapetes leucopterus,Dendroplex picus,Todirostrum nigriceps,Campylorhynchus griseus,Elaenia pallatangae,Grallaricula nana,Elaenia cristata,Chamaeza campanisona,Lophotriccus pileatus,Stilpnia larvata,Tangara arthus,Euscarthmus meloryphus,Stigmatura napensis,Syndactyla subalaris,Attila cinnamomeus,Myiophobus flavicans,Rupicola peruvianus,Myiopagis viridicata,Thripadectes holostictus,Coryphospingus cucullatus,Vireo flavifrons,Nemosia pileata,Icterus cayanensis,Vireo gilvus,Elaenia chiriquensis,Cercomacra cinerascens,Tachycineta thalassina,Neoctantes niger,Melanerpes formicivorus,Sicalis flaveola,Myrmotherula pacifica,Herpsilochmus rufimarginatus,Tangara labradorides,Pheugopedius fasciatoventris,Euphonia chrysopasta,Chlorospingus semifuscus,Cymbilaimus lineatus,Loriotus cristatus,Cranioleuca erythrops,Elaenia frantzii,Scytalopus atratus,Sipia nigricauda,Chlorornis riefferii,Diglossa cyanea,Synallaxis candei,Grallaria squamigera,Hylophilus semicinereus,Icterus galbula,Daptrius ater,Perissocephalus tricolor,Atlapetes flaviceps,Sericossypha albocristata,Stilpnia vitriolina,Myiodynastes chrysocephalus,Pteroglossus castanotis,Sporophila corvina,Bombycilla cedrorum,Cyanocorax yncas,Atlapetes melanocephalus,Thamnomanes ardesiacus,Campylorhamphus procurvoides,Euphonia minuta,Elaenia flavogaster,Sclerurus albigularis,Sporophila funerea,Lepidocolaptes souleyetii,Tachycineta albilinea,Thamnomanes caesius,Vireo masteri,Anabacerthia variegaticeps,Progne subis,Contopus cooperi,Vireo flavoviridis,Phoenicircus nigricollis,Pachysylvia muscicapina,Hylopezus macularius,Willisornis poecilinotus,Thamnophilus atrinucha,Elaenia spectabilis,Odontorchilus branickii,Leistes bellicosus,Campylorhynchus zonatus,Empidonax alnorum,Synallaxis rutilans,Tangara nigroviridis,Conopias cinchoneti,Ochthoeca cinnamomeiventris,Liosceles thoracicus,Myrmotherula longipennis,Poecilotriccus ruficeps,Epinecrophylla spodionota,Cantorchilus leucotis,Grallaria bangsi,Amblycercus holosericeus,Percnostola rufifrons,Cyanerpes cyaneus,Emberizoides herbicola,Thraupis episcopus,Hylocichla mustelina,Pheugopedius euophrys,Clibanornis rufipectus,Sporophila luctuosa,Grallaricula ferrugineipectus,Melanospiza bicolor,Picumnus exilis,Dysithamnus leucostictus,Megarynchus pitangua,Scytalopus micropterus,Corythopis torquatus,Sclerurus caudacutus,Mecocerculus stictopterus,Euphonia concinna,Procnias averano,Psarocolius angustifrons,Platyrinchus mystaceus,Sipia laemosticta,Formicivora grisea,Catharus ustulatus,Myiarchus crinitus,Euphonia laniirostris,Dendrocolaptes certhia,Leptopogon rufipectus,Myrmelastes leucostigma,Manacus manacus,Sporophila castaneiventris,Hylopezus fulviventris,Psarocolius viridis,Sporophila nigricollis,Cantorchilus leucopogon,Catamblyrhynchus diadema,Taraba major,Arremon assimilis,Myiotheretes fumigatus,Arremon taciturnus,Certhiaxis cinnamomeus,Thamnophilus murinus,Hemitriccus zosterops,Myiopagis flavivertex,Glyphorynchus spirurus,Pachyramphus albogriseus,Spizella pallida,Grallaricula flavirostris,Falco peregrinus,Saltator grossus,Riparia riparia,Cercomacroides serva,Furnarius leucopus,Atlapetes leucopis,Synallaxis albescens,Pyriglena leuconota,Ammodramus aurifrons,Dendrocolaptes sanctithomae,Cranioleuca vulpina,Cyclarhis gujanensis,Myiarchus cephalotes,Polioptila plumbea,Schiffornis veraepacis,Snowornis subalaris,Xiphorhynchus obsoletus,Tyrannus tyrannus,Asthenes wyatti,Pipreola riefferii,Rhodinocichla rosea,Scytalopus latebricola,Machaeropterus regulus,Grallaria varia,Cercomacroides nigrescens,Myiopagis gaimardii,Myrmotherula axillaris,Stilpnia heinei,Hypocnemis hypoxantha,Sittasomus griseicapillus,Xiphorhynchus lachrymosus,Dysithamnus mentalis,Zonotrichia leucophrys,Ammodramus humeralis,Thamnophilus doliatus,Quiscalus lugubris,Phacellodomus rufifrons,Buthraupis montana,Fluvicola nengeta,Leptopogon superciliaris,Inezia caudata,Contopus virens,Rhynchocyclus olivaceus,Anisognathus igniventris,Hirundinea ferruginea,Saltator coerulescens,Conopophaga castaneiceps,Ochthoeca fumicolor,Passerculus sandwichensis,Chlorophanes spiza,Cyclarhis nigrirostris,Formicarius nigricapillus,Todirostrum pictum,Laniocera hypopyrra,Dysithamnus puncticeps,Myrmothera campanisona,Mecocerculus leucophrys,Microcerculus marginatus,Cyanolyca armillata,Myiodynastes maculatus,Ornithion inerme,Passer domesticus,Myrmeciza longipes,Myrmoborus lugubris,Tolmomyias assimilis,Myiarchus tyrannulus,Elaenia parvirostris,Dacnis cayana,Frederickena fulva,Cyphorhinus phaeocephalus,Cacicus uropygialis,Neopelma chrysocephalum,Asemospiza obscura,Automolus ochrolaemus,Cacicus oseryi,Phaenostictus mcleannani,Thraupis palmarum,Cistothorus platensis,Vireo olivaceus,Icterus croconotus,Tersina viridis,Spinus olivaceus,Campylorhynchus turdinus,Automolus melanopezus,Troglodytes solstitialis,Pachysylvia decurtata,Cacicus solitarius,Icterus nigrogularis,Euphonia mesochrysa,Synallaxis cinnamomea,Sporophila caerulescens,Synallaxis cherriei,Tachycineta albiventer,Hylophilus flavipes,Neopipo cinnamomea,Atlapetes pallidinucha,Lathrotriccus euleri,Todirostrum chrysocrotaphum,Capsiempis flaveola,Poliocrania exsul,Henicorhina negreti,Catharus aurantiirostris,Chlorospingus canigularis,Campylorhamphus pusillus,Icterus mesomelas,Selenidera reinwardtii,Sakesphorus canadensis,Grallaria haplonota,Mionectes striaticollis,Nasica longirostris,Rupicola rupicola,Thamnophilus punctatus,Vireolanius leucotis,Philydor erythrocercum,Premnoplex brunnescens,Cyanocorax affinis,Capito auratus,Chlorospingus flavigularis,Atlapetes latinuchus,Lophotriccus vitiosus,Myiophobus roraimae,Asthenes fuliginosa,Xiphorhynchus erythropygius,Dubusia taeniata,Henicorhina leucosticta,Piculus flavigula,Sporophila plumbea,Aulacorhynchus albivitta,Chamaeza nobilis,Chlorophonia cyanocephala,Thamnophilus amazonicus,Tyrannus forficatus,Eremophila alpestris,Saltator striatipectus,Vireo philadelphicus,Camptostoma obsoletum,Myiotheretes striaticollis,Ammodramus savannarum,Thlypopsis sordida,Diglossa indigotica,Myiarchus ferox,Arremon atricapillus,Atalotriccus pilaris,Ramphotrigon fuscicauda,Euphonia violacea,Grallaria milleri,Chlorophonia pyrrhophrys,Caracara plancus,Myiornis ecaudatus,Microrhopias quixensis,Sporophila telasco,Sporathraupis cyanocephala,Deconychura longicauda,Zimmerius chrysops,Myiozetetes luteiventris,Pyrrhomyias cinnamomeus,Eucometis penicillata,Myrmophylax atrothorax,Myiopagis subplacens,Arremon castaneiceps,Pittasoma rufopileatum,Thamnophilus nigrocinereus,Thripophaga fusciceps,Xiphorhynchus elegans,Xiphorhynchus susurrans,Tachyphonus rufus,Dendrocincla tyrannina,Asthenes flammulata,Grallaria rufula,Tyrannus dominicensis,Sturnella magna,Chlorospingus flavopectus,Cercomacroides fuscicauda,Phaeomyias murina,Tityra semifasciata,Sporophila lineola,Myiodynastes luteiventris,Cercomacra nigricans,Machaeropterus deliciosus,Mitrephanes phaeocercus,Dolichonyx oryzivorus,Stilpnia cyanicollis,Thamnistes anabatinus,Thryophilus rufalbus,Synallaxis albigularis,Myrmochanes hemileucus,Epinecrophylla ornata,Myrmoborus myotherinus,Myiozetetes similis,Hylophylax naevius,Vireo leucophrys,Elaenia albiceps,Gymnocichla nudiceps,Hypocnemis peruviana,Xiphorhynchus pardalotus,Euphonia rufiventris,Ixothraupis rufigula,Lepidothrix coronata,Pygiptila stellaris,Troglodytes aedon,Forpus conspicillatus,Automolus infuscatus,Chamaeza mollissima,Drymophila devillei,Grallaria nuchalis,Haplospiza rustica,Myiarchus tuberculifer,Chiroxiphia lanceolata,Tachyphonus delatrii,Cercomacroides parkeri,Cistothorus apolinari,Lamprospiza melanoleuca,Myadestes ralloides,Hylophilus olivaceus,Sclerurus guatemalensis,Conopophaga aurita,Progne tapera,Micrastur ruficollis,Hypocnemis flavescens,Thryophilus nicefori,Campylorhamphus trochilirostris,Ibycter americanus,Icterus chrysater,Synallaxis fuscorufa,Volatinia jacarina,Ramphocaenus melanurus,Vireo altiloquus,Poecilotriccus capitalis,Thlypopsis superciliaris,Synallaxis brachyura,Tyrannus niveigularis,Grallaria alleni,Icterus spurius,Gymnopithys bicolor,Sayornis nigricans,Cyanocorax violaceus,Schiffornis major,Formicarius analis,Synallaxis unirufa,Scytalopus spillmanni,Hemitriccus striaticollis,Pipreola arcuata,Xiphorhynchus guttatus,Campephilus melanoleucos,Scytalopus rodriguezi,Molothrus bonariensis,Anisognathus lacrymosus,Scytalopus perijanus,Myiophobus fasciatus,Myiotriccus ornatus,Pachyramphus cinnamomeus,Thripadectes virgaticeps,Stilpnia cayana,Xiphorhynchus triangularis,Scytalopus vicinior,Loriotus luctuosus,Diglossa lafresnayii,Diglossa humeralis,Sporophila schistacea,Inezia subflava,Thripadectes melanorhynchus,Petrochelidon pyrrhonota,Platyrinchus coronatus,Grallaria ruficapilla,Conopias albovittatus,Gymnopithys rufigula,Cranioleuca curtata,Pionus menstruus,Psarocolius wagleri,Dendrexetastes rufigula,Lochmias nematura,Coereba flaveola,Empidonax flaviventris,Diglossa glauca,Synallaxis azarae,Anabacerthia striaticollis,Todirostrum maculatum,Tunchiornis ochraceiceps,Empidonax virescens,Tangara chilensis,Hypocnemoides melanopogon,Lophotriccus galeatus,Tyrannopsis sulphurea,Anisognathus somptuosus,Vireo griseus,Pseudopipra pipra,Myiopagis caniceps,Microbates collaris,Cnipodectes subbrunneus,Dendrocincla fuliginosa,Pachyramphus minor,Milvago chimachima,Scytalopus sanctaemartae,Schistochlamys melanopis,Myrmelastes schistaceus,Cyanolyca turcosa,Ceratopipra mentalis,Scytalopus griseicollis,Myiornis atricapillus,Progne chalybea,Sclerurus rufigularis,Sclerurus obscurior,Cantorchilus nigricapillus,Hylophylax punctulatus,Kleinothraupis atropileus,Formicarius rufipectus,Acropternis orthonyx,Donacobius atricapilla,Sicalis luteola,Tyrannus savana,Cranioleuca gutturata,Colonia colonus,Oncostoma cinereigulare,Herpetotheres cachinnans,Lipaugus unirufus,Thamnophilus multistriatus,Pipraeidea melanonota,Pachysylvia hypoxantha,Thripadectes ignobilis,Henicorhina leucophrys,Chlorophonia cyanea,Attila citriniventris,Myrmornis torquata,Mazaria propinqua,Lipaugus weberi,Lanio fulvus,Myiozetetes cayanensis,Tangara parzudakii,Vireo chivi,Arremon aurantiirostris,Grallaria guatimalensis,Catharus minimus,Poecilotriccus sylvia,Tiaris olivaceus,Myiophobus cryptoxanthus,Cinclodes excelsior,Ramphocelus dimidiatus,Tolmomyias poliocephalus,Cacicus cela,Tyrannus melancholicus,Sporophila minuta,Atlapetes fuscoolivaceus,Celeus flavus,Conirostrum speciosum,Myornis senilis,Catharus fuscater,Oreothraupis arremonops,Chlorochrysa phoenicotis,Myrmotherula schisticolor,Dysithamnus occidentalis,Terenotriccus erythrurus,Cyanolyca pulchra,Atlapetes schistaceus,Dumetella carolinensis,Scytalopus alvarezlopezi,Melanopareia elegans,Conopias trivirgatus,Pseudotriccus pelzelni,Tangara gyrola,Hylophilus thoracicus,Attila bolivianus,Sclerurus mexicanus,Myrmotherula assimilis,Myrmelastes hyperythrus,Cinnycerthia olivascens,Grallaria quitensis,Hylopezus perspicillatus,Phyllomyias nigrocapillus,Tolmomyias sulphurescens,Isleria hauxwelli,Lepidocolaptes lacrymiger,Anthus rubescens,Cichlopsis leucogenys,Hirundo rustica,Anthus lutescens,Hemitriccus iohannis,Spinus psaltria,Automolus subulatus,Contopus fumigatus,Grallaria kaestneri,Sporophila angolensis,Epinecrophylla haematonota,Hemithraupis flavicollis,Pitangus sulphuratus,Catharus fuscescens,Tyranneutes stolzmanni,Psarocolius decumanus,Ara ararauna,Sclateria naevia,Pheugopedius coraya,Hemitriccus granadensis,Dives warczewiczi,Andigena nigrirostris,Phlegopsis nigromaculata,Saltator atripennis,Cyphorhinus arada,Pseudocolaptes boissonneautii,Arremonops conirostris,Grallaria flavotincta,Rhytipterna simplex,Sicalis citrina,Automolus rufipileatus,Pheugopedius spadix,Sphenopsis melanotis,Tachycineta bicolor,Hemitriccus margaritaceiventer,Hylophylax naevioides,Tangara velia,Grallaricula lineifrons

In [15]:
df = df.transpose()
df.sample(3)

,clase_real,clase_predicha_inferencia,predicciones_mc,confianzas_mc
Chlorospingus flavopectus,"[99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99]","[308, 104, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 18, 99, 100, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 10, 99, 99, 99, 99, 533, 99, 99, 99, 99, 99, 99, 35, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99]","[308, 28, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 18, 99, 100, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 10, 99, 99, 99, 99, 657, 99, 99, 99, 99, 99, 99, 35, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99]","[0.28253484, 0.30962414, 0.96790993, 0.9840513, 0.9540374, 0.9837335, 0.9934242, 0.9747457, 0.89134765, 0.983509, 0.9458998, 0.97345, 0.9762916, 0.9198865, 0.95463836, 0.7568146, 0.16095257, 0.8867246, 0.23766392, 0.98055696, 0.99542844, 0.95418864, 0.9932602, 0.97173697, 0.847373, 0.78974676, 0.93600583, 0.64909416, 0.60684663, 0.9820899, 0.9703948, 0.86731166, 0.2721231, 0.98612136, 0.90938115, 0.9620213, 0.8160574, 0.1483467, 0.975571, 0.91978425, 0.74158096, 0.9834773, 0.99753845, 0.96591705, 0.6391067, 0.92455035, 0.98513377, 0.44190785, 0.9971762, 0.97686464, 0.92952055, 0.9732519, 0.9532155, 0.9714585, 0.78453225, 0.97998327, 0.4518299, 0.9749833, 0.9022233, 0.9524117, 0.9429568, 0.9656315, 0.9870471, 0.9087125, 0.9564388, 0.9779824, 0.9994723, 0.99779654, 0.85001916, 0.9419082, 0.916338, 0.7744579, 0.95700914, 0.91563374, 0.9954591]"
Phaenostictus mcleannani,"[418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418]","[418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418]","[418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 237, 418, 418, 418, 418, 418, 418, 418]","[0.9789883, 0.99753076, 0.98116714, 0.97698087, 0.963138, 0.9997135, 0.9976076, 0.41768336, 0.91581607, 0.9371754, 0.98054147, 0.9869473, 0.97952694, 0.986225, 0.9283937, 0.92534786, 0.9942842, 0.7430329, 0.98633426, 0.95645195, 0.9609241, 0.9840883, 0.98140633, 0.9823683, 0.15373181, 0.96592385, 0.9745247, 0.9429615, 0.965474, 0.9622338, 0.9858941, 0.9618403]"
Cantorchilus leucopogon,"[64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64]","[64, 64, 64, 336, 64, 64, 64, 64, 64, 64, 299, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 451, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64]","[64, 64, 64, 336, 64, 64, 64, 64, 64, 64, 299, 260, 64, 64, 64, 64, 64, 64, 64, 64, 64, 500, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64]","[0.9400944, 0.81525445, 0.8653094, 0.39862508, 0.9961224, 0.9921829, 0.65019816, 0.9995733, 0.99259335, 0.16925041, 0.57195127, 0.38863337, 0.9985208, 0.8911292, 0.7926331, 0.95740646, 0.94080365, 0.99962115, 0.52083385, 0.99121463, 0.99796605, 0.24087706, 0.98446953, 0.9744984, 0.93599313, 0.95677936, 0.401013, 0.75320476, 0.9540767, 0.62821287, 0.38149303, 0.97394806, 0.9941203, 0.98815405, 0.8575385]"

In [16]:
def calcular_proporcion(row):
    real = set(row['clase_real'])
    predicha = set(row['predicciones_mc'])

    # Elementos comunes entre ambas listas
    elementos_comunes = len(real.intersection(predicha))

    # Total de elementos únicos en clase_real
    total_elementos_real = len(real)

    # Calcula la proporción (evitando división por cero)
    if total_elementos_real > 0:
        return elementos_comunes / total_elementos_real
    else:
        return 0

# Aplicar la función a cada fila para crear la nueva columna
df['proporcion_coincidencia'] = df.apply(calcular_proporcion, axis=1)

# Si quieres expresarla como porcentaje
df['porcentaje_coincidencia'] = df['proporcion_coincidencia'] * 100

In [19]:
df.sample(3)

,clase_real,clase_predicha_inferencia,predicciones_mc,confianzas_mc,proporcion_coincidencia,porcentaje_coincidencia
Attila cinnamomeus,"[38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38]","[38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 443, 38, 38, 38, 38, 38, 173, 650, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 335, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 274, 38, 38, 38, 38, 38, 38, 38, 38]","[38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 443, 38, 38, 38, 38, 38, 173, 650, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 335, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 652, 38, 38, 38, 38, 38, 38, 38, 38]","[0.95261365, 0.9305934, 0.97200835, 0.9693832, 0.93993586, 0.90508103, 0.9483218, 0.9071486, 0.91027445, 0.85074615, 0.95901996, 0.59696525, 0.9412112, 0.7957336, 0.87349707, 0.9757204, 0.9203449, 0.9162803, 0.48308507, 0.910654, 0.9821147, 0.9740363, 0.9616561, 0.89686596, 0.9734759, 0.99908924, 0.9704325, 0.9775264, 0.9139094, 0.91274434, 0.9543904, 0.93983865, 0.9489267, 0.7238349, 0.96289384, 0.98275405, 0.94360787, 0.98129076, 0.9728742, 0.5112396, 0.9331584, 0.9924886, 0.50548774, 0.097549856, 0.97387165, 0.9246421, 0.8856968, 0.78360116, 0.87468827, 0.8018969, 0.9256215, 0.8494971, 0.50004697, 0.9158426, 0.5971613, 0.8375748, 0.94509804, 0.9934257, 0.3126503, 0.91146845, 0.9105256, 0.8169531, 0.84709454, 0.28828284, 0.95786893, 0.9583147, 0.2467548, 0.96393746, 0.59641373, 0.7020411, 0.90136504, 0.984363, 0.94457436, 0.91967463, 0.9146748]",1.00,100.00
Sipia laemosticta,"[530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530]","[380, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 560, 530, 148, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530]","[409, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 560, 530, 148, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530, 530]","[0.28483278, 0.967447, 0.9626155, 0.972982, 0.97960633, 0.98107076, 0.99735093, 0.96789885, 0.87866616, 0.99380726, 0.9515299, 0.9764389, 0.99728084, 0.97678214, 0.999461, 0.96243304, 0.97351396, 0.90893316, 0.98437136, 0.96375144, 0.9971208, 0.99529797, 0.9775857, 0.96969056, 0.12700328, 0.9897078, 0.48015502, 0.9976419, 0.9876409, 0.7225641, 0.9500993, 0.9786673, 0.99254453, 0.97822565, 0.99005497, 0.9208368, 0.94439113, 0.99174786, 0.9840776, 0.98714674, 0.89838123, 0.9780828, 0.999759, 0.9827849, 0.9919991, 0.9761386, 0.9620443, 0.88128144, 0.9676283, 0.96163154, 0.98962295, 0.95145947, 0.6941033, 0.99135405]",1.00,100.00
Tyrannus savana,"[638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638]","[638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 494, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 303, 638, 638, 638, 638, 638, 638]","[638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 3, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 638, 303, 638, 638, 638, 638, 638, 638]","[0.9871738, 0.9239484, 0.92452484, 0.84486985, 0.8852404, 0.9645868, 0.96691287, 0.80633694, 0.9805602, 0.9311587, 0.98146445, 0.9963242, 0.9653841, 0.970519, 0.13105614, 0.9839827, 0.9847157, 0.9739344, 0.9340983, 0.8753735, 0.91406775, 0.9518717, 0.9847112, 0.9329915, 0.97467333, 0.83680964, 0.16023454, 0.94168997, 0.9251448, 0.6852924, 0.9671715, 0.9194938, 0.93714744]",1.00,100.00

In [23]:
df.to_csv("/Users/camcortes/Documents/birds-sounds/src/data/incertidumbres_EfficentNetV2L.csv")