# Notes

In [1]:
import os
import pandas as pd

from src.data_engineering import process_features

In [2]:
# Obtener la ruta del directorio raíz
root_dir = os.path.abspath(os.path.join(os.getcwd(), '..'))

In [ ]:
familias = os.listdir('songs/')
familias.sort()
for familia in familias:
    print(f'Procesando familia: {familia}')

    generos_path = f'songs/{familia}/'
    generos = os.listdir(generos_path)
    generos.sort()
    for genero in generos:
        print(f'\tProcesando género: {genero}')

        especies_path = f'{generos_path}{genero}/'
        especies = os.listdir(especies_path)
        #especies.sort()
        for especie in especies:
            #print(f'\t\tProcesando especie: {especie}')

            name_comun_path = f'{especies_path}{especie}/'
            name_comuns = os.listdir(name_comun_path)
            for name_comun in name_comuns:
                ruta_base = f'{name_comun_path}{name_comun}'
                #print(f'\t\t\tRuta base: {ruta_base}')

                nombre_archivo = f"./notebooks/data/{familia}_{genero}_{especie}.csv"
                if not os.path.exists(nombre_archivo):
                    print(f'\t\t\tRuta base: {ruta_base}')
                    process_features(
                    f"{ruta_base}/",
                    "./notebooks/data/"
                    f"{familia}_{genero}_{especie}"
                    )
                else:
                    #pass
                    print(f'El archivo {nombre_archivo} ya existe, saltando procesamiento.')

In [4]:
# process_features(
#     "songs/Alaudidae/Eremophila/Eremophila alpestris/HornedLark/",
#     "./data/"
#     "ElegantWoodcreeper"
# )

In [4]:
import time
ruta_features = 'notebooks/data/'
archivos_csv = os.listdir(ruta_features)
dfs = []
start_time = time.time()

for archivo_csv in archivos_csv:
    # Extraer familia, género y especie del nombre del archivo
    partes_nombre = archivo_csv.split('_')
    familia = partes_nombre[0]
    genero = partes_nombre[1]
    especie = '_'.join(partes_nombre[2:]).replace('.csv', '')  # Asume que el nombre de la especie puede tener guiones bajos

    df = pd.read_csv(os.path.join(ruta_features, archivo_csv))
    # Agregar las columnas con la información extraída
    df['Familia'] = familia
    df['Genero'] = genero
    df['Especie'] = especie

    dfs.append(df)
    end_time = time.time()

print(f"Tiempo transcurrido: {end_time - start_time} segundos")

Tiempo transcurrido: 55.52996516227722 segundos

In [5]:
df_final = pd.concat(dfs, ignore_index=True)
df_final.to_csv('src/data/data_tabular/species_features.csv', index=False)

In [6]:
df = pd.read_csv('src/data/data_tabular/species_features.csv')
print(df.shape)
df.head(3)

CPU times: user 1e+03 ns, sys: 0 ns, total: 1e+03 ns
Wall time: 2.86 μs
(40276, 4820)

,track_index,autocorrelation_kurtosis_01,autocorrelation_max_01,autocorrelation_mean_01,autocorrelation_median_01,autocorrelation_min_01,autocorrelation_skew_01,autocorrelation_std_01,chroma_cens_kurtosis_01,chroma_cens_kurtosis_02,...,zcr_kurtosis_01,zcr_max_01,zcr_mean_01,zcr_median_01,zcr_min_01,zcr_skew_01,zcr_std_01,Familia,Genero,Especie
0,17242,79384.546875,9948.958984,0.002224,-0.000002,-6745.563965,66.996178,19.026342,-0.465705,0.369771,...,2.710036,0.287598,0.152835,0.151855,0.096191,0.567153,0.018813,Thamnophilidae,Pithys,Pithys albifrons
1,61448,11766.333008,2616.639648,0.097834,0.058590,-2535.653564,3.391762,12.506159,0.881887,0.257165,...,1.005324,0.437988,0.211480,0.214844,0.130859,-0.247902,0.031412,Thamnophilidae,Pithys,Pithys albifrons
2,61611,73002.781250,2198.963379,0.026946,-0.000043,-1292.112427,84.082329,3.907068,-0.157645,0.109866,...,1.409501,0.405762,0.157406,0.152832,0.087402,0.652681,0.027775,Thamnophilidae,Pithys,Pithys albifrons

In [7]:
tyranni = [
    'Philepittidae', 'Eurylaimidae', 'Calyptomenidae', 'Sapayoidae', 'Pittidae',
    'Pipridae', 'Cotingidae', 'Tityridae', 'Tyrannidae', 'Melanopareiidae', 'Conopophagidae',
    'Thamnophilidae', 'Grallariidae', 'Rhinocryptidae', 'Formicariidae', 'Furnariidae', "Onychorhynchidae",
]

passeri = [
        'Menuridae', 'Atrichornithidae', 'Climacteridae', 'Maluridae', 'Meliphagidae', 'Pardalotidae',
        'Petroicidae', 'Orthonychidae', 'Pomatostomidae', 'Cinclosomatidae', 'Neosittidae',
        'Pachycephalidae', 'Dicruridae', 'Oriolidae', 'Artamidae', 'Paradisaeidae', 'Corvidae',
        'Cyanocorax', 'Corcoracidae', 'Irenidae', 'Laniidae', 'Vireonidae', 'Ptilonorhynchidae',
        'Turnagridae', 'Callaeidae', 'Alaudidae', 'Chloropseidae', 'Aegithinidae', 'Picathartidae',
        'Bombycillidae', 'Ptilogonatidae', 'Cinclidae', 'Motacillidae', 'Prunellidae', 'Melanocharitidae',
        'Paramythiidae', 'Passeridae', 'Estrildidae', 'Ploceidae', 'Parulidae', 'Thraupidae',
        'Peucedramidae', 'Fringillidae', 'Cardinalidae', 'Drepanididae', 'Emberizidae', 'Nectariniidae',
        'Dicaeidae', 'Mimidae', 'Sittidae', 'Certhiidae', 'Troglodytidae', 'Polioptilidae', 'Paridae',
        'Aegithalidae', 'Hirundinidae', 'Regulidae', 'Pycnonotidae', 'Sylviidae', 'Acrocephalidae',
        'Locustellidae', 'Cettiidae', 'Phylloscopidae', 'Cisticolidae', 'Hypocoliidae', 'Zosteropidae',
        'Paradoxornithidae', 'Timaliidae', 'Leiothrichidae', 'Muscicapidae', 'Turdidae', 'Sturnidae',
        'Icteridae', "Passerellidae", "Donacobiidae", "Mitrospingidae", "Rhodinocichlidae"
]

In [8]:
def suborder(row):
    if row['Familia'] in tyranni:
        return 'Tyranni'
    elif row['Familia'] in passeri:
        return 'Passeri'
    else:
        return 'No definido'

In [9]:
df['Suborder'] = df.apply(suborder, axis=1)

In [10]:
df.head(3)

,track_index,autocorrelation_kurtosis_01,autocorrelation_max_01,autocorrelation_mean_01,autocorrelation_median_01,autocorrelation_min_01,autocorrelation_skew_01,autocorrelation_std_01,chroma_cens_kurtosis_01,chroma_cens_kurtosis_02,...,zcr_max_01,zcr_mean_01,zcr_median_01,zcr_min_01,zcr_skew_01,zcr_std_01,Familia,Genero,Especie,Suborder
0,17242,79384.546875,9948.958984,0.002224,-0.000002,-6745.563965,66.996178,19.026342,-0.465705,0.369771,...,0.287598,0.152835,0.151855,0.096191,0.567153,0.018813,Thamnophilidae,Pithys,Pithys albifrons,Tyranni
1,61448,11766.333008,2616.639648,0.097834,0.058590,-2535.653564,3.391762,12.506159,0.881887,0.257165,...,0.437988,0.211480,0.214844,0.130859,-0.247902,0.031412,Thamnophilidae,Pithys,Pithys albifrons,Tyranni
2,61611,73002.781250,2198.963379,0.026946,-0.000043,-1292.112427,84.082329,3.907068,-0.157645,0.109866,...,0.405762,0.157406,0.152832,0.087402,0.652681,0.027775,Thamnophilidae,Pithys,Pithys albifrons,Tyranni

In [11]:
# Contar el número de registros por suborder
df.groupby("Suborder").size()

Suborder
No definido     2479
Passeri        18340
Tyranni        19457
dtype: int64

In [12]:
df[df['Suborder'] == 'No definido']["Familia"].unique()

array(['Psittacidae', 'Grallaridae', 'Falconidae', 'Capitonidae',
       'Rhamphastidae', 'Picidae'], dtype=object)

In [14]:
df.to_csv('src/data/data_tabular/species_features_tabular.csv', index=False)