In [1]:
import pandas as pd
import utils
import taxonomia

pd.set_option('display.max_columns', None)

In [2]:
archivo_excel = 'ruta/al/archivo.xlsx'
avonet1 = pd.read_excel("./data_total/AVONET Supplementary dataset 1.xlsx", sheet_name='AVONET1_BirdLife')
df = pd.read_csv("./data_total/data_specie.csv")

In [3]:
avonet1 = avonet1[avonet1['Order1'] == 'Passeriformes']
avonet1['Species1'] = avonet1['Species1'].str.replace(" ", "_")
avonet1 = avonet1.drop(columns=['Sequence', 'Family1', 'Order1', 'Avibase.ID1', 'Total.individuals', 'Female', 'Male', 'Unknown', 'Complete.measures', 'Mass.Source', 'Mass.Refs.Other', 
                                'Inference', 'Traits.inferred', 'Reference.species'])
avonet1.head(3)

,Species1,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-Wing.Index,Tail.Length,Mass,Habitat,Habitat.Density,Migration,Trophic.Level,Trophic.Niche,Primary.Lifestyle,Min.Latitude,Max.Latitude,Centroid.Latitude,Centroid.Longitude,Range.Size
2794,Acanthisitta_chloris,12.1,6.3,2.4,2.2,18.0,46.0,6.2,38.1,13.9,23.5,6.91,Forest,1,1.0,Carnivore,Invertivore,Insessorial,-47.28,-35.38,-42.25,172.19,152503.84
2795,Xenicus_gilviventris,13.8,7.7,3.9,3.3,23.2,49.0,8.1,40.0,16.8,13.3,17.59,Shrubland,2,1.0,Carnivore,Invertivore,Generalist,-46.07,-41.01,-43.99,169.31,11157.46
2796,Acanthiza_apicalis,11.0,5.9,2.2,2.6,19.0,51.0,7.2,43.2,14.2,44.1,7.62,Woodland,2,1.0,Carnivore,Invertivore,Insessorial,-36.00,-16.78,-27.63,131.95,4124270.80

In [4]:
species_avonet = avonet1['Species1'].unique()
species_df = df['Specie'].unique()

In [5]:
Species_no_encontradas = [species for species in species_df if species not in species_avonet]
len(Species_no_encontradas)

37

In [6]:
Species_no_encontradas[0]

'Chalcothraupis_ruficervix'

In [7]:
avonet1[avonet1['Species1'].str.contains('vitriolina', case=False, na=False)]

,Species1,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-Wing.Index,Tail.Length,Mass,Habitat,Habitat.Density,Migration,Trophic.Level,Trophic.Niche,Primary.Lifestyle,Min.Latitude,Max.Latitude,Centroid.Latitude,Centroid.Longitude,Range.Size
8300,Tangara_vitriolina,12.2,7.7,5.9,5.8,20.4,73.1,14.8,56.1,20.9,57.3,23.0,Shrubland,2,1.0,Omnivore,Frugivore,Insessorial,-0.14,8.39,4.43,-75.52,123913.11

In [8]:
#avonet1['Species1'] = avonet1['Species1'].str.replace("Tangara_vitriolina", "Stilpnia_vitriolina")

In [9]:
df, avonet1 = utils.sinonimias(df, avonet1)

In [10]:
print(f'Nuestra base de datos tiene {len(species_df)} Species')
print(f'La base de datos AVONET tiene {len(species_avonet)} Species')

Nuestra base de datos tiene 992 Species
La base de datos AVONET tiene 6614 Species

In [11]:
avonet1 = avonet1.rename(columns={'Species1': 'Specie'})

In [12]:
df_merge = pd.merge(df, avonet1, how="left", on=["Specie", "Specie"])

In [13]:
df_merge[avonet1.columns].head(3)

,Specie,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-Wing.Index,Tail.Length,Mass,Habitat,Habitat.Density,Migration,Trophic.Level,Trophic.Niche,Primary.Lifestyle,Min.Latitude,Max.Latitude,Centroid.Latitude,Centroid.Longitude,Range.Size
0,Acropternis_orthonyx,22.9,10.4,4.5,6.5,36.4,94.8,5.2,89.9,5.5,88.9,89.86,Forest,1.0,1.0,Carnivore,Invertivore,Insessorial,-5.46,9.74,1.60,-76.74,112912.00
1,Agriornis_albicauda,32.4,18.6,7.0,8.6,39.7,141.3,35.2,106.0,24.9,113.1,53.00,Shrubland,3.0,1.0,Carnivore,Vertivore,Insessorial,-27.47,0.00,-15.22,-71.16,579914.07
2,Agriornis_montanus,30.4,17.4,5.8,5.7,33.1,131.3,33.0,98.2,25.1,98.2,63.30,Shrubland,3.0,1.0,Carnivore,Omnivore,Insessorial,-50.11,2.51,-30.52,-68.63,2168659.57

In [14]:
avonet3 = pd.read_excel("./data_total/AVONET Supplementary dataset 1.xlsx", sheet_name='AVONET3_BirdTree')

In [15]:

avonet3 = avonet3[avonet3['Order3'] == 'Passeriformes']
avonet3['Species3'] = avonet3['Species3'].str.replace(" ", "_")
avonet3 = avonet3[['Species3','Species.Status', ]]
print(avonet3.shape)
avonet3.head(3)

(5966, 2)

                  Species3 Species.Status
2612  Acanthisitta_chloris         Extant
2613  Xenicus_gilviventris         Extant
2614    Acanthiza_apicalis         Extant

In [16]:
avonet3 = avonet3.rename(columns={'Species3': 'Species1'})
df_merge, avonet3 = utils.sinonimias(df_merge, avonet3)

In [17]:
avonet3 = avonet3.rename(columns={'Species1': 'Specie'})
df_merge = pd.merge(df_merge, avonet3, how="left", on=["Specie", "Specie"])

In [18]:
#crea una columna llamada genus haciendo split de la columna Specie
df_merge['Genus'] = df_merge['Specie'].str.split("_").str[0]

In [19]:
familia = taxonomia.capitalize_family_genus(taxonomia.genus_family)
df_merge['Family'] = df_merge['Genus'].map(familia)
df_merge['Suborder'] = df_merge['Family'].map(taxonomia.suborder)

In [20]:
print(df_merge.shape)
df_merge.head(3)

(992, 399)

,Specie,chroma_cens_kurtosis_01,chroma_cens_kurtosis_02,chroma_cens_kurtosis_03,chroma_cens_kurtosis_04,chroma_cens_kurtosis_05,chroma_cens_kurtosis_06,chroma_cens_kurtosis_07,chroma_cens_kurtosis_08,chroma_cens_kurtosis_09,chroma_cens_max_01,chroma_cens_max_02,chroma_cens_max_03,chroma_cens_max_04,chroma_cens_max_05,chroma_cens_max_06,chroma_cens_max_07,chroma_cens_max_08,chroma_cens_max_09,chroma_cens_max_10,chroma_cens_max_11,chroma_cens_max_12,chroma_cens_mean_01,chroma_cens_mean_02,chroma_cens_mean_03,chroma_cens_mean_04,chroma_cens_mean_05,chroma_cens_mean_06,chroma_cens_mean_07,chroma_cens_mean_08,chroma_cens_mean_09,chroma_cens_mean_10,chroma_cens_mean_11,chroma_cens_mean_12,chroma_cens_median_01,chroma_cens_median_02,chroma_cens_median_03,chroma_cens_median_04,chroma_cens_median_05,chroma_cens_median_06,chroma_cens_median_07,chroma_cens_median_08,chroma_cens_median_09,chroma_cens_median_10,chroma_cens_median_11,chroma_cens_median_12,chroma_cens_min_01,chroma_cens_min_02,chroma_cens_min_03,chroma_cens_min_04,chroma_cens_min_05,chroma_cens_min_06,chroma_cens_min_07,chroma_cens_min_08,chroma_cens_min_09,chroma_cens_min_10,chroma_cens_min_11,chroma_cens_min_12,chroma_cens_skew_01,chroma_cens_skew_02,chroma_cens_skew_03,chroma_cens_skew_04,chroma_cens_skew_05,chroma_cens_skew_06,chroma_cens_skew_07,chroma_cens_skew_08,chroma_cens_skew_09,chroma_cens_std_01,chroma_cens_std_02,chroma_cens_std_03,chroma_cens_std_04,chroma_cens_std_05,chroma_cens_std_06,chroma_cens_std_07,chroma_cens_std_08,chroma_cens_std_09,chroma_cens_std_10,chroma_cens_std_11,chroma_cens_std_12,chroma_cqt_kurtosis_01,chroma_cqt_kurtosis_02,chroma_cqt_kurtosis_03,chroma_cqt_kurtosis_04,chroma_cqt_kurtosis_05,chroma_cqt_kurtosis_06,chroma_cqt_kurtosis_07,chroma_cqt_kurtosis_08,chroma_cqt_kurtosis_09,chroma_cqt_kurtosis_10,chroma_cqt_kurtosis_11,chroma_cqt_kurtosis_12,chroma_cqt_max_01,chroma_cqt_max_02,chroma_cqt_max_03,chroma_cqt_max_04,chroma_cqt_max_05,chroma_cqt_max_06,chroma_cqt_max_07,chroma_cqt_max_08,chroma_cqt_max_09,chroma_cqt_max_10,chroma_cqt_max_11,chroma_cqt_max_12,chroma_cqt_mean_01,chroma_cqt_mean_02,chroma_cqt_mean_03,chroma_cqt_mean_04,chroma_cqt_mean_05,chroma_cqt_mean_06,chroma_cqt_mean_07,chroma_cqt_mean_08,chroma_cqt_mean_09,chroma_cqt_mean_10,chroma_cqt_mean_11,chroma_cqt_mean_12,chroma_cqt_median_01,chroma_cqt_median_02,chroma_cqt_median_03,chroma_cqt_median_04,chroma_cqt_median_05,chroma_cqt_median_06,chroma_cqt_median_07,chroma_cqt_median_08,chroma_cqt_median_09,chroma_cqt_median_10,chroma_cqt_median_11,chroma_cqt_median_12,chroma_cqt_min_01,chroma_cqt_min_02,chroma_cqt_min_03,chroma_cqt_min_04,chroma_cqt_min_05,chroma_cqt_min_06,chroma_cqt_min_07,chroma_cqt_min_08,chroma_cqt_min_09,chroma_cqt_min_10,chroma_cqt_min_11,chroma_cqt_min_12,chroma_cqt_skew_01,chroma_cqt_skew_02,chroma_cqt_skew_03,chroma_cqt_skew_04,chroma_cqt_skew_05,chroma_cqt_skew_06,chroma_cqt_skew_07,chroma_cqt_skew_08,chroma_cqt_skew_09,chroma_cqt_skew_10,chroma_cqt_skew_11,chroma_cqt_skew_12,chroma_cqt_std_01,chroma_cqt_std_02,chroma_cqt_std_03,chroma_cqt_std_04,chroma_cqt_std_05,chroma_cqt_std_06,chroma_cqt_std_07,chroma_cqt_std_08,chroma_cqt_std_09,chroma_cqt_std_10,chroma_cqt_std_11,chroma_cqt_std_12,chroma_stft_kurtosis_01,chroma_stft_kurtosis_02,chroma_stft_kurtosis_03,chroma_stft_kurtosis_04,chroma_stft_kurtosis_05,chroma_stft_kurtosis_06,chroma_stft_kurtosis_07,chroma_stft_kurtosis_08,chroma_stft_kurtosis_09,chroma_stft_kurtosis_10,chroma_stft_kurtosis_11,chroma_stft_kurtosis_12,chroma_stft_max_01,chroma_stft_max_02,chroma_stft_max_03,chroma_stft_max_04,chroma_stft_max_05,chroma_stft_max_06,chroma_stft_max_07,chroma_stft_max_08,chroma_stft_max_09,chroma_stft_max_10,chroma_stft_max_11,chroma_stft_max_12,chroma_stft_mean_01,chroma_stft_mean_02,chroma_stft_mean_03,chroma_stft_mean_04,chroma_stft_mean_05,chroma_stft_mean_06,chroma_stft_mean_07,chroma_stft_mean_08,chroma_stft_mean_09,chroma_stft_mean_10,chroma_stft_mean_11,chroma_stft_mean_12,chroma_stft_median_01,chroma_stft_median_02,chroma_stft_median_03,chroma_stft_median_04,chroma_stft_median_05,chroma_stft_median_06,chroma_stft_median_07,chroma_stft_median_08,chroma_stft_median_09,chroma_stft_median_10,chroma_stft_median_11,chroma_stft_median_12,chroma_stft_min_01,chroma_stft_min_02,chroma_stft_min_03,chroma_stft_min_04,chroma_stft_min_05,chroma_stft_min_06,chroma_stft_min_07,chroma_stft_min_08,chroma_stft_min_09,chroma_stft_min_10,chroma_stft_min_11,chroma_stft_min_12,chroma_stft_skew_01,chroma_stft_skew_02,chroma_stft_skew_03,chroma_stft_skew_04,chroma_stft_skew_05,chroma_stft_skew_06,chroma_stft_skew_07,chroma_stft_skew_08,chroma_stft_skew_09,chroma_stft_skew_10,chroma_stft_skew_11,chroma_stft_skew_12,chroma_stft_std_01,chroma_stft_std_02,chroma_stft_std_03,chroma_stft_std_04,chroma_stft_std_05,chroma_stft_std_06,chroma_stft_std_07,chroma_stft_std_08,chroma_stft_std_09,chroma_stft_std_10,chroma_stft_std_11,chroma_stft_std_12,rmse_kurtosis_01,rmse_max_01,rmse_mean_01,rmse_median_01,rmse_min_01,rmse_skew_01,rmse_std_01,spectral_bandwidth_kurtosis_01,spectral_bandwidth_max_01,spectral_bandwidth_mean_01,spectral_bandwidth_median_01,spectral_bandwidth_min_01,spectral_bandwidth_skew_01,spectral_bandwidth_std_01,spectral_centroid_kurtosis_01,spectral_centroid_max_01,spectral_centroid_mean_01,spectral_centroid_median_01,spectral_centroid_min_01,spectral_centroid_skew_01,spectral_centroid_std_01,spectral_contrast_kurtosis_01,spectral_contrast_kurtosis_02,spectral_contrast_kurtosis_03,spectral_contrast_kurtosis_04,spectral_contrast_kurtosis_05,spectral_contrast_kurtosis_06,spectral_contrast_kurtosis_07,spectral_contrast_max_01,spectral_contrast_max_02,spectral_contrast_max_03,spectral_contrast_max_04,spectral_contrast_max_05,spectral_contrast_max_06,spectral_contrast_max_07,spectral_contrast_mean_01,spectral_contrast_mean_02,spectral_contrast_mean_03,spectral_contrast_mean_04,spectral_contrast_mean_05,spectral_contrast_mean_06,spectral_contrast_mean_07,spectral_contrast_median_01,spectral_contrast_median_02,spectral_contrast_median_03,spectral_contrast_median_04,spectral_contrast_median_05,spectral_contrast_median_06,spectral_contrast_median_07,spectral_contrast_min_01,spectral_contrast_min_02,spectral_contrast_min_03,spectral_contrast_min_04,spectral_contrast_min_05,spectral_contrast_min_06,spectral_contrast_min_07,spectral_contrast_skew_01,spectral_contrast_skew_02,spectral_contrast_skew_03,spectral_contrast_skew_04,spectral_contrast_skew_05,spectral_contrast_skew_06,spectral_contrast_skew_07,spectral_contrast_std_01,spectral_contrast_std_02,spectral_contrast_std_03,spectral_contrast_std_04,spectral_contrast_std_05,spectral_contrast_std_06,spectral_contrast_std_07,spectral_rolloff_kurtosis_01,spectral_rolloff_max_01,spectral_rolloff_mean_01,spectral_rolloff_median_01,spectral_rolloff_min_01,spectral_rolloff_skew_01,spectral_rolloff_std_01,tonnetz_kurtosis_01,tonnetz_kurtosis_02,tonnetz_kurtosis_03,tonnetz_kurtosis_04,tonnetz_kurtosis_05,tonnetz_kurtosis_06,tonnetz_max_01,tonnetz_max_02,tonnetz_max_03,tonnetz_max_04,tonnetz_max_05,tonnetz_max_06,tonnetz_mean_01,tonnetz_mean_02,tonnetz_mean_03,tonnetz_mean_04,tonnetz_mean_05,tonnetz_mean_06,tonnetz_median_01,tonnetz_median_02,tonnetz_median_03,tonnetz_median_04,tonnetz_median_05,tonnetz_median_06,tonnetz_min_01,tonnetz_min_02,tonnetz_min_03,tonnetz_min_04,tonnetz_min_05,tonnetz_min_06,tonnetz_skew_01,tonnetz_skew_02,tonnetz_skew_03,tonnetz_skew_04,tonnetz_skew_05,tonnetz_skew_06,tonnetz_std_01,tonnetz_std_02,tonnetz_std_03,tonnetz_std_04,tonnetz_std_05,tonnetz_std_06,zcr_kurtosis_01,zcr_max_01,zcr_mean_01,zcr_median_01,zcr_min_01,zcr_skew_01,zcr_std_01,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-Wing.Index,Tail.Length,Mass,Habitat,Habitat.Density,Migration,Trophic.Level,Trophic.Niche,Primary.Lifestyle,Min.Latitude,Max.Latitude,Centroid.Latitude,Centroid.Longitude,Range.Size,Species.Status,Genus,Family,Suborder
0,Acropternis_orthonyx,0.001471,0.007027,0.010283,0.004517,0.003856,0.001506,0.000723,0.000912,0.002066,0.648805,0.780883,0.663126,0.551339,0.438560,0.390459,0.376038,0.373493,0.352783,0.339950,0.364230,0.418704,0.380927,0.488973,0.385909,0.352912,0.253815,0.240446,0.206878,0.226549,0.211372,0.175691,0.194284,0.181324,0.350505,0.426024,0.377120,0.362586,0.254581,0.243424,0.214476,0.235386,0.215080,0.178882,0.198423,0.176428,0.119356,0.236279,0.164361,0.096330,0.057728,0.037007,0.028495,0.028722,0.023756,0.021995,0.021273,0.030672,0.102680,0.206678,0.234551,0.539433,0.458215,0.093098,0.058285,0.072497,0.073833,0.290299,0.318862,0.267050,0.243572,0.245347,0.219827,0.198302,0.213141,0.196763,0.195879,0.191179,0.190474,0.000629,0.001407,0.000343,0.000724,0.000734,0.000588,0.000257,0.000162,0.000223,0.000550,0.000906,0.001893,1.000000,1.000000,1.0,1.0,0.986494,0.974727,0.973353,0.969530,0.959500,0.958637,0.957238,0.967041,0.593296,0.684723,0.608010,0.570342,0.472685,0.411446,0.405389,0.402830,0.387714,0.377450,0.376614,0.367997,0.595944,0.710317,0.612082,0.582421,0.472024,0.403424,0.397697,0.395814,0.380578,0.371523,0.369764,0.352547,0.042418,0.082851,0.055358,0.043476,0.030027,0.021366,0.019394,0.019045,0.016319,0.012623,0.013908,0.018036,0.373350,0.427082,0.673697,0.625991,0.494511,0.164735,0.302230,0.283995,0.178357,0.154616,0.232630,0.153087,0.569113,0.519638,0.563765,0.556395,0.525013,0.511016,0.480995,0.465266,0.446832,0.464897,0.463545,0.447854,0.000408,0.000647,0.000751,0.000354,0.000250,0.000184,0.000197,0.000152,0.000152,0.000663,0.000724,0.000373,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.999556,1.0,0.551524,0.568445,0.576008,0.576199,0.561331,0.544679,0.533019,0.526169,0.524307,0.523264,0.530222,0.535651,0.569082,0.586704,0.593233,0.592804,0.579222,0.565798,0.555886,0.552318,0.551168,0.550540,0.554477,0.555628,0.002370,0.003181,0.005444,0.006740,0.008764,0.007553,0.004466,0.002264,0.002244,0.002173,0.003070,0.002843,0.431620,0.510384,0.519611,0.260727,0.217509,0.254743,0.207015,0.183811,0.261895,0.315445,0.300053,0.424517,0.605074,0.603867,0.575013,0.581415,0.589401,0.607541,0.598286,0.625531,0.621803,0.616264,0.578923,0.594830,0.007701,0.023056,0.030794,0.014795,0.001956,0.472892,0.037006,0.005799,0.487877,0.396409,0.429273,0.190194,0.447451,0.158081,0.006699,0.320833,0.222023,0.221001,0.108590,0.369187,0.100297,0.068470,0.112198,0.152880,0.038724,0.044872,0.043382,0.017986,0.378847,0.293476,0.329044,0.372922,0.289274,0.356522,0.659636,0.302163,0.223749,0.194647,0.110251,0.074428,0.118504,0.641271,0.298910,0.228707,0.189666,0.072010,0.058529,0.108055,0.640627,0.146734,0.166500,0.195842,0.197154,0.226881,0.179661,0.333640,0.493284,0.602316,0.623753,0.540403,0.587163,0.550012,0.641003,0.200771,0.085195,0.186235,0.237578,0.148769,0.129009,0.179045,0.003728,0.613160,0.368064,0.395108,0.096498,0.487640,0.207041,0.009099,0.006394,0.013637,0.014560,0.009013,0.010176,0.295009,0.304878,0.358638,0.459676,0.443844,0.320703,0.281380,0.532709,0.527748,0.465552,0.420959,0.321345,0.251095,0.486436,0.574344,0.440093,0.403861,0.325176,0.680794,0.686476,0.412624,0.513599,0.609311,0.320151,0.684396,0.183372,0.650663,0.728006,0.821681,0.702080,0.114772,0.128417,0.169831,0.190223,0.156245,0.163025,0.004543,0.301060,0.131440,0.130953,0.060814,0.335196,0.100959,22.9,10.4,4.5,6.5,36.4,94.8,5.2,89.9,5.5,88.9,89.86,Forest,1.0,1.0,Carnivore,Invertivore,Insessorial,-5.46,9.74,1.60,-76.74,112912.00,Extant,Acropternis,Rhinocryptidae,tiranni
1,Agriornis_albicauda,0.001132,0.003793,0.006593,0.003264,0.003602,0.003011,0.002900,0.004278,0.004896,0.382395,0.396291,0.492402,0.555568,0.473350,0.467723,0.462359,0.447528,0.417588,0.450097,0.410618,0.383529,0.224551,0.252463,0.273591,0.338166,0.282609,0.356559,0.316613,0.328987,0.286994,0.254432,0.244319,0.208685,0.209318,0.231174,0.265753,0.328230,0.272141,0.346990,0.318240,0.327644,0.276495,0.243580,0.239582,0.201697,0.107600,0.101624,0.080041,0.145951,0.147864,0.205883,0.170060,0.134710,0.085770,0.101908,0.114392,0.122225,0.102793,0.178931,0.224752,0.557495,0.471830,0.103103,0.070292,0.087586,0.085654,0.180796,0.177629,0.237913,0.227310,0.212837,0.187058,0.174414,0.203290,0.200749,0.223251,0.183656,0.155745,0.001155,0.002343,0.000543,0.000636,0.001255,0.002347,0.003710,0.002295,0.000946,0.000220,0.000386,0.000589,0.980475,0.977494,1.0,1.0,0.990813,1.000000,0.999241,0.996031,0.996052,0.992150,0.986384,0.983646,0.397548,0.400280,0.441671,0.531710,0.516146,0.556753,0.530548,0.498653,0.454098,0.463997,0.420394,0.390728,0.376301,0.378246,0.409643,0.505782,0.506615,0.573703,0.526269,0.483557,0.436811,0.448435,0.398893,0.363851,0.023271,0.039006,0.062892,0.074882,0.077334,0.072474,0.071364,0.055089,0.041662,0.027969,0.022902,0.027743,0.383558,0.445862,0.682551,0.633632,0.496842,0.169213,0.310127,0.291121,0.181923,0.152220,0.230840,0.148649,0.445851,0.424419,0.469586,0.497259,0.458357,0.464090,0.481772,0.492128,0.479898,0.525522,0.490677,0.456969,0.000329,0.000500,0.000587,0.000288,0.000204,0.000132,0.000161,0.000138,0.000150,0.000618,0.000694,0.000312,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,0.631054,0.622373,0.623398,0.631095,0.617851,0.617893,0.605864,0.601593,0.607308,0.611463,0.607937,0.617715,0.633943,0.625263,0.622952,0.633452,0.619857,0.621012,0.603581,0.595570,0.602919,0.605973,0.608872,0.619527,0.067891,0.074550,0.080535,0.048128,0.035505,0.016821,0.020482,0.017232,0.017272,0.022006,0.032851,0.064005,0.432654,0.512439,0.521835,0.262263,0.218328,0.255142,0.207899,0.184973,0.262595,0.316820,0.301391,0.425432,0.501650,0.496783,0.477877,0.491994,0.500462,0.517640,0.485934,0.495012,0.494692,0.508487,0.458862,0.479947,0.025185,0.016589,0.015231,0.007826,0.000012,0.505531,0.019085,0.018140,0.619991,0.554647,0.580349,0.280423,0.424148,0.162689,0.010224,0.475052,0.299735,0.295222,0.132072,0.363400,0.135510,0.055808,0.103419,0.125691,0.046891,0.037113,0.020545,0.020700,0.335153,0.256306,0.299808,0.199789,0.226284,0.202285,0.663857,0.287869,0.216740,0.239603,0.046064,0.058862,0.068738,0.671787,0.286415,0.223061,0.239179,0.037753,0.050001,0.062849,0.668154,0.160532,0.181733,0.237266,0.204267,0.241026,0.175708,0.414098,0.488348,0.590894,0.575126,0.518731,0.572908,0.521901,0.631659,0.199809,0.076188,0.179314,0.072783,0.100793,0.086374,0.166720,0.013600,0.800946,0.549654,0.578394,0.095746,0.471333,0.239392,0.005457,0.002771,0.006077,0.005868,0.004546,0.003932,0.267232,0.278493,0.338600,0.363829,0.309333,0.288960,0.293596,0.528885,0.568007,0.443048,0.382565,0.323573,0.261704,0.478201,0.598579,0.418383,0.373263,0.320487,0.715361,0.761377,0.579052,0.602927,0.624658,0.507711,0.681386,0.212595,0.691447,0.740137,0.794826,0.739502,0.100166,0.089130,0.085814,0.115431,0.097360,0.097958,0.003733,0.411529,0.172593,0.171226,0.101925,0.327314,0.125055,32.4,18.6,7.0,8.6,39.7,141.3,35.2,106.0,24.9,113.1,53.00,Shrubland,3.0,1.0,Carnivore,Vertivore,Insessorial,-27.47,0.00,-15.22,-71.16,579914.07,Extant,Agriornis,Tyrannidae,tiranni
2,Agriornis_montanus,0.002116,0.014413,0.019840,0.009525,0.005802,0.010294,0.012779,0.014382,0.010970,0.521195,0.678582,0.727320,0.633158,0.460323,0.361243,0.347295,0.386281,0.377767,0.395316,0.398350,0.378965,0.354515,0.453098,0.416843,0.386232,0.241711,0.220344,0.185753,0.219448,0.228542,0.204111,0.208134,0.195953,0.343202,0.414568,0.409309,0.378872,0.233819,0.213303,0.180580,0.214570,0.215623,0.191443,0.195887,0.187063,0.090179,0.194201,0.242609,0.169014,0.061041,0.037918,0.039313,0.051337,0.042054,0.048548,0.037606,0.039940,0.077234,0.196775,0.269169,0.563740,0.472250,0.124856,0.100263,0.111227,0.100099,0.204490,0.206964,0.233429,0.197979,0.214407,0.172977,0.160865,0.176892,0.174408,0.193935,0.195706,0.173644,0.000611,0.001608,0.000314,0.000622,0.001105,0.004567,0.004253,0.001579,0.000253,0.000667,0.000561,0.000641,1.000000,1.000000,1.0,1.0,0.989304,0.868362,0.886197,0.925152,0.905559,0.918310,0.949255,0.952759,0.577039,0.672492,0.668088,0.615391,0.463136,0.391418,0.379694,0.401353,0.417452,0.431941,0.410223,0.397322,0.565839,0.690670,0.663987,0.605313,0.447465,0.376615,0.356146,0.382120,0.400706,0.417118,0.384899,0.371004,0.046680,0.065757,0.083888,0.066037,0.037391,0.027319,0.027977,0.030116,0.025072,0.022237,0.015668,0.018609,0.375020,0.427898,0.673582,0.627870,0.497387,0.175696,0.312284,0.289592,0.178465,0.153599,0.231559,0.148036,0.523402,0.501091,0.512113,0.495440,0.443078,0.393422,0.388671,0.388836,0.393867,0.439397,0.455481,0.439122,0.000507,0.000885,0.001017,0.000469,0.000327,0.000215,0.000233,0.000176,0.000185,0.000824,0.001099,0.000468,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000,1.0,0.584666,0.608126,0.622827,0.621890,0.616005,0.606142,0.577764,0.559649,0.546052,0.564408,0.579613,0.571805,0.600094,0.628592,0.646400,0.638524,0.630072,0.619790,0.585617,0.558357,0.547642,0.575303,0.594432,0.583937,0.006699,0.007261,0.010305,0.013110,0.011548,0.009382,0.024494,0.019581,0.012549,0.007715,0.008488,0.011317,0.431134,0.509259,0.517826,0.259170,0.215577,0.253590,0.207256,0.185182,0.263119,0.315854,0.298011,0.424212,0.520630,0.535215,0.516374,0.515777,0.524135,0.538555,0.499063,0.513756,0.502272,0.509208,0.472256,0.495682,0.010628,0.019294,0.026198,0.020461,0.000032,0.484601,0.022654,0.009897,0.545560,0.447588,0.465894,0.279869,0.437159,0.118427,0.009346,0.409470,0.279569,0.270220,0.167659,0.361826,0.098320,0.060692,0.106094,0.134160,0.077662,0.071944,0.073510,0.013323,0.404808,0.305262,0.321104,0.290690,0.280852,0.267242,0.626574,0.302815,0.228409,0.200581,0.069740,0.052241,0.089487,0.598376,0.299972,0.233843,0.197728,0.059160,0.041609,0.088063,0.592531,0.154108,0.189054,0.221291,0.203873,0.235136,0.175771,0.328327,0.492913,0.601008,0.604204,0.576078,0.620707,0.558355,0.642803,0.214565,0.085279,0.163962,0.103736,0.107026,0.055560,0.199240,0.007664,0.710305,0.446184,0.455835,0.177878,0.482573,0.167226,0.010440,0.008064,0.018833,0.026549,0.013910,0.011871,0.293124,0.313009,0.372294,0.390498,0.370035,0.308938,0.285805,0.538227,0.549815,0.454850,0.395710,0.327874,0.254707,0.487527,0.582690,0.433548,0.385615,0.326723,0.697908,0.722547,0.510575,0.490096,0.559037,0.416298,0.690505,0.202076,0.682677,0.675680,0.776846,0.712963,0.097701,0.103183,0.095360,0.150283,0.117570,0.107339,0.006905,0.366439,0.179651,0.180056,0.087357,0.326708,0.103005,30.4,17.4,5.8,5.7,33.1,131.3,33.0,98.2,25.1,98.2,63.30,Shrubland,3.0,1.0,Carnivore,Omnivore,Insessorial,-50.11,2.51,-30.52,-68.63,2168659.57,Extant,Agriornis,Tyrannidae,tiranni

In [30]:
num_cols = df_merge.select_dtypes(include=['number'])
num_cols

,chroma_cens_kurtosis_01,chroma_cens_kurtosis_02,chroma_cens_kurtosis_03,chroma_cens_kurtosis_04,chroma_cens_kurtosis_05,chroma_cens_kurtosis_06,chroma_cens_kurtosis_07,chroma_cens_kurtosis_08,chroma_cens_kurtosis_09,chroma_cens_max_01,chroma_cens_max_02,chroma_cens_max_03,chroma_cens_max_04,chroma_cens_max_05,chroma_cens_max_06,chroma_cens_max_07,chroma_cens_max_08,chroma_cens_max_09,chroma_cens_max_10,chroma_cens_max_11,chroma_cens_max_12,chroma_cens_mean_01,chroma_cens_mean_02,chroma_cens_mean_03,chroma_cens_mean_04,chroma_cens_mean_05,chroma_cens_mean_06,chroma_cens_mean_07,chroma_cens_mean_08,chroma_cens_mean_09,chroma_cens_mean_10,chroma_cens_mean_11,chroma_cens_mean_12,chroma_cens_median_01,chroma_cens_median_02,chroma_cens_median_03,chroma_cens_median_04,chroma_cens_median_05,chroma_cens_median_06,chroma_cens_median_07,chroma_cens_median_08,chroma_cens_median_09,chroma_cens_median_10,chroma_cens_median_11,chroma_cens_median_12,chroma_cens_min_01,chroma_cens_min_02,chroma_cens_min_03,chroma_cens_min_04,chroma_cens_min_05,chroma_cens_min_06,chroma_cens_min_07,chroma_cens_min_08,chroma_cens_min_09,chroma_cens_min_10,chroma_cens_min_11,chroma_cens_min_12,chroma_cens_skew_01,chroma_cens_skew_02,chroma_cens_skew_03,chroma_cens_skew_04,chroma_cens_skew_05,chroma_cens_skew_06,chroma_cens_skew_07,chroma_cens_skew_08,chroma_cens_skew_09,chroma_cens_std_01,chroma_cens_std_02,chroma_cens_std_03,chroma_cens_std_04,chroma_cens_std_05,chroma_cens_std_06,chroma_cens_std_07,chroma_cens_std_08,chroma_cens_std_09,chroma_cens_std_10,chroma_cens_std_11,chroma_cens_std_12,chroma_cqt_kurtosis_01,chroma_cqt_kurtosis_02,chroma_cqt_kurtosis_03,chroma_cqt_kurtosis_04,chroma_cqt_kurtosis_05,chroma_cqt_kurtosis_06,chroma_cqt_kurtosis_07,chroma_cqt_kurtosis_08,chroma_cqt_kurtosis_09,chroma_cqt_kurtosis_10,chroma_cqt_kurtosis_11,chroma_cqt_kurtosis_12,chroma_cqt_max_01,chroma_cqt_max_02,chroma_cqt_max_03,chroma_cqt_max_04,chroma_cqt_max_05,chroma_cqt_max_06,chroma_cqt_max_07,chroma_cqt_max_08,chroma_cqt_max_09,chroma_cqt_max_10,chroma_cqt_max_11,chroma_cqt_max_12,chroma_cqt_mean_01,chroma_cqt_mean_02,chroma_cqt_mean_03,chroma_cqt_mean_04,chroma_cqt_mean_05,chroma_cqt_mean_06,chroma_cqt_mean_07,chroma_cqt_mean_08,chroma_cqt_mean_09,chroma_cqt_mean_10,chroma_cqt_mean_11,chroma_cqt_mean_12,chroma_cqt_median_01,chroma_cqt_median_02,chroma_cqt_median_03,chroma_cqt_median_04,chroma_cqt_median_05,chroma_cqt_median_06,chroma_cqt_median_07,chroma_cqt_median_08,chroma_cqt_median_09,chroma_cqt_median_10,chroma_cqt_median_11,chroma_cqt_median_12,chroma_cqt_min_01,chroma_cqt_min_02,chroma_cqt_min_03,chroma_cqt_min_04,chroma_cqt_min_05,chroma_cqt_min_06,chroma_cqt_min_07,chroma_cqt_min_08,chroma_cqt_min_09,chroma_cqt_min_10,chroma_cqt_min_11,chroma_cqt_min_12,chroma_cqt_skew_01,chroma_cqt_skew_02,chroma_cqt_skew_03,chroma_cqt_skew_04,chroma_cqt_skew_05,chroma_cqt_skew_06,chroma_cqt_skew_07,chroma_cqt_skew_08,chroma_cqt_skew_09,chroma_cqt_skew_10,chroma_cqt_skew_11,chroma_cqt_skew_12,chroma_cqt_std_01,chroma_cqt_std_02,chroma_cqt_std_03,chroma_cqt_std_04,chroma_cqt_std_05,chroma_cqt_std_06,chroma_cqt_std_07,chroma_cqt_std_08,chroma_cqt_std_09,chroma_cqt_std_10,chroma_cqt_std_11,chroma_cqt_std_12,chroma_stft_kurtosis_01,chroma_stft_kurtosis_02,chroma_stft_kurtosis_03,chroma_stft_kurtosis_04,chroma_stft_kurtosis_05,chroma_stft_kurtosis_06,chroma_stft_kurtosis_07,chroma_stft_kurtosis_08,chroma_stft_kurtosis_09,chroma_stft_kurtosis_10,chroma_stft_kurtosis_11,chroma_stft_kurtosis_12,chroma_stft_max_01,chroma_stft_max_02,chroma_stft_max_03,chroma_stft_max_04,chroma_stft_max_05,chroma_stft_max_06,chroma_stft_max_07,chroma_stft_max_08,chroma_stft_max_09,chroma_stft_max_10,chroma_stft_max_11,chroma_stft_max_12,chroma_stft_mean_01,chroma_stft_mean_02,chroma_stft_mean_03,chroma_stft_mean_04,chroma_stft_mean_05,chroma_stft_mean_06,chroma_stft_mean_07,chroma_stft_mean_08,chroma_stft_mean_09,chroma_stft_mean_10,chroma_stft_mean_11,chroma_stft_mean_12,chroma_stft_median_01,chroma_stft_median_02,chroma_stft_median_03,chroma_stft_median_04,chroma_stft_median_05,chroma_stft_median_06,chroma_stft_median_07,chroma_stft_median_08,chroma_stft_median_09,chroma_stft_median_10,chroma_stft_median_11,chroma_stft_median_12,chroma_stft_min_01,chroma_stft_min_02,chroma_stft_min_03,chroma_stft_min_04,chroma_stft_min_05,chroma_stft_min_06,chroma_stft_min_07,chroma_stft_min_08,chroma_stft_min_09,chroma_stft_min_10,chroma_stft_min_11,chroma_stft_min_12,chroma_stft_skew_01,chroma_stft_skew_02,chroma_stft_skew_03,chroma_stft_skew_04,chroma_stft_skew_05,chroma_stft_skew_06,chroma_stft_skew_07,chroma_stft_skew_08,chroma_stft_skew_09,chroma_stft_skew_10,chroma_stft_skew_11,chroma_stft_skew_12,chroma_stft_std_01,chroma_stft_std_02,chroma_stft_std_03,chroma_stft_std_04,chroma_stft_std_05,chroma_stft_std_06,chroma_stft_std_07,chroma_stft_std_08,chroma_stft_std_09,chroma_stft_std_10,chroma_stft_std_11,chroma_stft_std_12,rmse_kurtosis_01,rmse_max_01,rmse_mean_01,rmse_median_01,rmse_min_01,rmse_skew_01,rmse_std_01,spectral_bandwidth_kurtosis_01,spectral_bandwidth_max_01,spectral_bandwidth_mean_01,spectral_bandwidth_median_01,spectral_bandwidth_min_01,spectral_bandwidth_skew_01,spectral_bandwidth_std_01,spectral_centroid_kurtosis_01,spectral_centroid_max_01,spectral_centroid_mean_01,spectral_centroid_median_01,spectral_centroid_min_01,spectral_centroid_skew_01,spectral_centroid_std_01,spectral_contrast_kurtosis_01,spectral_contrast_kurtosis_02,spectral_contrast_kurtosis_03,spectral_contrast_kurtosis_04,spectral_contrast_kurtosis_05,spectral_contrast_kurtosis_06,spectral_contrast_kurtosis_07,spectral_contrast_max_01,spectral_contrast_max_02,spectral_contrast_max_03,spectral_contrast_max_04,spectral_contrast_max_05,spectral_contrast_max_06,spectral_contrast_max_07,spectral_contrast_mean_01,spectral_contrast_mean_02,spectral_contrast_mean_03,spectral_contrast_mean_04,spectral_contrast_mean_05,spectral_contrast_mean_06,spectral_contrast_mean_07,spectral_contrast_median_01,spectral_contrast_median_02,spectral_contrast_median_03,spectral_contrast_median_04,spectral_contrast_median_05,spectral_contrast_median_06,spectral_contrast_median_07,spectral_contrast_min_01,spectral_contrast_min_02,spectral_contrast_min_03,spectral_contrast_min_04,spectral_contrast_min_05,spectral_contrast_min_06,spectral_contrast_min_07,spectral_contrast_skew_01,spectral_contrast_skew_02,spectral_contrast_skew_03,spectral_contrast_skew_04,spectral_contrast_skew_05,spectral_contrast_skew_06,spectral_contrast_skew_07,spectral_contrast_std_01,spectral_contrast_std_02,spectral_contrast_std_03,spectral_contrast_std_04,spectral_contrast_std_05,spectral_contrast_std_06,spectral_contrast_std_07,spectral_rolloff_kurtosis_01,spectral_rolloff_max_01,spectral_rolloff_mean_01,spectral_rolloff_median_01,spectral_rolloff_min_01,spectral_rolloff_skew_01,spectral_rolloff_std_01,tonnetz_kurtosis_01,tonnetz_kurtosis_02,tonnetz_kurtosis_03,tonnetz_kurtosis_04,tonnetz_kurtosis_05,tonnetz_kurtosis_06,tonnetz_max_01,tonnetz_max_02,tonnetz_max_03,tonnetz_max_04,tonnetz_max_05,tonnetz_max_06,tonnetz_mean_01,tonnetz_mean_02,tonnetz_mean_03,tonnetz_mean_04,tonnetz_mean_05,tonnetz_mean_06,tonnetz_median_01,tonnetz_median_02,tonnetz_median_03,tonnetz_median_04,tonnetz_median_05,tonnetz_median_06,tonnetz_min_01,tonnetz_min_02,tonnetz_min_03,tonnetz_min_04,tonnetz_min_05,tonnetz_min_06,tonnetz_skew_01,tonnetz_skew_02,tonnetz_skew_03,tonnetz_skew_04,tonnetz_skew_05,tonnetz_skew_06,tonnetz_std_01,tonnetz_std_02,tonnetz_std_03,tonnetz_std_04,tonnetz_std_05,tonnetz_std_06,zcr_kurtosis_01,zcr_max_01,zcr_mean_01,zcr_median_01,zcr_min_01,zcr_skew_01,zcr_std_01,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-Wing.Index,Tail.Length,Mass,Habitat.Density,Migration,Min.Latitude,Max.Latitude,Centroid.Latitude,Centroid.Longitude,Range.Size
0,0.001471,0.007027,0.010283,0.004517,0.003856,0.001506,0.000723,0.000912,0.002066,0.648805,0.780883,0.663126,0.551339,0.438560,0.390459,0.376038,0.373493,0.352783,0.339950,0.364230,0.418704,0.380927,0.488973,0.385909,0.352912,0.253815,0.240446,0.206878,0.226549,0.211372,0.175691,0.194284,0.181324,0.350505,0.426024,0.377120,0.362586,0.254581,0.243424,0.214476,0.235386,0.215080,0.178882,0.198423,0.176428,0.119356,0.236279,0.164361,0.096330,0.057728,0.037007,0.028495,0.028722,0.023756,0.021995,0.021273,0.030672,0.102680,0.206678,0.234551,0.539433,0.458215,0.093098,0.058285,0.072497,0.073833,0.290299,0.318862,0.267050,0.243572,0.245347,0.219827,0.198302,0.213141,0.196763,0.195879,0.191179,0.190474,0.000629,0.001407,0.000343,0.000724,0.000734,0.000588,0.000257,0.000162,0.000223,0.000550,0.000906,0.001893,1.000000,1.000000,1.000000,1.000000,0.986494,0.974727,0.973353,0.969530,0.959500,0.958637,0.957238,0.967041,0.593296,0.684723,0.608010,0.570342,0.472685,0.411446,0.405389,0.402830,0.387714,0.377450,0.376614,0.367997,0.595944,0.710317,0.612082,0.582421,0.472024,0.403424,0.397697,0.395814,0.380578,0.371523,0.369764,0.352547,0.042418,0.082851,0.055358,0.043476,0.030027,0.021366,0.019394,0.019045,0.016319,0.012623,0.013908,0.018036,0.373350,0.427082,0.673697,0.625991,0.494511,0.164735,0.302230,0.283995,0.178357,0.154616,0.232630,0.153087,0.569113,0.519638,0.563765,0.556395,0.525013,0.511016,0.480995,0.465266,0.446832,0.464897,0.463545,0.447854,0.000408,0.000647,0.000751,0.000354,0.000250,0.000184,0.000197,0.000152,0.000152,0.000663,0.000724,0.000373,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.999556,1.000000,0.551524,0.568445,0.576008,0.576199,0.561331,0.544679,0.533019,0.526169,0.524307,0.523264,0.530222,0.535651,0.569082,0.586704,0.593233,0.592804,0.579222,0.565798,0.555886,0.552318,0.551168,0.550540,0.554477,0.555628,0.002370,0.003181,0.005444,0.006740,0.008764,0.007553,0.004466,0.002264,0.002244,0.002173,0.003070,0.002843,0.431620,0.510384,0.519611,0.260727,0.217509,0.254743,0.207015,0.183811,0.261895,0.315445,0.300053,0.424517,0.605074,0.603867,0.575013,0.581415,0.589401,0.607541,0.598286,0.625531,0.621803,0.616264,0.578923,0.594830,0.007701,0.023056,0.030794,0.014795,0.001956,0.472892,0.037006,0.005799,0.487877,0.396409,0.429273,0.190194,0.447451,0.158081,0.006699,0.320833,0.222023,0.221001,0.108590,0.369187,0.100297,0.068470,0.112198,0.152880,0.038724,0.044872,0.043382,0.017986,0.378847,0.293476,0.329044,0.372922,0.289274,0.356522,0.659636,0.302163,0.223749,0.194647,0.110251,0.074428,0.118504,0.641271,0.298910,0.228707,0.189666,0.072010,0.058529,0.108055,0.640627,0.146734,0.166500,0.195842,0.197154,0.226881,0.179661,0.333640,0.493284,0.602316,0.623753,0.540403,0.587163,0.550012,0.641003,0.200771,0.085195,0.186235,0.237578,0.148769,0.129009,0.179045,0.003728,0.613160,0.368064,0.395108,0.096498,0.487640,0.207041,0.009099,0.006394,0.013637,0.014560,0.009013,0.010176,0.295009,0.304878,0.358638,0.459676,0.443844,0.320703,0.281380,0.532709,0.527748,0.465552,0.420959,0.321345,0.251095,0.486436,0.574344,0.440093,0.403861,0.325176,0.680794,0.686476,0.412624,0.513599,0.609311,0.320151,0.684396,0.183372,0.650663,0.728006,0.821681,0.702080,0.114772,0.128417,0.169831,0.190223,0.156245,0.163025,0.004543,0.301060,0.131440,0.130953,0.060814,0.335196,0.100959,22.9,10.4,4.5,6.5,36.4,94.8,5.2,89.9,5.5,88.9,89.86,1.0,1.0,-5.46,9.74,1.60,-76.74,112912.00
1,0.001132,0.003793,0.006593,0.003264,0.003602,0.003011,0.002900,0.004278,0.004896,0.382395,0.396291,0.492402,0.555568,0.473350,0.467723,0.462359,0.447528,0.417588,0.450097,0.410618,0.383529,0.224551,0.252463,0.273591,0.338166,0.282609,0.356559,0.316613,0.328987,0.286994,0.254432,0.244319,0.208685,0.209318,0.231174,0.265753,0.328230,0.272141,0.346990,0.318240,0.327644,0.276495,0.243580,0.239582,0.201697,0.107600,0.101624,0.080041,0.145951,0.147864,0.205883,0.170060,0.134710,0.085770,0.101908,0.114392,0.122225,0.102793,0.178931,0.224752,0.557495,0.471830,0.103103,0.070292,0.087586,0.085654,0.180796,0.177629,0.237913,0.227310,0.212837,0.187058,0.174414,0.203290,0.200749,0.223251,0.183656,0.155745,0.001155,0.002343,0.000543,0.000636,0.001255,0.002347,0.003710,0.002295,0.000946,0.000220,0.000386,0.000589,0.980475,0.977494,1.000000,1.000000,0.990813,1.000000,0.999241,0.996031,0.996052,0.992150,0.986384,0.983646,0.397548,0.400280,0.441671,0.531710,0.516146,0.556753,0.530548,0.498653,0.454098,0.463997,0.420394,0.390728,0.376301,0.378246,0.409643,0.505782,0.506615,0.573703,0.526269,0.483557,0.436811,0.448435,0.398893,0.363851,0.023271,0.039006,0.062892,0.074882,0.077334,0.072474,0.071364,0.055089,0.041662,0.027969,0.022902,0.027743,0.383558,0.445862,0.682551,0.633632,0.496842,0.169213,0.310127,0.291121,0.181923,0.152220,0.230840,0.148649,0.445851,0.424419,0.469586,0.497259,0.458357,0.464090,0.481772,0.492128,0.479898,0.525522,0.490677,0.456969,0.000329,0.000500,0.000587,0.000288,0.000204,0.000132,0.000161,0.000138,0.000150,0.000618,0.000694,0.000312,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.631054,0.622373,0.623398,0.631095,0.617851,0.617893,0.605864,0.601593,0.607308,0.611463,0.607937,0.617715,0.633943,0.625263,0.622952,0.633452,0.619857,0.621012,0.603581,0.595570,0.602919,0.605973,0.608872,0.619527,0.067891,0.074550,0.080535,0.048128,0.035505,0.016821,0.020482,0.017232,0.017272,0.022006,0.032851,0.064005,0.432654,0.512439,0.521835,0.262263,0.218328,0.255142,0.207899,0.184973,0.262595,0.316820,0.301391,0.425432,0.501650,0.496783,0.477877,0.491994,0.500462,0.517640,0.485934,0.495012,0.494692,0.508487,0.458862,0.479947,0.025185,0.016589,0.015231,0.007826,0.000012,0.505531,0.019085,0.018140,0.619991,0.554647,0.580349,0.280423,0.424148,0.162689,0.010224,0.475052,0.299735,0.295222,0.132072,0.363400,0.135510,0.055808,0.103419,0.125691,0.046891,0.037113,0.020545,0.020700,0.335153,0.256306,0.299808,0.199789,0.226284,0.202285,0.663857,0.287869,0.216740,0.239603,0.046064,0.058862,0.068738,0.671787,0.286415,0.223061,0.239179,0.037753,0.050001,0.062849,0.668154,0.160532,0.181733,0.237266,0.204267,0.241026,0.175708,0.414098,0.488348,0.590894,0.575126,0.518731,0.572908,0.521901,0.631659,0.199809,0.076188,0.179314,0.072783,0.100793,0.086374,0.166720,0.013600,0.800946,0.549654,0.578394,0.095746,0.471333,0.239392,0.005457,0.002771,0.006077,0.005868,0.004546,0.003932,0.267232,0.278493,0.338600,0.363829,0.309333,0.288960,0.293596,0.528885,0.568007,0.443048,0.382565,0.323573,0.261704,0.478201,0.598579,0.418383,0.373263,0.320487,0.715361,0.761377,0.579052,0.602927,0.624658,0.507711,0.681386,0.212595,0.691447,0.740137,0.794826,0.739502,0.100166,0.089130,0.085814,0.115431,0.097360,0.097958,0.003733,0.411529,0.172593,0.171226,0.101925,0.327314,0.125055,32.4,18.6,7.0,8.6,39.7,141.3,35.2,106.0,24.9,113.1,53.00,3.0,1.0,-27.47,0.00,-15.22,-71.16,579914.07
2,0.002116,0.014413,0.019840,0.009525,0.005802,0.010294,0.012779,0.014382,0.010970,0.521195,0.678582,0.727320,0.633158,0.460323,0.361243,0.347295,0.386281,0.377767,0.395316,0.398350,0.378965,0.354515,0.453098,0.416843,0.386232,0.241711,0.220344,0.185753,0.219448,0.228542,0.204111,0.208134,0.195953,0.343202,0.414568,0.409309,0.378872,0.233819,0.213303,0.180580,0.214570,0.215623,0.191443,0.195887,0.187063,0.090179,0.194201,0.242609,0.169014,0.061041,0.037918,0.039313,0.051337,0.042054,0.048548,0.037606,0.039940,0.077234,0.196775,0.269169,0.563740,0.472250,0.124856,0.100263,0.111227,0.100099,0.204490,0.206964,0.233429,0.197979,0.214407,0.172977,0.160865,0.176892,0.174408,0.193935,0.195706,0.173644,0.000611,0.001608,0.000314,0.000622,0.001105,0.004567,0.004253,0.001579,0.000253,0.000667,0.000561,0.000641,1.000000,1.000000,1.000000,1.000000,0.989304,0.868362,0.886197,0.925152,0.905559,0.918310,0.949255,0.952759,0.577039,0.672492,0.668088,0.615391,0.463136,0.391418,0.379694,0.401353,0.417452,0.431941,0.410223,0.397322,0.565839,0.690670,0.663987,0.605313,0.447465,0.376615,0.356146,0.382120,0.400706,0.417118,0.384899,0.371004,0.046680,0.065757,0.083888,0.066037,0.037391,0.027319,0.027977,0.030116,0.025072,0.022237,0.015668,0.018609,0.375020,0.427898,0.673582,0.627870,0.497387,0.175696,0.312284,0.289592,0.178465,0.153599,0.231559,0.148036,0.523402,0.501091,0.512113,0.495440,0.443078,0.393422,0.388671,0.388836,0.393867,0.439397,0.455481,0.439122,0.000507,0.000885,0.001017,0.000469,0.000327,0.000215,0.000233,0.000176,0.000185,0.000824,0.001099,0.000468,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.584666,0.608126,0.622827,0.621890,0.616005,0.606142,0.577764,0.559649,0.546052,0.564408,0.579613,0.571805,0.600094,0.628592,0.646400,0.638524,0.630072,0.619790,0.585617,0.558357,0.547642,0.575303,0.594432,0.583937,0.006699,0.007261,0.010305,0.013110,0.011548,0.009382,0.024494,0.019581,0.012549,0.007715,0.008488,0.011317,0.431134,0.509259,0.517826,0.259170,0.215577,0.253590,0.207256,0.185182,0.263119,0.315854,0.298011,0.424212,0.520630,0.535215,0.516374,0.515777,0.524135,0.538555,0.499063,0.513756,0.502272,0.509208,0.472256,0.495682,0.010628,0.019294,0.026198,0.020461,0.000032,0.484601,0.022654,0.009897,0.545560,0.447588,0.465894,0.279869,0.437159,0.118427,0.009346,0.409470,0.279569,0.270220,0.167659,0.361826,0.098320,0.060692,0.106094,0.134160,0.077662,0.071944,0.073510,0.013323,0.404808,0.305262,0.321104,0.290690,0.280852,0.267242,0.626574,0.302815,0.228409,0.200581,0.069740,0.052241,0.089487,0.598376,0.299972,0.233843,0.197728,0.059160,0.041609,0.088063,0.592531,0.154108,0.189054,0.221291,0.203873,0.235136,0.175771,0.328327,0.492913,0.601008,0.604204,0.576078,0.620707,0.558355,0.642803,0.214565,0.085279,0.163962,0.103736,0.107026,0.055560,0.199240,0.007664,0.710305,0.446184,0.455835,0.177878,0.482573,0.167226,0.010440,0.008064,0.018833,0.026549,0.013910,0.011871,0.293124,0.313009,0.372294,0.390498,0.370035,0.308938,0.285805,0.538227,0.549815,0.454850,0.395710,0.327874,0.254707,0.487527,0.582690,0.433548,0.385615,0.326723,0.697908,0.722547,0.510575,0.490096,0.559037,0.416298,0.690505,0.202076,0.682677,0.675680,0.776846,0.712963,0.097701,0.103183,0.095360,0.150283,0.117570,0.107339,0.006905,0.366439,0.179651,0.180056,0.087357,0.326708,0.103005,30.4,17.4,5.8,5.7,33.1,131.3,33.0,98.2,25.1,98.2,63.30,3.0,1.0,-50.11,2.51,-30.52,-68.63,2168659.57

In [35]:
from feature_engine.selection import SmartCorrelatedSelection
scs = SmartCorrelatedSelection(threshold=0.8)
scs.fit_transform(num_cols)

,chroma_cens_kurtosis_01,chroma_cens_kurtosis_02,chroma_cens_kurtosis_03,chroma_cens_kurtosis_04,chroma_cens_kurtosis_05,chroma_cens_kurtosis_06,chroma_cens_kurtosis_08,chroma_cens_kurtosis_09,chroma_cens_max_01,chroma_cens_max_03,chroma_cens_max_04,chroma_cens_max_05,chroma_cens_max_07,chroma_cens_max_09,chroma_cens_max_10,chroma_cens_mean_01,chroma_cens_mean_02,chroma_cens_mean_03,chroma_cens_median_04,chroma_cens_median_05,chroma_cens_median_06,chroma_cens_median_08,chroma_cens_median_10,chroma_cens_median_12,chroma_cens_min_01,chroma_cens_min_02,chroma_cens_min_03,chroma_cens_min_05,chroma_cens_min_07,chroma_cens_min_10,chroma_cens_min_12,chroma_cens_skew_01,chroma_cens_skew_02,chroma_cens_skew_03,chroma_cens_skew_04,chroma_cens_skew_05,chroma_cens_skew_07,chroma_cens_skew_09,chroma_cens_std_04,chroma_cens_std_07,chroma_cens_std_09,chroma_cens_std_11,chroma_cens_std_12,chroma_cqt_kurtosis_02,chroma_cqt_kurtosis_03,chroma_cqt_kurtosis_04,chroma_cqt_kurtosis_05,chroma_cqt_kurtosis_06,chroma_cqt_kurtosis_08,chroma_cqt_kurtosis_10,chroma_cqt_kurtosis_12,chroma_cqt_max_01,chroma_cqt_max_02,chroma_cqt_max_03,chroma_cqt_max_04,chroma_cqt_max_05,chroma_cqt_max_07,chroma_cqt_max_09,chroma_cqt_max_12,chroma_cqt_mean_03,chroma_cqt_min_01,chroma_cqt_min_03,chroma_cqt_min_09,chroma_cqt_min_12,chroma_cqt_skew_01,chroma_cqt_skew_02,chroma_cqt_skew_03,chroma_cqt_skew_04,chroma_cqt_skew_05,chroma_cqt_std_04,chroma_cqt_std_05,chroma_cqt_std_07,chroma_cqt_std_09,chroma_cqt_std_11,chroma_stft_kurtosis_01,chroma_stft_kurtosis_02,chroma_stft_kurtosis_03,chroma_stft_kurtosis_06,chroma_stft_kurtosis_09,chroma_stft_kurtosis_10,chroma_stft_kurtosis_11,chroma_stft_max_01,chroma_stft_max_03,chroma_stft_max_05,chroma_stft_max_07,chroma_stft_max_08,chroma_stft_max_09,chroma_stft_max_10,chroma_stft_max_11,chroma_stft_max_12,chroma_stft_median_04,chroma_stft_median_06,chroma_stft_median_08,chroma_stft_median_10,chroma_stft_min_01,chroma_stft_min_04,chroma_stft_min_09,chroma_stft_min_11,chroma_stft_skew_12,chroma_stft_std_06,chroma_stft_std_09,chroma_stft_std_12,rmse_max_01,rmse_median_01,rmse_min_01,rmse_skew_01,rmse_std_01,spectral_bandwidth_kurtosis_01,spectral_bandwidth_max_01,spectral_bandwidth_mean_01,spectral_bandwidth_min_01,spectral_bandwidth_skew_01,spectral_bandwidth_std_01,spectral_centroid_kurtosis_01,spectral_centroid_max_01,spectral_centroid_median_01,spectral_centroid_min_01,spectral_centroid_skew_01,spectral_centroid_std_01,spectral_contrast_kurtosis_01,spectral_contrast_kurtosis_02,spectral_contrast_kurtosis_03,spectral_contrast_kurtosis_04,spectral_contrast_kurtosis_05,spectral_contrast_kurtosis_06,spectral_contrast_kurtosis_07,spectral_contrast_max_01,spectral_contrast_max_02,spectral_contrast_max_03,spectral_contrast_max_04,spectral_contrast_max_05,spectral_contrast_max_06,spectral_contrast_max_07,spectral_contrast_mean_01,spectral_contrast_median_02,spectral_contrast_median_03,spectral_contrast_median_04,spectral_contrast_median_05,spectral_contrast_median_06,spectral_contrast_median_07,spectral_contrast_min_01,spectral_contrast_min_02,spectral_contrast_min_03,spectral_contrast_min_04,spectral_contrast_min_05,spectral_contrast_min_06,spectral_contrast_min_07,spectral_contrast_skew_01,spectral_contrast_skew_03,spectral_contrast_skew_04,spectral_contrast_skew_05,spectral_contrast_skew_06,spectral_contrast_skew_07,spectral_contrast_std_01,spectral_contrast_std_02,spectral_contrast_std_06,spectral_contrast_std_07,spectral_rolloff_kurtosis_01,spectral_rolloff_mean_01,spectral_rolloff_skew_01,tonnetz_kurtosis_01,tonnetz_kurtosis_03,tonnetz_kurtosis_05,tonnetz_kurtosis_06,tonnetz_max_01,tonnetz_max_02,tonnetz_max_03,tonnetz_max_04,tonnetz_max_05,tonnetz_median_01,tonnetz_median_02,tonnetz_median_03,tonnetz_median_04,tonnetz_median_05,tonnetz_median_06,tonnetz_min_01,tonnetz_min_02,tonnetz_min_03,tonnetz_min_04,tonnetz_min_05,tonnetz_min_06,tonnetz_skew_01,tonnetz_skew_02,tonnetz_skew_03,tonnetz_skew_04,tonnetz_skew_05,tonnetz_skew_06,tonnetz_std_06,zcr_kurtosis_01,zcr_skew_01,zcr_std_01,Beak.Length_Nares,Beak.Depth,Tarsus.Length,Hand-Wing.Index,Tail.Length,Mass,Habitat.Density,Migration,Max.Latitude,Centroid.Latitude,Centroid.Longitude,Range.Size
0,0.001471,0.007027,0.010283,0.004517,0.003856,0.001506,0.000912,0.002066,0.648805,0.663126,0.551339,0.438560,0.376038,0.352783,0.339950,0.380927,0.488973,0.385909,0.362586,0.254581,0.243424,0.235386,0.178882,0.176428,0.119356,0.236279,0.164361,0.057728,0.028495,0.021995,0.030672,0.102680,0.206678,0.234551,0.539433,0.458215,0.058285,0.073833,0.243572,0.198302,0.196763,0.191179,0.190474,0.001407,0.000343,0.000724,0.000734,0.000588,0.000162,0.000550,0.001893,1.000000,1.000000,1.000000,1.000000,0.986494,0.973353,0.959500,0.967041,0.608010,0.042418,0.055358,0.016319,0.018036,0.373350,0.427082,0.673697,0.625991,0.494511,0.556395,0.525013,0.480995,0.446832,0.463545,0.000408,0.000647,0.000751,0.000184,0.000152,0.000663,0.000724,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.999556,1.000000,0.592804,0.565798,0.552318,0.550540,0.002370,0.006740,0.002244,0.003070,0.424517,0.607541,0.621803,0.594830,0.023056,0.014795,0.001956,0.472892,0.037006,0.005799,0.487877,0.396409,0.190194,0.447451,0.158081,0.006699,0.320833,0.221001,0.108590,0.369187,0.100297,0.068470,0.112198,0.152880,0.038724,0.044872,0.043382,0.017986,0.378847,0.293476,0.329044,0.372922,0.289274,0.356522,0.659636,0.302163,0.228707,0.189666,0.072010,0.058529,0.108055,0.640627,0.146734,0.166500,0.195842,0.197154,0.226881,0.179661,0.333640,0.493284,0.623753,0.540403,0.587163,0.550012,0.641003,0.200771,0.085195,0.129009,0.179045,0.003728,0.368064,0.487640,0.009099,0.013637,0.009013,0.010176,0.295009,0.304878,0.358638,0.459676,0.443844,0.251095,0.486436,0.574344,0.440093,0.403861,0.325176,0.680794,0.686476,0.412624,0.513599,0.609311,0.320151,0.684396,0.183372,0.650663,0.728006,0.821681,0.702080,0.163025,0.004543,0.335196,0.100959,10.4,6.5,36.4,5.5,88.9,89.86,1.0,1.0,9.74,1.60,-76.74,112912.00
1,0.001132,0.003793,0.006593,0.003264,0.003602,0.003011,0.004278,0.004896,0.382395,0.492402,0.555568,0.473350,0.462359,0.417588,0.450097,0.224551,0.252463,0.273591,0.328230,0.272141,0.346990,0.327644,0.243580,0.201697,0.107600,0.101624,0.080041,0.147864,0.170060,0.101908,0.122225,0.102793,0.178931,0.224752,0.557495,0.471830,0.070292,0.085654,0.227310,0.174414,0.200749,0.183656,0.155745,0.002343,0.000543,0.000636,0.001255,0.002347,0.002295,0.000220,0.000589,0.980475,0.977494,1.000000,1.000000,0.990813,0.999241,0.996052,0.983646,0.441671,0.023271,0.062892,0.041662,0.027743,0.383558,0.445862,0.682551,0.633632,0.496842,0.497259,0.458357,0.481772,0.479898,0.490677,0.000329,0.000500,0.000587,0.000132,0.000150,0.000618,0.000694,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.633452,0.621012,0.595570,0.605973,0.067891,0.048128,0.017272,0.032851,0.425432,0.517640,0.494692,0.479947,0.016589,0.007826,0.000012,0.505531,0.019085,0.018140,0.619991,0.554647,0.280423,0.424148,0.162689,0.010224,0.475052,0.295222,0.132072,0.363400,0.135510,0.055808,0.103419,0.125691,0.046891,0.037113,0.020545,0.020700,0.335153,0.256306,0.299808,0.199789,0.226284,0.202285,0.663857,0.287869,0.223061,0.239179,0.037753,0.050001,0.062849,0.668154,0.160532,0.181733,0.237266,0.204267,0.241026,0.175708,0.414098,0.488348,0.575126,0.518731,0.572908,0.521901,0.631659,0.199809,0.076188,0.086374,0.166720,0.013600,0.549654,0.471333,0.005457,0.006077,0.004546,0.003932,0.267232,0.278493,0.338600,0.363829,0.309333,0.261704,0.478201,0.598579,0.418383,0.373263,0.320487,0.715361,0.761377,0.579052,0.602927,0.624658,0.507711,0.681386,0.212595,0.691447,0.740137,0.794826,0.739502,0.097958,0.003733,0.327314,0.125055,18.6,8.6,39.7,24.9,113.1,53.00,3.0,1.0,0.00,-15.22,-71.16,579914.07
2,0.002116,0.014413,0.019840,0.009525,0.005802,0.010294,0.014382,0.010970,0.521195,0.727320,0.633158,0.460323,0.347295,0.377767,0.395316,0.354515,0.453098,0.416843,0.378872,0.233819,0.213303,0.214570,0.191443,0.187063,0.090179,0.194201,0.242609,0.061041,0.039313,0.048548,0.039940,0.077234,0.196775,0.269169,0.563740,0.472250,0.100263,0.100099,0.197979,0.160865,0.174408,0.195706,0.173644,0.001608,0.000314,0.000622,0.001105,0.004567,0.001579,0.000667,0.000641,1.000000,1.000000,1.000000,1.000000,0.989304,0.886197,0.905559,0.952759,0.668088,0.046680,0.083888,0.025072,0.018609,0.375020,0.427898,0.673582,0.627870,0.497387,0.495440,0.443078,0.388671,0.393867,0.455481,0.000507,0.000885,0.001017,0.000215,0.000185,0.000824,0.001099,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.638524,0.619790,0.558357,0.575303,0.006699,0.013110,0.012549,0.008488,0.424212,0.538555,0.502272,0.495682,0.019294,0.020461,0.000032,0.484601,0.022654,0.009897,0.545560,0.447588,0.279869,0.437159,0.118427,0.009346,0.409470,0.270220,0.167659,0.361826,0.098320,0.060692,0.106094,0.134160,0.077662,0.071944,0.073510,0.013323,0.404808,0.305262,0.321104,0.290690,0.280852,0.267242,0.626574,0.302815,0.233843,0.197728,0.059160,0.041609,0.088063,0.592531,0.154108,0.189054,0.221291,0.203873,0.235136,0.175771,0.328327,0.492913,0.604204,0.576078,0.620707,0.558355,0.642803,0.214565,0.085279,0.055560,0.199240,0.007664,0.446184,0.482573,0.010440,0.018833,0.013910,0.011871,0.293124,0.313009,0.372294,0.390498,0.370035,0.254707,0.487527,0.582690,0.433548,0.385615,0.326723,0.697908,0.722547,0.510575,0.490096,0.559037,0.416298,0.690505,0.202076,0.682677,0.675680,0.776846,0.712963,0.107339,0.006905,0.326708,0.103005,17.4,5.7,33.1,25.1,98.2,63.30,3.0,1.0,2.51,-30.52,-68.63,2168659.57
3,0.000970,0.004047,0.005944,0.004501,0.002671,0.000842,0.003271,0.002560,0.513430,0.577776,0.605325,0.444907,0.318269,0.272737,0.265295,0.381892,0.457567,0.422511,0.417475,0.248599,0.225703,0.185478,0.141171,0.171497,0.235021,0.277076,0.282530,0.114802,0.066901,0.063404,0.102281,0.094056,0.173658,0.219358,0.559269,0.469416,0.073756,0.088789,0.178175,0.142963,0.117890,0.101167,0.090957,0.001342,0.001085,0.000606,0.000938,0.000783,0.000317,0.000979,0.001175,0.974746,0.983782,1.000000,0.992665,0.972791,0.874948,0.799509,0.771517,0.642709,0.071769,0.114468,0.026579,0.042857,0.375243,0.431040,0.671688,0.628641,0.498643,0.504922,0.465820,0.374766,0.329181,0.345127,0.000606,0.001024,0.001075,0.000203,0.000152,0.001072,0.001080,1.000000,0.985865,0.984454,1.000000,1.000000,0.999246,1.000000,0.999951,0.998394,0.585418,0.572403,0.524930,0.583674,0.004265,0.006527,0.008092,0.007493,0.426933,0.597853,0.578497,0.550444,0.019270,0.018919,0.003654,0.475633,0.024809,0.007668,0.481386,0.362482,0.175750,0.453618,0.131997,0.004678,0.317749,0.231681,0.149321,0.366307,0.083554,0.059281,0.103756,0.118327,0.035973,0.028426,0.058997,0.014115,0.385778,0.270018,0.248188,0.202982,0.258701,0.323905,0.643794,0.364401,0.234174,0.186821,0.049010,0.058135,0.173118,0.660455,0.193401,0.200291,0.230946,0.205409,0.249928,0.191749,0.289114,0.466499,0.590777,0.503059,0.579618,0.528295,0.632064,0.213775,0.084435,0.099364,0.210430,0.004111,0.366171,0.490312,0.004726,0.006468,0.004353,0.004434,0.248258,0.301625,0.316684,0.386925,0.326862,0.246545,0.499672,0.589115,0.435987,0.389664,0.340374,0.707752,0.762680,0.581490,0.621161,0.639319,0.551913,0.681041,0.208236,0.689692,0.744457,0.795582,0.746167,0.101104,0.003071,0.328980,0.092308,4.4,2.3,11.0,49.9,43.6,13.96,3.0,3.0,10.63,-23.48,-56.90,4295655.00
4,0.000882,0.004240,0.005530,0.003253,0.002052,0.000404,0.000560,0.001001,0.607231,0.564619,0.534960,0.438158,0.372240,0.341900,0.351195,0.403474,0.455010,0.380849,0.346116,0.240608,0.211977,0.198995,0.164074,0.227671,0.200872,0.230360,0.176089,0.086164,0.041312,0.043325,0.060077,0.096240,0.174278,0.205393,0.548467,0.463465,0.061403,0.083283,0.227782,0.191991,0.179237,0.225508,0.258579,0.001182,0.000297,0.000507,0.000579,0.000142,0.000142,0.000471,0.000638,0.995526,1.000000,0.998790,0.999437,0.991872,0.959156,0.927061,0.971225,0.599962,0.094459,0.083833,0.032686,0.047211,0.374627,0.430010,0.674831,0.630129,0.496708,0.535313,0.494235,0.431228,0.395426,0.474937,0.000485,0.001260,0.001207,0.000362,0.000233,0.001085,0.001354,0.990658,0.989728,0.994251,0.999478,1.000000,0.997483,0.999183,1.000000,0.995814,0.425416,0.437874,0.417217,0.430212,0.012278,0.016870,0.011843,0.017001,0.431011,0.587473,0.579256,0.552033,0.018551,0.026360,0.003585,0.466077,0.028019,0.006060,0.459080,0.365718,0.232397,0.456972,0.120292,0.007142,0.301904,0.211049,0.128542,0.374889,0.092204,0.060542,0.104047,0.114715,0.026681,0.028838,0.039065,0.020949,0.358219,0.264211,0.319272,0.269018,0.235427,0.325255,0.618226,0.296265,0.221158,0.205416,0.093669,0.076841,0.133034,0.637426,0.179377,0.185150,0.223756,0.214002,0.252764,0.203537,0.294108,0.490755,0.595141,0.487472,0.556332,0.538865,0.624447,0.203802,0.084397,0.109520,0.170956,0.003652,0.344451,0.489646,0.006206,0.007337,0.005487,0.005914,0.291096,0.319773,0.347179,0.431228,0.379531,0.258124,0.483867,0.587691,0.437582,0.395074,0.322161,0.690517,0.721605,0.533529,0.586640,0.598399,0.458469,0.680538,0.210140,0.682715,0.748212,0.797308,0.739606,0.140332,0.004494,0.334843,0.103805,21.3,9.8,31.5,10.6,97.5,70.42,1.0,1.0,23.75,9.78,-84.39,1152587.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,0.001082,0.004646,0.006361,0.003867,0.003338,0.001439,0.001350,0.001847,0.576541,0.613139,0.585003,0.426603,0.296911,0.268667,0.279978,0.382074,0.494305,0.447392,0.440942,0.254602,0.173790,0.157971,0.135701,0.205497,0.199395,0.303728,0.284279,0.127075,0.036739,0.034980,0.080212,0.098827,0.191024,0.220755,0.549811,0.465831,0.071798,0.087240,0.177171,0.137005,0.132599,0.155893,0.160188,0.001272,0.000291,0.000817,0.001233,0.000470,0.000412,0.000750,0.000720,0.998814,1.000000,1.000000,1.000000,0.978376,0.939899,0.890092,0.869659,0.665893,0.057910,0.086532,0.018157,0.029228,0.376759,0.428890,0.672628,0.623568,0.498068,0.506544,0.461758,0.357492,0.331270,0.412324,0.004171,0.004766,0.004394,0.000922,0.000714,0.003917,0.005554,0.983506,0.980216,0.982419,0.978328,0.984025,0.982164,0.979740,0.986867,0.976238,0.360044,0.368653,0.399148,0.390021,0.012022,0.009963,0.017231,0.015467,0.438934,0.470448,0.487614,0.444455,0.012158,0.028458,0.003430,0.470760,0.016240,0.014762,0.491706,0.374057,0.212202,0.464714,0.112014,0.015913,0.343146,0.264941,0.186838,0.375063,0.075562,0.060000,0.105073,0.122652,0.035506,0.025413,0.033832,0.022029,0.364814,0.254168,0.260886,0.251557,0.257968,0.326728,0.571957,0.322818,0.231938,0.195019,0.097870,0.132821,0.221932,0.546447,0.151907,0.182998,0.214052,0.225173,0.298559,0.244433,0.250032,0.480365,0.590003,0.489746,0.539514,0.494106,0.629684,0.209470,0.079295,0.089801,0.157879,0.016641,0.380888,0.507316,0.005773,0.006711,0.004727,0.005232,0.260230,0.293812,0.344109,0.403887,0.348143,0.250853,0.480212,0.605533,0.432634,0.400002,0.329955,0.703688,0.744492,0.564687,0.597319,0.633498,0.493554,0.682318,0.209731,0.676991,0.743365,0.795933,0.739677,0.123122,0.005195,0.319150,0.087644,5.1,2.8,14.8,13.3,41.8,7.13,1.0,1.0,8.06,-4.86,-66.45,3855220.60
988,0.001365,0.007211,0.008663,0.006919,0.002607,0.000786,0.000694,0.000701,0.602253,0.823877,0.585050,0.390062,0.234088,0.321478,0.327382,0.349630,0.480390,0.469307,0.365783,0.206009,0.138837,0.150684,0.225139,0.286450,0.078440,0.244123,0.252729,0.054578,0.040880,0.032219,0.037823,0.079159,0.201118,0.259554,0.546631,0.461825,0.068496,0.066397,0.226457,0.111605,0.187815,0.247957,0.233485,0.000774,0.000366,0.000404,0.000640,0.000147,0.000140,0.000167,0.000296,1.000000,1.000000,1.000000,1.000000,0.983955,0.962295,0.920265,0.939073,0.717304,0.055494,0.096699,0.020116,0.021018,0.374916,0.430098,0.669537,0.627533,0.496772,0.535640,0.451435,0.337052,0.440765,0.587468,0.000424,0.000563,0.000599,0.000093,0.000115,0.000529,0.000569,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.502927,0.509565,0.397698,0.365574,0.001088,0.002048,0.001604,0.001227,0.431062,0.673992,0.633969,0.572583,0.009296,0.014800,0.000024,0.468211,0.014210,0.004424,0.459097,0.376345,0.173660,0.443560,0.127068,0.003594,0.283795,0.240116,0.116176,0.358942,0.108955,0.066125,0.142450,0.137429,0.029668,0.062131,0.032329,0.012729,0.378130,0.297822,0.271905,0.354550,0.426528,0.567307,0.666291,0.295880,0.209031,0.191559,0.071522,0.062251,0.137741,0.658094,0.193993,0.198793,0.232658,0.221223,0.259881,0.204711,0.319606,0.512939,0.608373,0.522184,0.608300,0.553441,0.638289,0.214579,0.082319,0.294773,0.243086,0.001522,0.379092,0.484548,0.015972,0.013794,0.013633,0.007430,0.416102,0.358874,0.331084,0.410733,0.448659,0.257059,0.474176,0.595120,0.414357,0.380577,0.305986,0.655714,0.603167,0.400532,0.384047,0.469268,0.271606,0.711643,0.177890,0.652822,0.676826,0.782651,0.697980,0.202650,0.001507,0.332589,0.159322,5.6,3.2,18.0,16.0,52.8,10.90,1.0,1.0,11.15,9.22,-72.16,24090.83
989,0.001057,0.006427,0.005948,0.005124,0.003080,0.010223,0.006615,0.002388,0.522311,0.762520,0.640953,0.462792,0.220940,0.269025,0.289377,0.332673,0.445494,0.501779,0.458204,0.290659,0.121352,0.095906,0.141513,0.218704,0.106904,0.232420,0.259368,0.115088,0.032923,0.029622,0.055612,0.086088,0.171249,0.239021,0.549933,0.458290,0.107141,0.086585,0.199583,0.092129,0.136288,0.180729,0.193230,0.001284,0.000312,0.000419,0.000719,0.005019,0.002493,0.000832,0.000646,1.000000,1.000000,1.000000,1.000000,1.000000,0.892780,0.924249,0.975953,0.719466,0.027269,0.091709,0.018347,0.023722,0.378011,0.433323,0.670108,0.625961,0.493679,0.552064,0.510650,0.274640,0.341002,0.447993,0.000926,0.001129,0.009000,0.000464,0.001229,0.005942,0.004793,0.998105,0.943563,0.970622,0.987298,0.983208,0.990948,0.966015,0.991336,0.989921,0.341518,0.482058,0.478457,0.357333,0.012067,0.001702,0.002192,0.005549,0.427707,0.555902,0.512152,0.549514,0.009339,0.009316,0.001446,0.494071,0.010403,0.009504,0.443515,0.343317,0.155285,0.448929,0.123947,0.007324,0.327041,0.256569,0.169697,0.362446,0.088959,0.054118,0.114051,0.140288,0.045620,0.040712,0.026020,0.015688,0.422801,0.267876,0.288951,0.331116,0.308180,0.358188,0.641038,0.396222,0.215162,0.202784,0.070821,0.090789,0.138592,0.621418,0.189774,0.181147,0.219013,0.215397,0.255393,0.205343,0.397591,0.478672,0.602345,0.537968,0.576822,0.531220,0.637250,0.234527,0.086438,0.138522,0.201883,0.007155,0.371928,0.490154,0.007751,0.011098,0.006139,0.006598,0.318166,0.301609,0.386193,0.421855,0.363672,0.269615,0.461091,0.620948,0.436499,0.387938,0.317426,0.709421,0.720976,0.553267,0.488988,0.562629,0.423562,0.696778,0.215852,0.683282,0.701555,0.775205,0.732083,0.128501,0.003966,0.325267,0.106069,5.3,3.5,17.0,15.1,50.9,9.70,1.0,1.0,17.35,15.50,-90.88,71349.79

In [32]:
utils.remove_collinear_features(num_cols, 0.8)

chroma_cens_kurtosis_07 | chroma_cens_kurtosis_06 | 0.91
chroma_cens_kurtosis_08 | chroma_cens_kurtosis_07 | 0.84
chroma_cens_max_07 | chroma_cens_max_06 | 0.83
chroma_cens_max_09 | chroma_cens_max_08 | 0.83
chroma_cens_mean_07 | chroma_cens_mean_06 | 0.87
chroma_cens_mean_08 | chroma_cens_mean_07 | 0.87
chroma_cens_mean_09 | chroma_cens_mean_08 | 0.87
chroma_cens_mean_10 | chroma_cens_mean_09 | 0.86
chroma_cens_mean_11 | chroma_cens_mean_10 | 0.85
chroma_cens_mean_12 | chroma_cens_mean_11 | 0.84
chroma_cens_median_01 | chroma_cens_mean_01 | 0.98
chroma_cens_median_02 | chroma_cens_mean_02 | 0.98
chroma_cens_median_03 | chroma_cens_mean_03 | 0.98
chroma_cens_median_04 | chroma_cens_mean_04 | 0.98
chroma_cens_median_05 | chroma_cens_mean_05 | 0.98
chroma_cens_median_06 | chroma_cens_mean_06 | 0.99
chroma_cens_median_06 | chroma_cens_mean_07 | 0.86
chroma_cens_median_07 | chroma_cens_mean_06 | 0.86
chroma_cens_median_07 | chroma_cens_mean_07 | 0.99
chroma_cens_median_07 | chroma_cens_mean_08 | 0.88
chroma_cens_median_07 | chroma_cens_median_06 | 0.87
chroma_cens_median_08 | chroma_cens_mean_07 | 0.86
chroma_cens_median_08 | chroma_cens_mean_08 | 0.99
chroma_cens_median_08 | chroma_cens_mean_09 | 0.87
chroma_cens_median_08 | chroma_cens_median_07 | 0.88
chroma_cens_median_09 | chroma_cens_mean_08 | 0.87
chroma_cens_median_09 | chroma_cens_mean_09 | 0.99
chroma_cens_median_09 | chroma_cens_mean_10 | 0.86
chroma_cens_median_09 | chroma_cens_median_08 | 0.88
chroma_cens_median_10 | chroma_cens_mean_09 | 0.86
chroma_cens_median_10 | chroma_cens_mean_10 | 0.99
chroma_cens_median_10 | chroma_cens_mean_11 | 0.85
chroma_cens_median_10 | chroma_cens_median_09 | 0.88
chroma_cens_median_11 | chroma_cens_mean_10 | 0.86
chroma_cens_median_11 | chroma_cens_mean_11 | 0.98
chroma_cens_median_11 | chroma_cens_mean_12 | 0.83
chroma_cens_median_11 | chroma_cens_median_10 | 0.87
chroma_cens_median_12 | chroma_cens_mean_11 | 0.85
chroma_cens_median_12 | chroma_cens_mean_12 | 0.97
chroma_cens_median_12 | chroma_cens_median_11 | 0.88
chroma_cens_min_05 | chroma_cens_min_04 | 0.82
chroma_cens_min_07 | chroma_cens_min_06 | 0.91
chroma_cens_min_08 | chroma_cens_min_07 | 0.92
chroma_cens_min_09 | chroma_cens_min_07 | 0.82
chroma_cens_min_09 | chroma_cens_min_08 | 0.91
chroma_cens_min_10 | chroma_cens_min_08 | 0.82
chroma_cens_min_10 | chroma_cens_min_09 | 0.92
chroma_cens_min_11 | chroma_cens_min_10 | 0.91
chroma_cens_min_12 | chroma_cens_min_11 | 0.89
chroma_cens_skew_06 | chroma_cens_kurtosis_06 | 0.81
chroma_cens_skew_07 | chroma_cens_skew_06 | 0.9
chroma_cens_skew_08 | chroma_cens_skew_07 | 0.85
chroma_cens_skew_09 | chroma_cens_skew_08 | 0.81
chroma_cens_std_01 | chroma_cens_max_01 | 0.85
chroma_cens_std_02 | chroma_cens_max_02 | 0.82
chroma_cens_std_02 | chroma_cens_std_01 | 0.81
chroma_cens_std_03 | chroma_cens_std_02 | 0.83
chroma_cens_std_04 | chroma_cens_std_03 | 0.81
chroma_cens_std_05 | chroma_cens_std_04 | 0.82
chroma_cens_std_07 | chroma_cens_std_06 | 0.88
chroma_cens_std_09 | chroma_cens_std_08 | 0.87
chroma_cens_std_10 | chroma_cens_max_10 | 0.81
chroma_cens_std_11 | chroma_cens_max_11 | 0.86
chroma_cens_std_11 | chroma_cens_std_10 | 0.83
chroma_cens_std_12 | chroma_cens_max_12 | 0.91
chroma_cqt_kurtosis_07 | chroma_cqt_kurtosis_06 | 0.94
chroma_cqt_kurtosis_08 | chroma_cqt_kurtosis_07 | 0.86
chroma_cqt_kurtosis_09 | chroma_cqt_kurtosis_08 | 0.89
chroma_cqt_kurtosis_10 | chroma_cqt_kurtosis_09 | 0.88
chroma_cqt_kurtosis_11 | chroma_cqt_kurtosis_10 | 0.9
chroma_cqt_kurtosis_12 | chroma_cqt_kurtosis_01 | 0.8
chroma_cqt_kurtosis_12 | chroma_cqt_kurtosis_11 | 0.89
chroma_cqt_max_07 | chroma_cqt_max_06 | 0.86
chroma_cqt_max_08 | chroma_cqt_max_07 | 0.9
chroma_cqt_max_09 | chroma_cqt_max_08 | 0.9
chroma_cqt_max_10 | chroma_cqt_max_08 | 0.82
chroma_cqt_max_10 | chroma_cqt_max_09 | 0.91
chroma_cqt_max_11 | chroma_cqt_max_09 | 0.81
chroma_cqt_max_11 | chroma_cqt_max_10 | 0.91
chroma_cqt_max_12 | chroma_cqt_max_10 | 0.81
chroma_cqt_max_12 | chroma_cqt_max_11 | 0.92
chroma_cqt_mean_01 | chroma_cens_mean_01 | 0.85
chroma_cqt_mean_01 | chroma_cens_median_01 | 0.85
chroma_cqt_mean_02 | chroma_cens_mean_02 | 0.82
chroma_cqt_mean_02 | chroma_cens_median_02 | 0.82
chroma_cqt_mean_04 | chroma_cens_mean_04 | 0.82
chroma_cqt_mean_04 | chroma_cens_median_04 | 0.81
chroma_cqt_mean_04 | chroma_cens_min_04 | 0.84
chroma_cqt_mean_05 | chroma_cens_mean_05 | 0.87
chroma_cqt_mean_05 | chroma_cens_median_05 | 0.87
chroma_cqt_mean_06 | chroma_cens_mean_06 | 0.95
chroma_cqt_mean_06 | chroma_cens_mean_07 | 0.89
chroma_cqt_mean_06 | chroma_cens_median_06 | 0.94
chroma_cqt_mean_06 | chroma_cens_median_07 | 0.9
chroma_cqt_mean_07 | chroma_cens_mean_06 | 0.83
chroma_cqt_mean_07 | chroma_cens_mean_07 | 0.96
chroma_cqt_mean_07 | chroma_cens_mean_08 | 0.88
chroma_cqt_mean_07 | chroma_cens_median_06 | 0.83
chroma_cqt_mean_07 | chroma_cens_median_07 | 0.96
chroma_cqt_mean_07 | chroma_cens_median_08 | 0.89
chroma_cqt_mean_07 | chroma_cqt_mean_06 | 0.93
chroma_cqt_mean_08 | chroma_cens_mean_07 | 0.85
chroma_cqt_mean_08 | chroma_cens_mean_08 | 0.96
chroma_cqt_mean_08 | chroma_cens_mean_09 | 0.86
chroma_cqt_mean_08 | chroma_cens_median_07 | 0.86
chroma_cqt_mean_08 | chroma_cens_median_08 | 0.96
chroma_cqt_mean_08 | chroma_cens_median_09 | 0.87
chroma_cqt_mean_08 | chroma_cqt_mean_06 | 0.82
chroma_cqt_mean_08 | chroma_cqt_mean_07 | 0.93
chroma_cqt_mean_09 | chroma_cens_mean_08 | 0.88
chroma_cqt_mean_09 | chroma_cens_mean_09 | 0.96
chroma_cqt_mean_09 | chroma_cens_mean_10 | 0.84
chroma_cqt_mean_09 | chroma_cens_median_08 | 0.89
chroma_cqt_mean_09 | chroma_cens_median_09 | 0.96
chroma_cqt_mean_09 | chroma_cens_median_10 | 0.86
chroma_cqt_mean_09 | chroma_cqt_mean_07 | 0.81
chroma_cqt_mean_09 | chroma_cqt_mean_08 | 0.93
chroma_cqt_mean_10 | chroma_cens_mean_09 | 0.87
chroma_cqt_mean_10 | chroma_cens_mean_10 | 0.95
chroma_cqt_mean_10 | chroma_cens_median_09 | 0.88
chroma_cqt_mean_10 | chroma_cens_median_10 | 0.96
chroma_cqt_mean_10 | chroma_cens_median_11 | 0.81
chroma_cqt_mean_10 | chroma_cqt_mean_08 | 0.82
chroma_cqt_mean_10 | chroma_cqt_mean_09 | 0.92
chroma_cqt_mean_11 | chroma_cens_mean_10 | 0.89
chroma_cqt_mean_11 | chroma_cens_mean_11 | 0.93
chroma_cqt_mean_11 | chroma_cens_median_10 | 0.9
chroma_cqt_mean_11 | chroma_cens_median_11 | 0.94
chroma_cqt_mean_11 | chroma_cqt_mean_10 | 0.92
chroma_cqt_mean_12 | chroma_cens_mean_11 | 0.87
chroma_cqt_mean_12 | chroma_cens_mean_12 | 0.92
chroma_cqt_mean_12 | chroma_cens_median_11 | 0.88
chroma_cqt_mean_12 | chroma_cens_median_12 | 0.93
chroma_cqt_mean_12 | chroma_cqt_mean_11 | 0.9
chroma_cqt_median_01 | chroma_cens_mean_01 | 0.85
chroma_cqt_median_01 | chroma_cens_median_01 | 0.85
chroma_cqt_median_01 | chroma_cqt_mean_01 | 0.99
chroma_cqt_median_02 | chroma_cens_mean_02 | 0.84
chroma_cqt_median_02 | chroma_cens_median_02 | 0.85
chroma_cqt_median_02 | chroma_cqt_mean_02 | 0.99
chroma_cqt_median_03 | chroma_cqt_mean_03 | 0.99
chroma_cqt_median_04 | chroma_cens_mean_04 | 0.83
chroma_cqt_median_04 | chroma_cens_median_04 | 0.83
chroma_cqt_median_04 | chroma_cqt_mean_04 | 0.99
chroma_cqt_median_05 | chroma_cens_mean_05 | 0.85
chroma_cqt_median_05 | chroma_cens_median_05 | 0.86
chroma_cqt_median_05 | chroma_cqt_mean_05 | 0.99
chroma_cqt_median_05 | chroma_cqt_mean_06 | 0.8
chroma_cqt_median_06 | chroma_cens_mean_06 | 0.94
chroma_cqt_median_06 | chroma_cens_mean_07 | 0.88
chroma_cqt_median_06 | chroma_cens_median_06 | 0.94
chroma_cqt_median_06 | chroma_cens_median_07 | 0.89
chroma_cqt_median_06 | chroma_cqt_mean_06 | 1.0
chroma_cqt_median_06 | chroma_cqt_mean_07 | 0.93
chroma_cqt_median_06 | chroma_cqt_mean_08 | 0.82
chroma_cqt_median_06 | chroma_cqt_median_05 | 0.8
chroma_cqt_median_07 | chroma_cens_mean_06 | 0.82
chroma_cqt_median_07 | chroma_cens_mean_07 | 0.95
chroma_cqt_median_07 | chroma_cens_mean_08 | 0.88
chroma_cqt_median_07 | chroma_cens_median_06 | 0.82
chroma_cqt_median_07 | chroma_cens_median_07 | 0.96
chroma_cqt_median_07 | chroma_cens_median_08 | 0.89
chroma_cqt_median_07 | chroma_cqt_mean_06 | 0.92
chroma_cqt_median_07 | chroma_cqt_mean_07 | 1.0
chroma_cqt_median_07 | chroma_cqt_mean_08 | 0.93
chroma_cqt_median_07 | chroma_cqt_mean_09 | 0.81
chroma_cqt_median_07 | chroma_cqt_median_06 | 0.92
chroma_cqt_median_08 | chroma_cens_mean_07 | 0.84
chroma_cqt_median_08 | chroma_cens_mean_08 | 0.95
chroma_cqt_median_08 | chroma_cens_mean_09 | 0.85
chroma_cqt_median_08 | chroma_cens_median_07 | 0.86
chroma_cqt_median_08 | chroma_cens_median_08 | 0.96
chroma_cqt_median_08 | chroma_cens_median_09 | 0.86
chroma_cqt_median_08 | chroma_cqt_mean_06 | 0.81
chroma_cqt_median_08 | chroma_cqt_mean_07 | 0.92
chroma_cqt_median_08 | chroma_cqt_mean_08 | 1.0
chroma_cqt_median_08 | chroma_cqt_mean_09 | 0.93
chroma_cqt_median_08 | chroma_cqt_mean_10 | 0.82
chroma_cqt_median_08 | chroma_cqt_median_06 | 0.82
chroma_cqt_median_08 | chroma_cqt_median_07 | 0.93
chroma_cqt_median_09 | chroma_cens_mean_08 | 0.86
chroma_cqt_median_09 | chroma_cens_mean_09 | 0.95
chroma_cqt_median_09 | chroma_cens_mean_10 | 0.83
chroma_cqt_median_09 | chroma_cens_median_08 | 0.88
chroma_cqt_median_09 | chroma_cens_median_09 | 0.96
chroma_cqt_median_09 | chroma_cens_median_10 | 0.85
chroma_cqt_median_09 | chroma_cqt_mean_07 | 0.81
chroma_cqt_median_09 | chroma_cqt_mean_08 | 0.92
chroma_cqt_median_09 | chroma_cqt_mean_09 | 1.0
chroma_cqt_median_09 | chroma_cqt_mean_10 | 0.92
chroma_cqt_median_09 | chroma_cqt_median_07 | 0.81
chroma_cqt_median_09 | chroma_cqt_median_08 | 0.93
chroma_cqt_median_10 | chroma_cens_mean_09 | 0.86
chroma_cqt_median_10 | chroma_cens_mean_10 | 0.93
chroma_cqt_median_10 | chroma_cens_median_09 | 0.88
chroma_cqt_median_10 | chroma_cens_median_10 | 0.95
chroma_cqt_median_10 | chroma_cqt_mean_08 | 0.83
chroma_cqt_median_10 | chroma_cqt_mean_09 | 0.92
chroma_cqt_median_10 | chroma_cqt_mean_10 | 0.99
chroma_cqt_median_10 | chroma_cqt_mean_11 | 0.91
chroma_cqt_median_10 | chroma_cqt_median_08 | 0.83
chroma_cqt_median_10 | chroma_cqt_median_09 | 0.92
chroma_cqt_median_11 | chroma_cens_mean_10 | 0.87
chroma_cqt_median_11 | chroma_cens_mean_11 | 0.91
chroma_cqt_median_11 | chroma_cens_median_10 | 0.9
chroma_cqt_median_11 | chroma_cens_median_11 | 0.93
chroma_cqt_median_11 | chroma_cqt_mean_10 | 0.92
chroma_cqt_median_11 | chroma_cqt_mean_11 | 0.99
chroma_cqt_median_11 | chroma_cqt_mean_12 | 0.89
chroma_cqt_median_11 | chroma_cqt_median_10 | 0.92
chroma_cqt_median_12 | chroma_cens_mean_11 | 0.85
chroma_cqt_median_12 | chroma_cens_mean_12 | 0.88
chroma_cqt_median_12 | chroma_cens_median_11 | 0.88
chroma_cqt_median_12 | chroma_cens_median_12 | 0.91
chroma_cqt_median_12 | chroma_cqt_mean_11 | 0.91
chroma_cqt_median_12 | chroma_cqt_mean_12 | 0.99
chroma_cqt_median_12 | chroma_cqt_median_11 | 0.91
chroma_cqt_min_02 | chroma_cqt_min_01 | 0.9
chroma_cqt_min_03 | chroma_cqt_min_02 | 0.81
chroma_cqt_min_04 | chroma_cens_min_04 | 0.82
chroma_cqt_min_04 | chroma_cens_min_05 | 0.84
chroma_cqt_min_04 | chroma_cqt_min_03 | 0.81
chroma_cqt_min_05 | chroma_cens_min_05 | 0.83
chroma_cqt_min_05 | chroma_cens_min_06 | 0.8
chroma_cqt_min_05 | chroma_cqt_min_04 | 0.91
chroma_cqt_min_06 | chroma_cens_min_06 | 0.87
chroma_cqt_min_06 | chroma_cens_min_07 | 0.8
chroma_cqt_min_06 | chroma_cqt_min_05 | 0.92
chroma_cqt_min_07 | chroma_cens_min_06 | 0.83
chroma_cqt_min_07 | chroma_cens_min_07 | 0.86
chroma_cqt_min_07 | chroma_cens_min_08 | 0.8
chroma_cqt_min_07 | chroma_cqt_min_05 | 0.87
chroma_cqt_min_07 | chroma_cqt_min_06 | 0.95
chroma_cqt_min_08 | chroma_cens_min_07 | 0.84
chroma_cqt_min_08 | chroma_cens_min_08 | 0.85
chroma_cqt_min_08 | chroma_cqt_min_05 | 0.85
chroma_cqt_min_08 | chroma_cqt_min_06 | 0.91
chroma_cqt_min_08 | chroma_cqt_min_07 | 0.95
chroma_cqt_min_09 | chroma_cens_min_08 | 0.83
chroma_cqt_min_09 | chroma_cens_min_09 | 0.81
chroma_cqt_min_09 | chroma_cqt_min_05 | 0.83
chroma_cqt_min_09 | chroma_cqt_min_06 | 0.87
chroma_cqt_min_09 | chroma_cqt_min_07 | 0.9
chroma_cqt_min_09 | chroma_cqt_min_08 | 0.95
chroma_cqt_min_10 | chroma_cqt_min_06 | 0.82
chroma_cqt_min_10 | chroma_cqt_min_07 | 0.86
chroma_cqt_min_10 | chroma_cqt_min_08 | 0.91
chroma_cqt_min_10 | chroma_cqt_min_09 | 0.94
chroma_cqt_min_11 | chroma_cqt_min_08 | 0.84
chroma_cqt_min_11 | chroma_cqt_min_09 | 0.87
chroma_cqt_min_11 | chroma_cqt_min_10 | 0.94
chroma_cqt_min_12 | chroma_cqt_min_10 | 0.84
chroma_cqt_min_12 | chroma_cqt_min_11 | 0.93
chroma_cqt_skew_02 | chroma_cens_median_02 | 0.81
chroma_cqt_skew_02 | chroma_cqt_mean_02 | 0.8
chroma_cqt_skew_02 | chroma_cqt_median_02 | 0.84
chroma_cqt_skew_06 | chroma_cqt_kurtosis_06 | 0.87
chroma_cqt_skew_06 | chroma_cqt_kurtosis_07 | 0.85
chroma_cqt_skew_07 | chroma_cqt_kurtosis_06 | 0.8
chroma_cqt_skew_07 | chroma_cqt_kurtosis_07 | 0.87
chroma_cqt_skew_07 | chroma_cqt_skew_06 | 0.95
chroma_cqt_skew_08 | chroma_cqt_kurtosis_08 | 0.81
chroma_cqt_skew_08 | chroma_cqt_kurtosis_09 | 0.82
chroma_cqt_skew_08 | chroma_cqt_skew_06 | 0.83
chroma_cqt_skew_08 | chroma_cqt_skew_07 | 0.92
chroma_cqt_skew_09 | chroma_cqt_kurtosis_09 | 0.86
chroma_cqt_skew_09 | chroma_cqt_kurtosis_10 | 0.84
chroma_cqt_skew_09 | chroma_cqt_skew_07 | 0.82
chroma_cqt_skew_09 | chroma_cqt_skew_08 | 0.92
chroma_cqt_skew_10 | chroma_cqt_kurtosis_10 | 0.85
chroma_cqt_skew_10 | chroma_cqt_kurtosis_11 | 0.81
chroma_cqt_skew_10 | chroma_cqt_skew_09 | 0.89
chroma_cqt_skew_11 | chroma_cqt_kurtosis_11 | 0.83
chroma_cqt_skew_11 | chroma_cqt_kurtosis_12 | 0.83
chroma_cqt_skew_11 | chroma_cqt_skew_10 | 0.9
chroma_cqt_skew_12 | chroma_cqt_kurtosis_12 | 0.85
chroma_cqt_skew_12 | chroma_cqt_skew_10 | 0.81
chroma_cqt_skew_12 | chroma_cqt_skew_11 | 0.94
chroma_cqt_std_02 | chroma_cens_std_04 | 0.82
chroma_cqt_std_02 | chroma_cqt_std_01 | 0.87
chroma_cqt_std_03 | chroma_cqt_std_02 | 0.87
chroma_cqt_std_04 | chroma_cens_std_02 | 0.83
chroma_cqt_std_04 | chroma_cens_std_03 | 0.82
chroma_cqt_std_04 | chroma_cqt_min_04 | 0.81
chroma_cqt_std_04 | chroma_cqt_std_01 | 0.81
chroma_cqt_std_04 | chroma_cqt_std_02 | 0.85
chroma_cqt_std_04 | chroma_cqt_std_03 | 0.9
chroma_cqt_std_07 | chroma_cqt_std_06 | 0.92
chroma_cqt_std_08 | chroma_cqt_std_07 | 0.9
chroma_cqt_std_09 | chroma_cqt_std_08 | 0.92
chroma_cqt_std_10 | chroma_cqt_std_09 | 0.9
chroma_cqt_std_11 | chroma_cqt_std_10 | 0.91
chroma_cqt_std_12 | chroma_cens_max_12 | 0.82
chroma_cqt_std_12 | chroma_cqt_std_11 | 0.91
chroma_stft_kurtosis_04 | chroma_stft_kurtosis_03 | 0.84
chroma_stft_kurtosis_06 | chroma_stft_kurtosis_05 | 0.8
chroma_stft_kurtosis_07 | chroma_stft_kurtosis_06 | 0.87
chroma_stft_kurtosis_08 | chroma_stft_kurtosis_07 | 0.9
chroma_stft_kurtosis_09 | chroma_stft_kurtosis_07 | 0.8
chroma_stft_kurtosis_09 | chroma_stft_kurtosis_08 | 0.9
chroma_stft_kurtosis_12 | chroma_stft_kurtosis_01 | 0.88
chroma_stft_max_02 | chroma_stft_max_01 | 0.83
chroma_stft_max_03 | chroma_stft_max_02 | 0.81
chroma_stft_max_05 | chroma_stft_max_04 | 0.81
chroma_stft_max_06 | chroma_stft_max_05 | 0.89
chroma_stft_max_07 | chroma_stft_max_06 | 0.86
chroma_stft_mean_02 | chroma_stft_mean_01 | 0.95
chroma_stft_mean_03 | chroma_stft_mean_01 | 0.87
chroma_stft_mean_03 | chroma_stft_mean_02 | 0.96
chroma_stft_mean_04 | chroma_stft_mean_02 | 0.88
chroma_stft_mean_04 | chroma_stft_mean_03 | 0.96
chroma_stft_mean_05 | chroma_stft_mean_03 | 0.85
chroma_stft_mean_05 | chroma_stft_mean_04 | 0.93
chroma_stft_mean_06 | chroma_stft_mean_05 | 0.91
chroma_stft_mean_07 | chroma_stft_mean_05 | 0.81
chroma_stft_mean_07 | chroma_stft_mean_06 | 0.91
chroma_stft_mean_08 | chroma_stft_mean_07 | 0.86
chroma_stft_mean_09 | chroma_stft_mean_08 | 0.89
chroma_stft_mean_10 | chroma_stft_mean_09 | 0.89
chroma_stft_mean_11 | chroma_stft_mean_01 | 0.8
chroma_stft_mean_11 | chroma_stft_mean_10 | 0.89
chroma_stft_mean_12 | chroma_stft_mean_01 | 0.93
chroma_stft_mean_12 | chroma_stft_mean_02 | 0.82
chroma_stft_mean_12 | chroma_stft_mean_11 | 0.91
chroma_stft_median_01 | chroma_stft_mean_01 | 0.99
chroma_stft_median_01 | chroma_stft_mean_02 | 0.94
chroma_stft_median_01 | chroma_stft_mean_03 | 0.87
chroma_stft_median_01 | chroma_stft_mean_12 | 0.92
chroma_stft_median_02 | chroma_stft_mean_01 | 0.94
chroma_stft_median_02 | chroma_stft_mean_02 | 0.99
chroma_stft_median_02 | chroma_stft_mean_03 | 0.95
chroma_stft_median_02 | chroma_stft_mean_04 | 0.88
chroma_stft_median_02 | chroma_stft_mean_12 | 0.82
chroma_stft_median_02 | chroma_stft_median_01 | 0.95
chroma_stft_median_03 | chroma_stft_mean_01 | 0.87
chroma_stft_median_03 | chroma_stft_mean_02 | 0.95
chroma_stft_median_03 | chroma_stft_mean_03 | 0.99
chroma_stft_median_03 | chroma_stft_mean_04 | 0.95
chroma_stft_median_03 | chroma_stft_mean_05 | 0.86
chroma_stft_median_03 | chroma_stft_median_01 | 0.87
chroma_stft_median_03 | chroma_stft_median_02 | 0.96
chroma_stft_median_04 | chroma_stft_mean_02 | 0.87
chroma_stft_median_04 | chroma_stft_mean_03 | 0.95
chroma_stft_median_04 | chroma_stft_mean_04 | 0.99
chroma_stft_median_04 | chroma_stft_mean_05 | 0.93
chroma_stft_median_04 | chroma_stft_median_01 | 0.8
chroma_stft_median_04 | chroma_stft_median_02 | 0.88
chroma_stft_median_04 | chroma_stft_median_03 | 0.96
chroma_stft_median_05 | chroma_stft_mean_03 | 0.85
chroma_stft_median_05 | chroma_stft_mean_04 | 0.93
chroma_stft_median_05 | chroma_stft_mean_05 | 0.99
chroma_stft_median_05 | chroma_stft_mean_06 | 0.9
chroma_stft_median_05 | chroma_stft_mean_07 | 0.81
chroma_stft_median_05 | chroma_stft_median_02 | 0.8
chroma_stft_median_05 | chroma_stft_median_03 | 0.86
chroma_stft_median_05 | chroma_stft_median_04 | 0.94
chroma_stft_median_06 | chroma_stft_mean_05 | 0.89
chroma_stft_median_06 | chroma_stft_mean_06 | 0.99
chroma_stft_median_06 | chroma_stft_mean_07 | 0.89
chroma_stft_median_06 | chroma_stft_median_05 | 0.9
chroma_stft_median_07 | chroma_stft_mean_05 | 0.8
chroma_stft_median_07 | chroma_stft_mean_06 | 0.9
chroma_stft_median_07 | chroma_stft_mean_07 | 0.99
chroma_stft_median_07 | chroma_stft_mean_08 | 0.84
chroma_stft_median_07 | chroma_stft_median_05 | 0.82
chroma_stft_median_07 | chroma_stft_median_06 | 0.9
chroma_stft_median_08 | chroma_stft_mean_07 | 0.85
chroma_stft_median_08 | chroma_stft_mean_08 | 0.99
chroma_stft_median_08 | chroma_stft_mean_09 | 0.88
chroma_stft_median_08 | chroma_stft_median_07 | 0.85
chroma_stft_median_09 | chroma_stft_mean_08 | 0.88
chroma_stft_median_09 | chroma_stft_mean_09 | 0.99
chroma_stft_median_09 | chroma_stft_mean_10 | 0.87
chroma_stft_median_09 | chroma_stft_median_08 | 0.88
chroma_stft_median_10 | chroma_stft_mean_09 | 0.88
chroma_stft_median_10 | chroma_stft_mean_10 | 0.99
chroma_stft_median_10 | chroma_stft_mean_11 | 0.87
chroma_stft_median_10 | chroma_stft_median_09 | 0.88
chroma_stft_median_11 | chroma_stft_mean_10 | 0.88
chroma_stft_median_11 | chroma_stft_mean_11 | 0.99
chroma_stft_median_11 | chroma_stft_mean_12 | 0.89
chroma_stft_median_11 | chroma_stft_median_10 | 0.87
chroma_stft_median_12 | chroma_stft_mean_01 | 0.92
chroma_stft_median_12 | chroma_stft_mean_02 | 0.81
chroma_stft_median_12 | chroma_stft_mean_11 | 0.9
chroma_stft_median_12 | chroma_stft_mean_12 | 0.99
chroma_stft_median_12 | chroma_stft_median_01 | 0.92
chroma_stft_median_12 | chroma_stft_median_02 | 0.82
chroma_stft_median_12 | chroma_stft_median_11 | 0.9
chroma_stft_min_02 | chroma_stft_min_01 | 0.94
chroma_stft_min_03 | chroma_stft_min_01 | 0.85
chroma_stft_min_03 | chroma_stft_min_02 | 0.94
chroma_stft_min_04 | chroma_stft_min_02 | 0.85
chroma_stft_min_04 | chroma_stft_min_03 | 0.96
chroma_stft_min_05 | chroma_stft_min_02 | 0.81
chroma_stft_min_05 | chroma_stft_min_03 | 0.92
chroma_stft_min_05 | chroma_stft_min_04 | 0.98
chroma_stft_min_06 | chroma_stft_min_03 | 0.89
chroma_stft_min_06 | chroma_stft_min_04 | 0.94
chroma_stft_min_06 | chroma_stft_min_05 | 0.97
chroma_stft_min_07 | chroma_stft_min_03 | 0.85
chroma_stft_min_07 | chroma_stft_min_04 | 0.9
chroma_stft_min_07 | chroma_stft_min_05 | 0.92
chroma_stft_min_07 | chroma_stft_min_06 | 0.97
chroma_stft_min_08 | chroma_stft_min_03 | 0.84
chroma_stft_min_08 | chroma_stft_min_04 | 0.89

,chroma_cens_kurtosis_01,chroma_cens_kurtosis_02,chroma_cens_kurtosis_03,chroma_cens_kurtosis_04,chroma_cens_kurtosis_05,chroma_cens_kurtosis_06,chroma_cens_kurtosis_09,chroma_cens_max_01,chroma_cens_max_02,chroma_cens_max_03,chroma_cens_max_04,chroma_cens_max_05,chroma_cens_max_06,chroma_cens_max_08,chroma_cens_max_10,chroma_cens_max_11,chroma_cens_max_12,chroma_cens_mean_01,chroma_cens_mean_02,chroma_cens_mean_03,chroma_cens_mean_04,chroma_cens_mean_05,chroma_cens_mean_06,chroma_cens_min_01,chroma_cens_min_02,chroma_cens_min_03,chroma_cens_min_04,chroma_cens_min_06,chroma_cens_skew_01,chroma_cens_skew_02,chroma_cens_skew_03,chroma_cens_skew_04,chroma_cens_skew_05,chroma_cens_std_06,chroma_cens_std_08,chroma_cqt_kurtosis_01,chroma_cqt_kurtosis_02,chroma_cqt_kurtosis_03,chroma_cqt_kurtosis_04,chroma_cqt_kurtosis_05,chroma_cqt_kurtosis_06,chroma_cqt_max_01,chroma_cqt_max_02,chroma_cqt_max_03,chroma_cqt_max_04,chroma_cqt_max_05,chroma_cqt_max_06,chroma_cqt_mean_03,chroma_cqt_min_01,chroma_cqt_skew_01,chroma_cqt_skew_03,chroma_cqt_skew_04,chroma_cqt_skew_05,chroma_cqt_std_01,chroma_cqt_std_05,chroma_cqt_std_06,chroma_stft_kurtosis_01,chroma_stft_kurtosis_02,chroma_stft_kurtosis_03,chroma_stft_kurtosis_05,chroma_stft_kurtosis_10,chroma_stft_kurtosis_11,chroma_stft_max_01,chroma_stft_max_04,chroma_stft_max_08,chroma_stft_max_09,chroma_stft_max_10,chroma_stft_max_11,chroma_stft_max_12,chroma_stft_mean_01,chroma_stft_min_01,chroma_stft_std_01,rmse_kurtosis_01,rmse_max_01,rmse_mean_01,rmse_min_01,rmse_std_01,spectral_bandwidth_kurtosis_01,spectral_bandwidth_max_01,spectral_bandwidth_mean_01,spectral_bandwidth_min_01,spectral_bandwidth_skew_01,spectral_bandwidth_std_01,spectral_centroid_kurtosis_01,spectral_centroid_max_01,spectral_centroid_mean_01,spectral_centroid_min_01,spectral_centroid_skew_01,spectral_centroid_std_01,spectral_contrast_kurtosis_01,spectral_contrast_kurtosis_02,spectral_contrast_kurtosis_03,spectral_contrast_kurtosis_04,spectral_contrast_kurtosis_05,spectral_contrast_kurtosis_06,spectral_contrast_kurtosis_07,spectral_contrast_max_01,spectral_contrast_max_02,spectral_contrast_max_03,spectral_contrast_max_04,spectral_contrast_max_05,spectral_contrast_max_06,spectral_contrast_max_07,spectral_contrast_mean_01,spectral_contrast_mean_02,spectral_contrast_mean_03,spectral_contrast_mean_04,spectral_contrast_mean_05,spectral_contrast_mean_06,spectral_contrast_mean_07,spectral_contrast_min_01,spectral_contrast_min_02,spectral_contrast_min_03,spectral_contrast_min_04,spectral_contrast_min_05,spectral_contrast_min_06,spectral_contrast_min_07,spectral_contrast_skew_01,spectral_contrast_skew_03,spectral_contrast_skew_04,spectral_contrast_skew_05,spectral_contrast_skew_06,spectral_contrast_skew_07,spectral_contrast_std_01,spectral_contrast_std_02,spectral_contrast_std_06,spectral_contrast_std_07,spectral_rolloff_kurtosis_01,spectral_rolloff_skew_01,tonnetz_kurtosis_01,tonnetz_kurtosis_02,tonnetz_kurtosis_03,tonnetz_kurtosis_04,tonnetz_kurtosis_06,tonnetz_max_01,tonnetz_max_02,tonnetz_max_03,tonnetz_max_04,tonnetz_max_05,tonnetz_max_06,tonnetz_mean_01,tonnetz_mean_02,tonnetz_mean_03,tonnetz_mean_04,tonnetz_mean_05,tonnetz_mean_06,tonnetz_min_02,tonnetz_min_05,tonnetz_min_06,tonnetz_skew_01,tonnetz_skew_02,tonnetz_skew_03,tonnetz_skew_04,tonnetz_skew_05,tonnetz_skew_06,zcr_kurtosis_01,zcr_skew_01,zcr_std_01,Beak.Length_Culmen,Beak.Width,Tarsus.Length,Wing.Length,Kipps.Distance,Tail.Length,Habitat.Density,Migration,Min.Latitude,Max.Latitude,Centroid.Longitude,Range.Size
0,0.001471,0.007027,0.010283,0.004517,0.003856,0.001506,0.002066,0.648805,0.780883,0.663126,0.551339,0.438560,0.390459,0.373493,0.339950,0.364230,0.418704,0.380927,0.488973,0.385909,0.352912,0.253815,0.240446,0.119356,0.236279,0.164361,0.096330,0.037007,0.102680,0.206678,0.234551,0.539433,0.458215,0.219827,0.213141,0.000629,0.001407,0.000343,0.000724,0.000734,0.000588,1.000000,1.000000,1.000000,1.000000,0.986494,0.974727,0.608010,0.042418,0.373350,0.673697,0.625991,0.494511,0.569113,0.525013,0.511016,0.000408,0.000647,0.000751,0.000250,0.000663,0.000724,1.000000,1.000000,1.000000,1.000000,1.000000,0.999556,1.000000,0.551524,0.002370,0.605074,0.007701,0.023056,0.030794,0.001956,0.037006,0.005799,0.487877,0.396409,0.190194,0.447451,0.158081,0.006699,0.320833,0.222023,0.108590,0.369187,0.100297,0.068470,0.112198,0.152880,0.038724,0.044872,0.043382,0.017986,0.378847,0.293476,0.329044,0.372922,0.289274,0.356522,0.659636,0.302163,0.223749,0.194647,0.110251,0.074428,0.118504,0.641271,0.146734,0.166500,0.195842,0.197154,0.226881,0.179661,0.333640,0.493284,0.623753,0.540403,0.587163,0.550012,0.641003,0.200771,0.085195,0.129009,0.179045,0.003728,0.487640,0.009099,0.006394,0.013637,0.014560,0.010176,0.295009,0.304878,0.358638,0.459676,0.443844,0.320703,0.281380,0.532709,0.527748,0.465552,0.420959,0.321345,0.686476,0.609311,0.320151,0.684396,0.183372,0.650663,0.728006,0.821681,0.702080,0.004543,0.335196,0.100959,22.9,4.5,36.4,94.8,5.2,88.9,1.0,1.0,-5.46,9.74,-76.74,112912.00
1,0.001132,0.003793,0.006593,0.003264,0.003602,0.003011,0.004896,0.382395,0.396291,0.492402,0.555568,0.473350,0.467723,0.447528,0.450097,0.410618,0.383529,0.224551,0.252463,0.273591,0.338166,0.282609,0.356559,0.107600,0.101624,0.080041,0.145951,0.205883,0.102793,0.178931,0.224752,0.557495,0.471830,0.187058,0.203290,0.001155,0.002343,0.000543,0.000636,0.001255,0.002347,0.980475,0.977494,1.000000,1.000000,0.990813,1.000000,0.441671,0.023271,0.383558,0.682551,0.633632,0.496842,0.445851,0.458357,0.464090,0.000329,0.000500,0.000587,0.000204,0.000618,0.000694,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.631054,0.067891,0.501650,0.025185,0.016589,0.015231,0.000012,0.019085,0.018140,0.619991,0.554647,0.280423,0.424148,0.162689,0.010224,0.475052,0.299735,0.132072,0.363400,0.135510,0.055808,0.103419,0.125691,0.046891,0.037113,0.020545,0.020700,0.335153,0.256306,0.299808,0.199789,0.226284,0.202285,0.663857,0.287869,0.216740,0.239603,0.046064,0.058862,0.068738,0.671787,0.160532,0.181733,0.237266,0.204267,0.241026,0.175708,0.414098,0.488348,0.575126,0.518731,0.572908,0.521901,0.631659,0.199809,0.076188,0.086374,0.166720,0.013600,0.471333,0.005457,0.002771,0.006077,0.005868,0.003932,0.267232,0.278493,0.338600,0.363829,0.309333,0.288960,0.293596,0.528885,0.568007,0.443048,0.382565,0.323573,0.761377,0.624658,0.507711,0.681386,0.212595,0.691447,0.740137,0.794826,0.739502,0.003733,0.327314,0.125055,32.4,7.0,39.7,141.3,35.2,113.1,3.0,1.0,-27.47,0.00,-71.16,579914.07
2,0.002116,0.014413,0.019840,0.009525,0.005802,0.010294,0.010970,0.521195,0.678582,0.727320,0.633158,0.460323,0.361243,0.386281,0.395316,0.398350,0.378965,0.354515,0.453098,0.416843,0.386232,0.241711,0.220344,0.090179,0.194201,0.242609,0.169014,0.037918,0.077234,0.196775,0.269169,0.563740,0.472250,0.172977,0.176892,0.000611,0.001608,0.000314,0.000622,0.001105,0.004567,1.000000,1.000000,1.000000,1.000000,0.989304,0.868362,0.668088,0.046680,0.375020,0.673582,0.627870,0.497387,0.523402,0.443078,0.393422,0.000507,0.000885,0.001017,0.000327,0.000824,0.001099,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.584666,0.006699,0.520630,0.010628,0.019294,0.026198,0.000032,0.022654,0.009897,0.545560,0.447588,0.279869,0.437159,0.118427,0.009346,0.409470,0.279569,0.167659,0.361826,0.098320,0.060692,0.106094,0.134160,0.077662,0.071944,0.073510,0.013323,0.404808,0.305262,0.321104,0.290690,0.280852,0.267242,0.626574,0.302815,0.228409,0.200581,0.069740,0.052241,0.089487,0.598376,0.154108,0.189054,0.221291,0.203873,0.235136,0.175771,0.328327,0.492913,0.604204,0.576078,0.620707,0.558355,0.642803,0.214565,0.085279,0.055560,0.199240,0.007664,0.482573,0.010440,0.008064,0.018833,0.026549,0.011871,0.293124,0.313009,0.372294,0.390498,0.370035,0.308938,0.285805,0.538227,0.549815,0.454850,0.395710,0.327874,0.722547,0.559037,0.416298,0.690505,0.202076,0.682677,0.675680,0.776846,0.712963,0.006905,0.326708,0.103005,30.4,5.8,33.1,131.3,33.0,98.2,3.0,1.0,-50.11,2.51,-68.63,2168659.57
3,0.000970,0.004047,0.005944,0.004501,0.002671,0.000842,0.002560,0.513430,0.571216,0.577776,0.605325,0.444907,0.349598,0.290893,0.265295,0.247666,0.252519,0.381892,0.457567,0.422511,0.426870,0.261405,0.231068,0.235021,0.277076,0.282530,0.285173,0.073237,0.094056,0.173658,0.219358,0.559269,0.469416,0.173781,0.138380,0.000664,0.001342,0.001085,0.000606,0.000938,0.000783,0.974746,0.983782,1.000000,0.992665,0.972791,0.922124,0.642709,0.071769,0.375243,0.671688,0.628641,0.498643,0.514782,0.465820,0.413423,0.000606,0.001024,0.001075,0.000321,0.001072,0.001080,1.000000,0.988318,1.000000,0.999246,1.000000,0.999951,0.998394,0.522314,0.004265,0.582818,0.008883,0.019270,0.028753,0.003654,0.024809,0.007668,0.481386,0.362482,0.175750,0.453618,0.131997,0.004678,0.317749,0.237233,0.149321,0.366307,0.083554,0.059281,0.103756,0.118327,0.035973,0.028426,0.058997,0.014115,0.385778,0.270018,0.248188,0.202982,0.258701,0.323905,0.643794,0.364401,0.227834,0.188393,0.058451,0.077549,0.171487,0.651357,0.193401,0.200291,0.230946,0.205409,0.249928,0.191749,0.289114,0.466499,0.590777,0.503059,0.579618,0.528295,0.632064,0.213775,0.084435,0.099364,0.210430,0.004111,0.490312,0.004726,0.003315,0.006468,0.006993,0.004434,0.248258,0.301625,0.316684,0.386925,0.326862,0.320901,0.275912,0.551791,0.556088,0.462811,0.400256,0.346524,0.762680,0.639319,0.551913,0.681041,0.208236,0.689692,0.744457,0.795582,0.746167,0.003071,0.328980,0.092308,9.2,3.7,11.0,99.0,49.2,43.6,3.0,3.0,-36.66,10.63,-56.90,4295655.00
4,0.000882,0.004240,0.005530,0.003253,0.002052,0.000404,0.001001,0.607231,0.613951,0.564619,0.534960,0.438158,0.388329,0.349616,0.351195,0.414647,0.474239,0.403474,0.455010,0.380849,0.348838,0.252672,0.225035,0.200872,0.230360,0.176089,0.134174,0.058173,0.096240,0.174278,0.205393,0.548467,0.463465,0.209770,0.193344,0.000396,0.001182,0.000297,0.000507,0.000579,0.000142,0.995526,1.000000,0.998790,0.999437,0.991872,0.980638,0.599962,0.094459,0.374627,0.674831,0.630129,0.496708,0.546045,0.494235,0.465656,0.000485,0.001260,0.001207,0.000471,0.001085,0.001354,0.990658,0.990240,1.000000,0.997483,0.999183,1.000000,0.995814,0.460171,0.012278,0.575920,0.006622,0.018551,0.038653,0.003585,0.028019,0.006060,0.459080,0.365718,0.232397,0.456972,0.120292,0.007142,0.301904,0.217965,0.128542,0.374889,0.092204,0.060542,0.104047,0.114715,0.026681,0.028838,0.039065,0.020949,0.358219,0.264211,0.319272,0.269018,0.235427,0.325255,0.618226,0.296265,0.215327,0.211449,0.107470,0.087443,0.139067,0.633316,0.179377,0.185150,0.223756,0.214002,0.252764,0.203537,0.294108,0.490755,0.595141,0.487472,0.556332,0.538865,0.624447,0.203802,0.084397,0.109520,0.170956,0.003652,0.489646,0.006206,0.004480,0.007337,0.008853,0.005914,0.291096,0.319773,0.347179,0.431228,0.379531,0.328066,0.290824,0.535454,0.553571,0.462849,0.403947,0.322618,0.721605,0.598399,0.458469,0.680538,0.210140,0.682715,0.748212,0.797308,0.739606,0.004494,0.334843,0.103805,30.3,7.0,31.5,94.6,9.7,97.5,1.0,1.0,-18.35,23.75,-84.39,1152587.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,0.001082,0.004646,0.006361,0.003867,0.003338,0.001439,0.001847,0.576541,0.651661,0.613139,0.585003,0.426603,0.308925,0.285900,0.279978,0.312451,0.357864,0.382074,0.494305,0.447392,0.445064,0.262538,0.182107,0.199395,0.303728,0.284279,0.281244,0.055865,0.098827,0.191024,0.220755,0.549811,0.465831,0.154750,0.150156,0.000671,0.001272,0.000291,0.000817,0.001233,0.000470,0.998814,1.000000,1.000000,1.000000,0.978376,0.948683,0.665893,0.057910,0.376759,0.672628,0.623568,0.498068,0.542900,0.461758,0.392119,0.004171,0.004766,0.004394,0.001202,0.003917,0.005554,0.983506,0.965439,0.984025,0.982164,0.979740,0.986867,0.976238,0.308767,0.012022,0.434514,0.006970,0.012158,0.033685,0.003430,0.016240,0.014762,0.491706,0.374057,0.212202,0.464714,0.112014,0.015913,0.343146,0.273400,0.186838,0.375063,0.075562,0.060000,0.105073,0.122652,0.035506,0.025413,0.033832,0.022029,0.364814,0.254168,0.260886,0.251557,0.257968,0.326728,0.571957,0.322818,0.226362,0.197077,0.109473,0.140840,0.221765,0.545039,0.151907,0.182998,0.214052,0.225173,0.298559,0.244433,0.250032,0.480365,0.590003,0.489746,0.539514,0.494106,0.629684,0.209470,0.079295,0.089801,0.157879,0.016641,0.507316,0.005773,0.003613,0.006711,0.007558,0.005232,0.260230,0.293812,0.344109,0.403887,0.348143,0.324811,0.280307,0.529541,0.570992,0.458077,0.410216,0.333906,0.744492,0.633498,0.493554,0.682318,0.209731,0.676991,0.743365,0.795933,0.739677,0.005195,0.319150,0.087644,10.0,3.4,14.8,46.7,6.1,41.8,1.0,1.0,-17.23,8.06,-66.45,3855220.60
988,0.001365,0.007211,0.008663,0.006919,0.002607,0.000786,0.000701,0.602253,0.717105,0.823877,0.585050,0.390062,0.269049,0.263490,0.327382,0.397382,0.421664,0.349630,0.480390,0.469307,0.365662,0.208047,0.144291,0.078440,0.244123,0.252729,0.143208,0.045042,0.079159,0.201118,0.259554,0.546631,0.461825,0.127237,0.148563,0.000385,0.000774,0.000366,0.000404,0.000640,0.000147,1.000000,1.000000,1.000000,1.000000,0.983955,0.920038,0.717304,0.055494,0.374916,0.669537,0.627533,0.496772,0.599239,0.451435,0.371235,0.000424,0.000563,0.000599,0.000146,0.000529,0.000569,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.396241,0.001088,0.607022,0.004416,0.009296,0.020391,0.000024,0.014210,0.004424,0.459097,0.376345,0.173660,0.443560,0.127068,0.003594,0.283795,0.249734,0.116176,0.358942,0.108955,0.066125,0.142450,0.137429,0.029668,0.062131,0.032329,0.012729,0.378130,0.297822,0.271905,0.354550,0.426528,0.567307,0.666291,0.295880,0.205055,0.193064,0.103573,0.079779,0.173519,0.644505,0.193993,0.198793,0.232658,0.221223,0.259881,0.204711,0.319606,0.512939,0.608373,0.522184,0.608300,0.553441,0.638289,0.214579,0.082319,0.294773,0.243086,0.001522,0.484548,0.015972,0.010401,0.013794,0.015370,0.007430,0.416102,0.358874,0.331084,0.410733,0.448659,0.311858,0.291464,0.517555,0.546864,0.421107,0.388283,0.288995,0.603167,0.469268,0.271606,0.711643,0.177890,0.652822,0.676826,0.782651,0.697980,0.001507,0.332589,0.159322,11.2,3.2,18.0,60.4,9.5,52.8,1.0,1.0,6.89,11.15,-72.16,24090.83
989,0.001057,0.006427,0.005948,0.005124,0.003080,0.010223,0.002388,0.522311,0.586456,0.762520,0.640953,0.462792,0.235326,0.224472,0.289377,0.353914,0.381059,0.332673,0.445494,0.501779,0.467927,0.293296,0.127570,0.106904,0.232420,0.259368,0.251609,0.052445,0.086088,0.171249,0.239021,0.549933,0.458290,0.107922,0.100834,0.000717,0.001284,0.000312,0.000419,0.000719,0.005019,1.000000,1.000000,1.000000,1.000000,1.000000,0.902616,0.719466,0.027269,0.378011,0.670108,0.625961,0.493679,0.561809,0.510650,0.314329,0.000926,0.001129,0.009000,0.001305,0.005942,0.004793,0.998105,0.960981,0.983208,0.990948,0.966015,0.991336,0.989921,0.459589,0.012067,0.547320,0.018902,0.009339,0.012629,0.001446,0.010403,0.009504,0.443515,0.343317,0.155285,0.448929,0.123947,0.007324,0.327041,0.266244,0.169697,0.362446,0.088959,0.054118,0.114051,0.140288,0.045620,0.040712,0.026020,0.015688,0.422801,0.267876,0.288951,0.331116,0.308180,0.358188,0.641038,0.396222,0.209826,0.204720,0.091669,0.104573,0.145419,0.628283,0.189774,0.181147,0.219013,0.215397,0.255393,0.205343,0.397591,0.478672,0.602345,0.537968,0.576822,0.531220,0.637250,0.234527,0.086438,0.138522,0.201883,0.007155,0.490154,0.007751,0.004799,0.011098,0.010005,0.006598,0.318166,0.301609,0.386193,0.421855,0.363672,0.316080,0.304652,0.513605,0.590719,0.449413,0.391689,0.317406,0.720976,0.562629,0.423562,0.696778,0.215852,0.683282,0.701555,0.775205,0.732083,0.003966,0.325267,0.106069,10.1,3.5,17.0,58.1,8.8,50.9,1.0,1.0,13.51,17.35,-90.88,71349.79
990,0.002654,0.006072,0.008344,0.004506,0.003198,0.003139,0.004264,0.498103,0.543273,0.596950,0.702352,0.586915,0.374112,0.358555,0.316738,0.329601,0.333639,0.324082,0.410467,0.398856,0.457827,0.315149,0.230501,0.112079,0.159881,0.184348,0.260632,0.066812,0.093781,0.163719,0.213399,0.563205,0.474270,0.180215,0.175153,0.003681,0.002126,0.000334,0.001267,0.000721,0.003075,0.985372,0.992797,0.997520,0.999145,0.996461,0.918465,0.613342,0.048131,0.379779,0.674190,0.624775,0.496748,0.515399,0.522735,0.429289,0.000503,0.000805,0.000943,0.000303,0.000802,0.000887,0.999711,0.999590,0.999229,0.999672,0.999567,0.998220,0.999067,0.497205,0.004420,0.604169,0.007882,0.021490,0.033142,0.002265,0.033081,0.005754,0.477349,0.381164,0.175198,0.445652,0.160265,0.006319,0.343088,0.248564,0.154105,0.375247,0.099906,0.061792,0.111737,0.128591,0.050985,0.031151,0.044867,0.014914,0.390904,0.293467,0.290748,0.255281,0.369810,0.381203,0.630416,0.302807,0.223538,0.201420,0.076862,0.110240,0.121443,0.632255,0.165486,0.186042,0.212174,0.207869,0.240875,0.182668,0.317802,0.495523,0.592902,0.521156,0.587421,0.558666,0.637429,0.220641,0.089678,0.137550,0.180915,0.003654,0.489367,0.007616,0.004020,0.009356,0.010456,0.006397,0.279126,0.300481,0.434040,0.452624,0.399650,0.360595,0.280602,0.524745,0.582164,0.469267,0.414811,0.339682,0.716884,0.611522,0.497778,0.676477,0.201466,0.710634,0.756433,0.806072,0.753934,0.003413,0.334389,0.121909,13.6,5.3,23.8,63.9,11.4,59.4,3.0,1.0,-55.72,19.19,-58.42,12703362.39
991,0.001484,0.005932,0.008818,0.004923,0.003710,0.007648,0.004186,0.523638,0.559141,0.619197,0.702602,0.624201,0.385008,0.374188,0.344987,0.347358,0.349493,0.323812,0.393208,0.380999,0.424865,0.299349,0.237630,0.099544,0.137958,0.145864,0.194792,0.060484,0.093450,0.167049,0.218225,0.562753,0.475187,0.184669,0.187820,0.001104,0.002561,0.000389,0.000587,0.000702,0.004238,0.985151,0.989208,0.996422,0.997560,0.995491,0.935894,0.591766,0.054343,0.378363,0.675704,0.627997,0.497265,0.511825,0.523108,0.439666,0.000452,0.000697,0.000717,0.000268,0.000652,0.000841,0.996405,0.999484,0.997077,0.996257,0.999228,0.998315,0.996665,0.503494,0.004481,0.600015,0.009261,0.020647,0.026675,0.002764,0.025092,0.006034,0.496480,0.381847,0.150877,0.448233,0.172484,0.005389,0.341563,0.240741,0.132053,0.373502,0.108233,0.060383,0.111687,0.132759,0.048923,0.034814,0.045818,0.014255,0.429569,0.312746,0.316609,0.281276,0.418136,0.357455,0.642271,0.346631,0.230074,0.210372,0.079715,0.119738,0.107335,0.623587,0.175574,0.181938,0.213488,0.188965,0.223154,0.166484,0.304995,0.487319,0.592562,0.517326,0.585633,0.555051,0.641420,0.226249,0.087334,0.118208,0.191284,0.003150,0.489603,0.014346,0.005438,0.011374,0.014300,0.009783,0.319875,0.326201,0.456141,0.491186,0.437947,0.402078,0.282615,0.529252,0.577805,0.469601,0.408853,0.336499,0.702736,0.571098,0.460190,0.675064,0.204692,0.712876,0.754689,0.806063,0.757972,0.003653,0.337496,0.128074,15.4,4.5,22.8,78.7,18.5,70.6,2.0,3.0,33.38,70.64,-115.14,7364178.61

In [ ]:
df_merge['Suborder'].value_counts()

Suborder
tiranni    509
passeri    298
Name: count, dtype: int64

In [ ]:
df_merge.to_csv('data_total/data_songs_avonet.csv', index=False)