In [1]:
import pandas as pd
import utils

pd.set_option('display.max_columns', None)

In [2]:
archivo_excel = 'ruta/al/archivo.xlsx'
avonet1 = pd.read_excel("./data_total/AVONET Supplementary dataset 1.xlsx", sheet_name='AVONET1_BirdLife')
df = pd.read_csv("./data_total/data_specie.csv")

In [3]:
avonet1 = avonet1[avonet1['Order1'] == 'Passeriformes']
avonet1['Species1'] = avonet1['Species1'].str.replace(" ", "_")
avonet1.head()

,Sequence,Species1,Family1,Order1,Avibase.ID1,Total.individuals,Female,Male,Unknown,Complete.measures,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-Wing.Index,Tail.Length,Mass,Mass.Source,Mass.Refs.Other,Inference,Traits.inferred,Reference.species,Habitat,Habitat.Density,Migration,Trophic.Level,Trophic.Niche,Primary.Lifestyle,Min.Latitude,Max.Latitude,Centroid.Latitude,Centroid.Longitude,Range.Size
2794,4496.0,Acanthisitta_chloris,Acanthisittidae,Passeriformes,AVIBASE-7D5E37D9,6,3,3,0,4,12.1,6.3,2.4,2.2,18.0,46.0,6.2,38.1,13.9,23.5,6.91,Dunning,NaN,NO,NaN,NaN,Forest,1,1.0,Carnivore,Invertivore,Insessorial,-47.28,-35.38,-42.25,172.19,152503.84
2795,4498.0,Xenicus_gilviventris,Acanthisittidae,Passeriformes,AVIBASE-19420218,5,1,1,3,4,13.8,7.7,3.9,3.3,23.2,49.0,8.1,40.0,16.8,13.3,17.59,Dunning,NaN,NO,NaN,NaN,Shrubland,2,1.0,Carnivore,Invertivore,Generalist,-46.07,-41.01,-43.99,169.31,11157.46
2796,6222.0,Acanthiza_apicalis,Acanthizidae,Passeriformes,AVIBASE-4413633D,20,8,12,0,4,11.0,5.9,2.2,2.6,19.0,51.0,7.2,43.2,14.2,44.1,7.62,Dunning,NaN,NO,NaN,NaN,Woodland,2,1.0,Carnivore,Invertivore,Insessorial,-36.00,-16.78,-27.63,131.95,4124270.80
2797,6218.0,Acanthiza_chrysorrhoa,Acanthizidae,Passeriformes,AVIBASE-B1B0E343,13,5,8,0,4,11.7,6.2,2.1,2.5,18.0,58.3,9.1,49.1,15.6,37.9,9.29,Dunning,NaN,NO,NaN,NaN,Woodland,2,1.0,Carnivore,Invertivore,Terrestrial,-43.64,-18.56,-28.80,136.41,4590956.34
2798,6217.0,Acanthiza_cinerea,Acanthizidae,Passeriformes,AVIBASE-BCF9128E,8,0,8,0,4,10.6,6.0,2.6,2.8,19.2,52.0,10.1,42.2,19.2,32.4,7.60,Dunning,NaN,NO,NaN,NaN,Forest,1,1.0,Carnivore,Invertivore,Insessorial,-10.11,-0.56,-5.22,141.57,124509.89

In [4]:
species_avonet = avonet1['Species1'].unique()
species_df = df['Especie'].unique()

In [5]:
especies_no_encontradas = [species for species in species_df if species not in species_avonet]
len(especies_no_encontradas)

37

In [6]:
especies_no_encontradas[0]

'Chalcothraupis_ruficervix'

In [7]:
avonet1[avonet1['Species1'].str.contains('vitriolina', case=False, na=False)]

,Sequence,Species1,Family1,Order1,Avibase.ID1,Total.individuals,Female,Male,Unknown,Complete.measures,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-Wing.Index,Tail.Length,Mass,Mass.Source,Mass.Refs.Other,Inference,Traits.inferred,Reference.species,Habitat,Habitat.Density,Migration,Trophic.Level,Trophic.Niche,Primary.Lifestyle,Min.Latitude,Max.Latitude,Centroid.Latitude,Centroid.Longitude,Range.Size
8300,11122.0,Tangara_vitriolina,Thraupidae,Passeriformes,AVIBASE-A7B6279C,87,6,6,75,4,12.2,7.7,5.9,5.8,20.4,73.1,14.8,56.1,20.9,57.3,23.0,Dunning,NaN,NO,NaN,NaN,Shrubland,2,1.0,Omnivore,Frugivore,Insessorial,-0.14,8.39,4.43,-75.52,123913.11

In [8]:
#avonet1['Species1'] = avonet1['Species1'].str.replace("Tangara_vitriolina", "Stilpnia_vitriolina")

In [9]:
df, avonet1 = utils.sinonimias(df, avonet1)

In [10]:
print(f'Nuestra base de datos tiene {len(species_df)} especies')
print(f'La base de datos AVONET tiene {len(species_avonet)} especies')

Nuestra base de datos tiene 992 especies
La base de datos AVONET tiene 6614 especies

In [11]:
avonet1 = avonet1.rename(columns={'Species1': 'Especie'})

In [12]:
df_merge = pd.merge(df, avonet1, how="left", on=["Especie", "Especie"])

In [13]:
df_merge[avonet1.columns]

,Sequence,Especie,Family1,Order1,Avibase.ID1,Total.individuals,Female,Male,Unknown,Complete.measures,Beak.Length_Culmen,Beak.Length_Nares,Beak.Width,Beak.Depth,Tarsus.Length,Wing.Length,Kipps.Distance,Secondary1,Hand-Wing.Index,Tail.Length,Mass,Mass.Source,Mass.Refs.Other,Inference,Traits.inferred,Reference.species,Habitat,Habitat.Density,Migration,Trophic.Level,Trophic.Niche,Primary.Lifestyle,Min.Latitude,Max.Latitude,Centroid.Latitude,Centroid.Longitude,Range.Size
0,4891.0,Acropternis_orthonyx,Rhinocryptidae,Passeriformes,AVIBASE-6B6D07C9,9.0,2.0,5.0,2.0,4.0,22.9,10.4,4.5,6.5,36.4,94.8,5.2,89.9,5.5,88.9,89.86,Dunning,NaN,NO,NaN,NaN,Forest,1.0,1.0,Carnivore,Invertivore,Insessorial,-5.46,9.74,1.60,-76.74,112912.00
1,5853.0,Agriornis_albicauda,Tyrannidae,Passeriformes,AVIBASE-D918C06D,6.0,1.0,3.0,2.0,4.0,32.4,18.6,7.0,8.6,39.7,141.3,35.2,106.0,24.9,113.1,53.00,EltonTraits_Model,NaN,NO,NaN,NaN,Shrubland,3.0,1.0,Carnivore,Vertivore,Insessorial,-27.47,0.00,-15.22,-71.16,579914.07
2,5852.0,Agriornis_montanus,Tyrannidae,Passeriformes,AVIBASE-78427CA9,9.0,2.0,6.0,1.0,3.0,30.4,17.4,5.8,5.7,33.1,131.3,33.0,98.2,25.1,98.2,63.30,Dunning,NaN,NO,NaN,NaN,Shrubland,3.0,1.0,Carnivore,Omnivore,Insessorial,-50.11,2.51,-30.52,-68.63,2168659.57
3,7758.0,Alopochelidon_fucata,Hirundinidae,Passeriformes,AVIBASE-355CAC4F,9.0,4.0,5.0,0.0,4.0,9.2,4.4,3.7,2.3,11.0,99.0,49.2,49.5,49.9,43.6,13.96,Dunning,NaN,NO,NaN,NaN,Grassland,3.0,3.0,Carnivore,Invertivore,Aerial,-36.66,10.63,-23.48,-56.90,4295655.00
4,10457.0,Amblycercus_holosericeus,Icteridae,Passeriformes,AVIBASE-8DAADD7F,27.0,4.0,10.0,13.0,9.0,30.3,21.3,7.0,9.8,31.5,94.6,9.7,82.4,10.6,97.5,70.42,Dunning,NaN,NO,NaN,NaN,Forest,1.0,1.0,Carnivore,Invertivore,Insessorial,-18.35,23.75,9.78,-84.39,1152587.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
987,5595.0,Zimmerius_gracilipes,Tyrannidae,Passeriformes,AVIBASE-5CDCBAA4,7.0,3.0,3.0,1.0,4.0,10.0,5.1,3.4,2.8,14.8,46.7,6.1,40.6,13.3,41.8,7.13,Dunning,NaN,NO,NaN,NaN,Forest,1.0,1.0,Carnivore,Invertivore,Insessorial,-17.23,8.06,-4.86,-66.45,3855220.60
988,5591.0,Zimmerius_improbus,Tyrannidae,Passeriformes,AVIBASE-51736656,8.0,2.0,6.0,0.0,4.0,11.2,5.6,3.2,3.2,18.0,60.4,9.5,49.8,16.0,52.8,10.90,Dunning,NaN,NO,NaN,NaN,Forest,1.0,1.0,Omnivore,Invertivore,Insessorial,6.89,11.15,9.22,-72.16,24090.83
989,5588.0,Zimmerius_vilissimus,Tyrannidae,Passeriformes,AVIBASE-236A79C7,8.0,3.0,5.0,0.0,4.0,10.1,5.3,3.5,3.5,17.0,58.1,8.8,49.5,15.1,50.9,9.70,Dunning,NaN,NO,NaN,NaN,Forest,1.0,1.0,Omnivore,Invertivore,Insessorial,13.51,17.35,15.50,-90.88,71349.79
990,10416.0,Zonotrichia_capensis,Passerellidae,Passeriformes,AVIBASE-A7280FF0,169.0,24.0,59.0,86.0,22.0,13.6,8.7,5.3,6.5,23.8,63.9,11.4,56.8,16.8,59.4,20.31,Dunning,NaN,NO,NaN,NaN,Shrubland,3.0,1.0,Herbivore,Omnivore,Generalist,-55.72,19.19,-19.35,-58.42,12703362.39
991,10419.0,Zonotrichia_leucophrys,Passerellidae,Passeriformes,AVIBASE-8601A467,5.0,2.0,3.0,0.0,4.0,15.4,8.4,4.5,6.0,22.8,78.7,18.5,60.9,23.4,70.6,28.00,Dunning,NaN,NO,NaN,NaN,Shrubland,2.0,3.0,Omnivore,Omnivore,Generalist,33.38,70.64,58.71,-115.14,7364178.61